### ISSUE TITLE
Keep tags and versionname/versioncode synced

### ISSUE THREAD

**Issue by krt16s** [martykan/forecastie#1]
It would be a good thing, if you could keep the version in the tag (currently v0.1) and the actual android version in app/build.gradle (version 1.0, versioncode 1) synced. Also, just in case: Keep the versioncode updated at all time, since thats the integer that is crucial to updating. See https://developer.android.com/tools/publishing/versioning.html

**Comment by martykan** [comment]
Oh, I forgot about that. I just made a new release and fixed it.
