### ISSUE TITLE
Parsing JSON fails after fresh install (NPE on MainActivity line 501)

### ISSUE THREAD

**Issue by chrissssss** [martykan/forecastie#100]
When you're looking in line 459 (just one example, further examples are also available in the result) there is:
`"wind":null,`

JSON 
`
{  
   "city":{  
      "id":2643743,
      "name":"London",
      "coord":{  
         "lon":-0.12574,
         "lat":51.50853
      },
      "country":"GB",
      "population":0,
      "sys":{  
         "population":0
      }
   },
   "cod":"200",
   "message":0.005,
   "cnt":34,
   "list":[  
      {  
         "dt":1466704800,
         "main":{  
            "temp":293.43,
            "temp_min":291.568,
            "temp_max":293.43,
            "pressure":1019.13,
            "sea_level":1029.04,
            "grnd_level":1019.13,
            "humidity":100,
            "temp_kf":1.86
         },
         "weather":[  
            {  
               "id":501,
               "main":"Rain",
               "description":"mäßiger Regen",
               "icon":"10d"
            }
         ],
         "clouds":{  
            "all":68
         },
         "wind":{  
            "speed":2.21,
            "deg":306.504
         },
         "rain":{  
            "3h":3.6675
         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-23 18:00:00"
      },
      {  
         "dt":1466715600,
         "main":{  
            "temp":291.08,
            "temp_min":289.326,
            "temp_max":291.08,
            "pressure":1020.25,
            "sea_level":1029.96,
            "grnd_level":1020.25,
            "humidity":89,
            "temp_kf":1.76
         },
         "weather":[  
            {  
               "id":501,
               "main":"Rain",
               "description":"mäßiger Regen",
               "icon":"10n"
            }
         ],
         "clouds":{  
            "all":80
         },
         "wind":{  
            "speed":4.91,
            "deg":270.005
         },
         "rain":{  
            "3h":11.07
         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-23 21:00:00"
      },
      {  
         "dt":1466726400,
         "main":{  
            "temp":288.51,
            "temp_min":286.858,
            "temp_max":288.51,
            "pressure":1020.71,
            "sea_level":1030.65,
            "grnd_level":1020.71,
            "humidity":92,
            "temp_kf":1.65
         },
         "weather":[  
            {  
               "id":801,
               "main":"Clouds",
               "description":"ein paar Wolken",
               "icon":"02n"
            }
         ],
         "clouds":{  
            "all":12
         },
         "wind":{  
            "speed":3.51,
            "deg":252.502
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-24 00:00:00"
      },
      {  
         "dt":1466737200,
         "main":{  
            "temp":287.34,
            "temp_min":285.794,
            "temp_max":287.34,
            "pressure":1031.27,
            "sea_level":1031.27,
            "grnd_level":1031.27,
            "humidity":94,
            "temp_kf":1.55
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"wolkenbedeckt",
               "icon":"04n"
            }
         ],
         "clouds":{  
            "all":92
         },
         "wind":{  
            "speed":3.26,
            "deg":271.505
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-24 03:00:00"
      },
      {  
         "dt":1466769600,
         "main":{  
            "temp":292.47,
            "temp_min":291.028,
            "temp_max":292.47,
            "pressure":1021.23,
            "sea_level":1031.01,
            "grnd_level":1021.23,
            "humidity":100,
            "temp_kf":1.45
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":4.76,
            "deg":220.5
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-24 12:00:00"
      },
      {  
         "dt":1466780400,
         "main":{  
            "temp":291.94,
            "temp_min":290.601,
            "temp_max":291.94,
            "pressure":1020.54,
            "sea_level":1030.39,
            "grnd_level":1020.54,
            "humidity":93,
            "temp_kf":1.34
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":68
         },
         "wind":{  
            "speed":6.22,
            "deg":223.002
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-24 15:00:00"
      },
      {  
         "dt":1466791200,
         "main":{  
            "temp":290.2,
            "temp_min":288.962,
            "temp_max":290.2,
            "pressure":1020.59,
            "sea_level":1030.44,
            "grnd_level":1020.59,
            "humidity":88,
            "temp_kf":1.24
         },
         "weather":[  
            {  
               "id":500,
               "main":"Rain",
               "description":"leichter Regen",
               "icon":"10d"
            }
         ],
         "clouds":{  
            "all":64
         },
         "wind":{  
            "speed":5.32,
            "deg":220.501
         },
         "rain":{  
            "3h":0.065
         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-24 18:00:00"
      },
      {  
         "dt":1466802000,
         "main":{  
            "temp":288.41,
            "temp_min":287.273,
            "temp_max":288.41,
            "pressure":1020.91,
            "sea_level":1030.71,
            "grnd_level":1020.91,
            "humidity":0,
            "temp_kf":1.14
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"04n"
            }
         ],
         "clouds":{  
            "all":56
         },
         "wind":{  
            "speed":3.43,
            "deg":253.003
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-24 21:00:00"
      },
      {  
         "dt":1466812800,
         "main":{  
            "temp":285.97,
            "temp_min":284.94,
            "temp_max":285.97,
            "pressure":1020.99,
            "sea_level":1030.93,
            "grnd_level":1020.99,
            "humidity":93,
            "temp_kf":1.03
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"02n"
            }
         ],
         "clouds":{  
            "all":8
         },
         "wind":{  
            "speed":3.22,
            "deg":253.002
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-25 00:00:00"
      },
      {  
         "dt":1466823600,
         "main":{  
            "temp":284.05,
            "temp_min":283.121,
            "temp_max":284.05,
            "pressure":1020.65,
            "sea_level":1030.64,
            "grnd_level":1020.65,
            "humidity":94,
            "temp_kf":0.93
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":2.66,
            "deg":250.504
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-25 03:00:00"
      },
      {  
         "dt":1466834400,
         "main":{  
            "temp":285.4,
            "temp_min":284.573,
            "temp_max":285.4,
            "pressure":1020.59,
            "sea_level":1030.53,
            "grnd_level":1020.59,
            "humidity":97,
            "temp_kf":0.83
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":2.71,
            "deg":243.002
         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-25 06:00:00"
      },
      {  
         "dt":1466845200,
         "main":{  
            "temp":289.35,
            "temp_min":288.623,
            "temp_max":289.35,
            "pressure":1020.66,
            "sea_level":1030.54,
            "grnd_level":1020.66,
            "humidity":100,
            "temp_kf":0.72
         },
         "weather":[  
            {  
               "id":801,
               "main":"Clouds",
               "description":"ein paar Wolken",
               "icon":"02d"
            }
         ],
         "clouds":{  
            "all":20
         },
         "wind":{  
            "speed":2.83,
            "deg":244.502
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-25 09:00:00"
      },
      {  
         "dt":1466856000,
         "main":{  
            "temp":290.62,
            "temp_min":289.995,
            "temp_max":290.62,
            "pressure":1020.47,
            "sea_level":1030.32,
            "grnd_level":1020.47,
            "humidity":88,
            "temp_kf":0.62
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":76
         },
         "wind":null,
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-25 12:00:00"
      },
      {  
         "dt":1466866800,
         "main":{  
            "temp":290.62,
            "temp_min":290.103,
            "temp_max":290.62,
            "pressure":1020.21,
            "sea_level":1029.98,
            "grnd_level":1020.21,
            "humidity":82,
            "temp_kf":0.52
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"03d"
            }
         ],
         "clouds":{  
            "all":36
         },
         "wind":null,
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-25 15:00:00"
      },
      {  
         "dt":1466877600,
         "main":{  
            "temp":289.56,
            "temp_min":289.15,
            "temp_max":289.56,
            "pressure":1020.3,
            "sea_level":1030.14,
            "grnd_level":1020.3,
            "humidity":87,
            "temp_kf":0.41
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"wolkenbedeckt",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":92
         },
         "wind":{  
            "speed":3.51,
            "deg":277.502
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-25 18:00:00"
      },
      {  
         "dt":1466888400,
         "main":{  
            "temp":287.76,
            "temp_min":287.451,
            "temp_max":287.76,
            "pressure":1021.01,
            "sea_level":1030.95,
            "grnd_level":1021.01,
            "humidity":83,
            "temp_kf":0.31
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"03n"
            }
         ],
         "clouds":{  
            "all":36
         },
         "wind":null,
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-25 21:00:00"
      },
      {  
         "dt":1466899200,
         "main":{  
            "temp":286.41,
            "temp_min":286.207,
            "temp_max":286.41,
            "pressure":1030.93,
            "sea_level":1030.93,
            "grnd_level":1030.93,
            "humidity":88,
            "temp_kf":0.21
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"04n"
            }
         ],
         "clouds":{  
            "all":56
         },
         "wind":{  
            "speed":3.11,
            "deg":274.502
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-26 00:00:00"
      },
      {  
         "dt":1466920800,
         "main":{  
            "temp":286.87,
            "temp_min":286.771,
            "temp_max":286.87,
            "pressure":1021.35,
            "sea_level":1031.33,
            "grnd_level":1021.35,
            "humidity":92,
            "temp_kf":0.1
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"02d"
            }
         ],
         "clouds":{  
            "all":8
         },
         "wind":{  
            "speed":4.71,
            "deg":292.5
         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-26 06:00:00"
      },
      {  
         "dt":1466931600,
         "main":{  
            "temp":289.23,
            "temp_min":289.23,
            "temp_max":289.23,
            "pressure":1031.73,
            "sea_level":1031.73,
            "grnd_level":1031.73,
            "humidity":92,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"03d"
            }
         ],
         "clouds":{  
            "all":44
         },
         "wind":{  
            "speed":4.67,
            "deg":306.004
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-26 09:00:00"
      },
      {  
         "dt":1466942400,
         "main":{  
            "temp":291.173,
            "temp_min":291.173,
            "temp_max":291.173,
            "pressure":1021.73,
            "sea_level":1031.55,
            "grnd_level":1021.73,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"03d"
            }
         ],
         "clouds":{  
            "all":32
         },
         "wind":{  
            "speed":4.5,
            "deg":291.001
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-26 12:00:00"
      },
      {  
         "dt":1466953200,
         "main":{  
            "temp":291.611,
            "temp_min":291.611,
            "temp_max":291.611,
            "pressure":1021.33,
            "sea_level":1031.09,
            "grnd_level":1021.33,
            "humidity":75,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":5.23,
            "deg":276.011
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-26 15:00:00"
      },
      {  
         "dt":1466964000,
         "main":{  
            "temp":290.387,
            "temp_min":290.387,
            "temp_max":290.387,
            "pressure":1021.11,
            "sea_level":1030.92,
            "grnd_level":1021.11,
            "humidity":73,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":5.01,
            "deg":267.002
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-26 18:00:00"
      },
      {  
         "dt":1466985600,
         "main":{  
            "temp":288.061,
            "temp_min":288.061,
            "temp_max":288.061,
            "pressure":1020.54,
            "sea_level":1030.36,
            "grnd_level":1020.54,
            "humidity":91,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"wolkenbedeckt",
               "icon":"04n"
            }
         ],
         "clouds":{  
            "all":88
         },
         "wind":{  
            "speed":4.21,
            "deg":241.005
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-27 00:00:00"
      },
      {  
         "dt":1466996400,
         "main":{  
            "temp":287.117,
            "temp_min":287.117,
            "temp_max":287.117,
            "pressure":1019.37,
            "sea_level":1029.29,
            "grnd_level":1019.37,
            "humidity":92,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"04n"
            }
         ],
         "clouds":{  
            "all":76
         },
         "wind":null,
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-27 03:00:00"
      },
      {  
         "dt":1467007200,
         "main":{  
            "temp":287.666,
            "temp_min":287.666,
            "temp_max":287.666,
            "pressure":1019.31,
            "sea_level":1029.21,
            "grnd_level":1019.31,
            "humidity":92,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"wolkenbedeckt",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":92
         },
         "wind":{  
            "speed":5.16,
            "deg":255
         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-27 06:00:00"
      },
      {  
         "dt":1467018000,
         "main":{  
            "temp":288.087,
            "temp_min":288.087,
            "temp_max":288.087,
            "pressure":1019.15,
            "sea_level":1029.01,
            "grnd_level":1019.15,
            "humidity":100,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":501,
               "main":"Rain",
               "description":"mäßiger Regen",
               "icon":"10d"
            }
         ],
         "clouds":{  
            "all":68
         },
         "wind":{  
            "speed":3.31,
            "deg":271.001
         },
         "rain":{  
            "3h":4.69
         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-27 09:00:00"
      },
      {  
         "dt":1467039600,
         "main":{  
            "temp":293.096,
            "temp_min":293.096,
            "temp_max":293.096,
            "pressure":1021.02,
            "sea_level":1030.8,
            "grnd_level":1021.02,
            "humidity":80,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"überwiegend bewölkt",
               "icon":"03d"
            }
         ],
         "clouds":{  
            "all":44
         },
         "wind":{  
            "speed":4.83,
            "deg":297.502
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-27 15:00:00"
      },
      {  
         "dt":1467050400,
         "main":{  
            "temp":291.964,
            "temp_min":291.964,
            "temp_max":291.964,
            "pressure":1021.69,
            "sea_level":1031.58,
            "grnd_level":1021.69,
            "humidity":71,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"02d"
            }
         ],
         "clouds":{  
            "all":8
         },
         "wind":{  
            "speed":4.3,
            "deg":313.5
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-27 18:00:00"
      },
      {  
         "dt":1467061200,
         "main":{  
            "temp":288.088,
            "temp_min":288.088,
            "temp_max":288.088,
            "pressure":1023.08,
            "sea_level":1032.96,
            "grnd_level":1023.08,
            "humidity":71,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":2.76,
            "deg":336.502
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-27 21:00:00"
      },
      {  
         "dt":1467072000,
         "main":{  
            "temp":284.621,
            "temp_min":284.621,
            "temp_max":284.621,
            "pressure":1023.88,
            "sea_level":1033.86,
            "grnd_level":1023.88,
            "humidity":81,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":2.27,
            "deg":357.5
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-28 00:00:00"
      },
      {  
         "dt":1467082800,
         "main":{  
            "temp":282.415,
            "temp_min":282.415,
            "temp_max":282.415,
            "pressure":1034.09,
            "sea_level":1034.09,
            "grnd_level":1034.09,
            "humidity":89,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":1.26,
            "deg":334.501
         },
         "rain":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-06-28 03:00:00"
      },
      {  
         "dt":1467093600,
         "main":{  
            "temp":285.535,
            "temp_min":285.535,
            "temp_max":285.535,
            "pressure":1024.39,
            "sea_level":1034.23,
            "grnd_level":1024.39,
            "humidity":84,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":1.32,
            "deg":293.503
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-28 06:00:00"
      },
      {  
         "dt":1467104400,
         "main":{  
            "temp":289.767,
            "temp_min":289.767,
            "temp_max":289.767,
            "pressure":1024.28,
            "sea_level":1034.09,
            "grnd_level":1024.28,
            "humidity":0,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"klarer Himmel",
               "icon":"02d"
            }
         ],
         "clouds":{  
            "all":8
         },
         "wind":{  
            "speed":1.97,
            "deg":182.509
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-28 09:00:00"
      },
      {  
         "dt":1467126000,
         "main":{  
            "temp":290.681,
            "temp_min":290.681,
            "temp_max":290.681,
            "pressure":1022.46,
            "sea_level":1032.22,
            "grnd_level":1022.46,
            "humidity":73,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"wolkenbedeckt",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":92
         },
         "wind":{  
            "speed":3.96,
            "deg":229.5
         },
         "rain":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-06-28 15:00:00"
      }
   ]
}
`

**Comment by martykan** [comment]
Some other fixes were needed, but it's working again.
