### ISSUE TITLE
[FR] add (optional) clock on widget

### ISSUE THREAD

**Issue by ildar** [martykan/forecastie#103]
4x2 has indeed a lot of wasted space. I know it's no easy task to optimize it. You could look at https://play.google.com/store/apps/details?id=ru.yandex.weatherplugin to learn some bits.
Anyway, I'd like to see (optional) clock on the widget or alternative widget with the clock. If you please...

**Comment by martykan** [comment]
There is a clock widget now.

**Comment by ildar** [comment]
Yes! I see it! Thanks a lot!

**Comment by ildar** [comment]
Still not very usable:
https://github.com/martykan/forecastie/issues/51#issuecomment-238143980

пт, 5 авг. 2016 г. в 17:54, Ildar Mulyukov <ildar.mulyukov@gmail.com>:

> Yes! I see it! Thanks a lot!
>
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/
