### ISSUE TITLE
"different colors per day" sometimes does not work correctly

### ISSUE THREAD

**Issue by zoff99** [martykan/forecastie#106]
sometimes the next background color does not start at the new day (usually 02:00)
but starts in the middle of the day (e.g.: 11:00)

sometimes it's correct, sometimes it is not.

**Comment by zoff99** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/6833516/17021792/8c334e8e-4f4a-11e6-90b2-4499390a8ab6.PNG)

**Comment by zoff99** [comment]
1 month old. any news on this bug?

**Comment by martykan** [comment]
Unable to reproduce. Does it happen every time?

**Comment by zoff99** [comment]
no only at some days. not sure what the logic is, but it happens many times
