### ISSUE TITLE
Separate days with tabs

### ISSUE THREAD

**Issue by RwyAPx7XFnS8J7rCdVaY** [martykan/forecastie#11]
It would nice if the days were separated with tabs like F-Droid, I think the way it is now is a bit confusing. I made some examples :-)

![today](https://cloud.githubusercontent.com/assets/16533301/12083943/16c86f82-b2a4-11e5-85ab-ca14191d9a81.png)

![next days](https://cloud.githubusercontent.com/assets/16533301/12083940/097f62a4-b2a4-11e5-844b-3eba41d768d5.png)

**Comment by martykan** [comment]
This was my original plan, but it is technically much more complicated. I'll try to make that work

**Comment by logos88** [comment]
Another option could be something like yahoo weather:

https://lh5.ggpht.com/400xfC_duCRyCU5C1lHQn_j7VzC6BYBu7org7SAhsJz_mAmSsrXt0xd8d-YuXTgTnH_d=h900

And if you press one day of the week it opens the forecast for that day

**Comment by martykan** [comment]
Done. 

[<img src="http://i.imgur.com/cp3QxUe.png" width="250">](http://i.imgur.com/cp3QxUe.png)
