### ISSUE TITLE
More frequent Releases

### ISSUE THREAD

**Issue by Nutomic** [martykan/forecastie#123]
The last release has been almost two months ago. In that time, there have been lots of fixes and improvements according to git log. 

It would be cool if you could do releases more frequently, maybe somewhere between every week and every month.

**Comment by martykan** [comment]
I am planning on doing a release very soon, maybe even today.

**Comment by martykan** [comment]
OK, I finally did the release.

**Comment by kn00tcn** [comment]
heh, tell that to lightning browser
