### ISSUE TITLE
Maps are very slow

### ISSUE THREAD

**Issue by martykan** [martykan/forecastie#125]
I implemented a weather map feature, but the OpenWeatherMap tiles are loading very slowly, it can take up to a minute to load. Does anyone know if this is a limitation of the free service, or are their servers under big load now?

**Comment by martykan** [comment]
Nevermind, fixed.

<img src="http://i.imgur.com/aTVW8ab.png" width="400">

**Comment by udhbhav** [comment]
I am also facing the same issue. Can you please tell how to speed up the loading?
