### ISSUE TITLE
Add option to change language

### ISSUE THREAD

**Issue by verdulo** [martykan/forecastie#134]
Please add possibility to change the app-language in options, so it will be possible to use languages which are not selectable in Android.

Please also fix the link to transifex on the main page: https://www.transifex.com/forecastie/forecastie/

**Comment by ildar** [comment]
If you want a language that's excluded from the list android system has,
you'd probably better get a special app for that. Its name "more languages"
or alike
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by robinpaulson** [comment]
@verdulo Is ildar's suggestion acceptable? Which language would you like?

The second part is fixed,

**Comment by verdulo** [comment]
No, I want to translate programs to Esperanto, which is not selectable on Android. Currently I'm using another weather app: https://github.com/Kestutis-Z/World-Weather, of course when you add an option to change the language, I'll consider contributing translation.

**Comment by ildar** [comment]
Now I restored the name of the app you need: [Morelocale2](
https://www.c-lis.co.jp/our_services/morelocale-2).
That should help you to switch your whole phone's UI to the desired
language (which, I think, may be what you want).
Please talk back if that solution satisfies you.
Anyway asking each and every app developer to add "Language pref" is no
good at all. Deadend.

**Comment by robinpaulson** [comment]
> Anyway asking each and every app developer to add "Language pref" is no good at all. Deadend.

There's nothing per se wrong with asking. Any software with a decent community around it should encourage anyone to ask questions, make suggestions, propose improvements and provide pull requests. I'm glad verdulo asked, whether esperanto is implemented or no.

**Comment by robinpaulson** [comment]
@verdulo Does the suggestion of the app "Morelocale2" fulfil your requirements? If not, I'll keep this open, but it might take a while to implement.

**Comment by verdulo** [comment]
EN
I used the application [MoreLocale2](https://www.c-lis.co.jp/morelocale-2/) to switch language of the system to Esperanto, and then I used language menu in Android 9 to add Polish language (as 2.), so the language-chooser in programs is not needed to me. In far future I plain add Esperanto translation to [LineageOS](https://crowdin.com/project/lineageos-aosp), so the application MoreLocale2 won't be needed. You can close the issue.

EO
Mi uzis la aplikaĵon [MoreLocale2](https://www.c-lis.co.jp/morelocale-2/) por baskuli lingvon de la operaciumo al Esperanto, sekve mi uzis lingvoelektilon en Android 9 por aldoni la Polan lingvo (kiel duan), do enaplikaĵaj lingvoelektiloj ne estas bezonataj (al mi). Estontece (en malproksima estontece, ĉar mi havas aliajn programojn por esperantigi) mi planas fari tradukon al  [LineageOS](https://crowdin.com/project/lineageos-aosp], do la aplikaĵo MoreLocale2 ne estos plue bezonata. Vi povas fermi la problemon.

**Comment by robinpaulson** [comment]
Oh, that's excellent, I'm glad to hear you solved your problem. Cheers for letting us know.
