### ISSUE TITLE
Make forecast text translatable

### ISSUE THREAD

**Issue by osoitz** [martykan/forecastie#135]
Even if Forecastie is 100% translated to my language in Transifex, it still show sentences in English like "Scattered clouds", "Clear sky, "Few clouds", "Light rain", "Moderate rain"...

I assume those sentences come from the weather provider, and all possible sentences are known.  It would be great if Forecastie was able to show them translated to the selected language.

**Comment by artem-p** [comment]
It is already work as you described. Forecastie gets system language and makes request to OWM provider with language code as parameter. Maybe there is a difference in language codes used in android and OWM. What language do you need?

**Comment by osoitz** [comment]
I'm using it in Basque (eu). Maybe OWM doesn't have the Basque strings? If so can you tell me how to help? Ill do it gladly.

**Comment by robinpaulson** [comment]
@osoitz First step: could you check OWM to see if they support Basque language? Maybe ask them if they will?

**Comment by artem-p** [comment]
Here are languages they support:

Arabic - ar, Bulgarian - bg, Catalan - ca, Czech - cz, German - de, Greek - el, English - en, Persian (Farsi) - fa, Finnish - fi, French - fr, Galician - gl, Croatian - hr, Hungarian - hu, Italian - it, Japanese - ja, Korean - kr, Latvian - la, Lithuanian - lt, Macedonian - mk, Dutch - nl, Polish - pl, Portuguese - pt, Romanian - ro, Russian - ru, Swedish - se, Slovak - sk, Slovenian - sl, Spanish - es, Turkish - tr, Ukrainian - ua, Vietnamese - vi, Chinese Simplified - zh_cn, Chinese Traditional - zh_tw

There is no Basque.
 
[http://openweathermap.org/current#multi](url)

**Comment by robinpaulson** [comment]
Hmm, I suppose it is possible to translate the OWM messages, but it's a lot more effort than if OWM supported them directly. It may take a while to get round to this, unless you want to have a go?

**Comment by robinpaulson** [comment]
This looks related to #134 , but not identical. We should perhaps consider the other when attempting to implement one.

**Comment by osoitz** [comment]
FYI, I contacted OWM and they sent me the strings to translate. So this will hopefully be solved soon for Basque in origin.

**Comment by robinpaulson** [comment]
@osoitz Could you expand please? Do you mean OWM will soon support Basque as a language?

**Comment by osoitz** [comment]
They said they'd be glad to support Basque and I already sent them the translated strings.

You might want to keep this bug open though if you still consider implementing a solution for other languages supported by Forecastie but not OWM.

**Comment by robinpaulson** [comment]
Wow, that's excellent of them. Good to hear.

**Comment by robinpaulson** [comment]
HI @osoitz , is there any progress on OWM's promise to include the Basque language?

**Comment by osoitz** [comment]
It was included indeed shortly after we talked here. Sorry for not mentioning it. Forecastie can be enjoyed fully translated now and this issue can be closed.

**Comment by robinpaulson** [comment]
Excellent, no problem. Glad to hear it's fixed.
