### ISSUE TITLE
More results for the day?

### ISSUE THREAD

**Issue by madmuffinz** [martykan/forecastie#136]
I would like to be able to see more results per day rather every other three hours.
Even 12 results would be nicer, but I am hopeful for 24 results even.

**Comment by brarcher** [comment]
I believe that the data this application uses is from openweathermap.org . It seems to only support a [5 day/3 hour forecast](http://openweathermap.org/api) API and not not support an hourly forecast. A different data source would be necessary to get daily forecasts. There are a number of [other weather API providers](http://www.programmableweb.com/news/top-10-weather-apis/analysis/2014/11/13), but they either do not seem to offer a free option or have a limit for the number of requests possible in a day.

**Comment by madmuffinz** [comment]
Ah I see. Thanks for replying

**Comment by robinpaulson** [comment]
If #126 is implemented, we could do this, but not at the time being.

**Comment by robinpaulson** [comment]
I will close this, if we implement #126 I will be glad to include hourly forecasts.
