### ISSUE TITLE
Null Pointer Exception in AbstractWidgetProvider

### ISSUE THREAD

**Issue by xtj-9182** [martykan/forecastie#137]
Hello,
I'm getting an NPE in AbstractWidgetProvider in the latest stable version (v1.2) installed via Google Play store.

![2016_09_14_16 01 16](https://cloud.githubusercontent.com/assets/9414008/18516224/5dfd4e60-7a98-11e6-97cd-3f3634e3010f.png)

**Comment by robinpaulson** [comment]
Is anyone else seeing this? Also, do you know what causes it?

**Comment by robinpaulson** [comment]
> Is anyone else seeing this? Also, do you know what causes it?

As in, what particular action (refresh weather, open graphs, change APIkey, etc.)?

**Comment by robinpaulson** [comment]
I can't recreate this, could you provide some hints please?

**Comment by robinpaulson** [comment]
I'm going to close this, it's been over 2 years with no other reports or expansion of the problem. I will reopen if it comes up again.
