### ISSUE TITLE
Add wind strength and direction graphs

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#138]
I love the new graphs feature, it's very useful for visualising weather changes over the next few days. It'd be even greater if it had similar graphs for the wind direction and wind strength over the same period.

Cheers

**Comment by robinpaulson** [comment]
In fact, I think the graphs are a better way of visualising the data than the abstract set of numbers which make up the default view. It'd be good to have an option which makes them the default view.....

**Comment by robinpaulson** [comment]
I have started coding the additional graphs I suggested above, but am stuck on part of it. Whereabouts does Forecastie store the title for the graphs? It is in one of the files in https://github.com/martykan/forecastie/tree/master/app/src/main/res/values ?

**Comment by martykan** [comment]
That should be strings.xml. The names are not used just for the graphs, but also for other things.

**Comment by robinpaulson** [comment]
The plan for this is to use a graph to show the wind strength, with arrows from the "Weather icons" font to show the direction. My concern is this may make the graph too crowded, unless the arrows are unreadbly small. Perhaps we only add an arrow at the point in time where the wind shifts? Implying all points after that point are the same. It would of course simplify this task if the precision is low (so, only 8 directions are represented, rather than the full 360), similarly to how wind is shown in text mode.

**Comment by robinpaulson** [comment]
I have created a branch in my fork of forecastie, before I commit I would appreciate a once-over from anyone who is interested:
https://github.com/robinpaulson/forecastie/tree/add_wind_graph

It is mostly a copy and paste from the other graphs, with appropriate tweaks.

**Comment by robinpaulson** [comment]
Closing, as this is mostly implemented.
