### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by ildar** [martykan/forecastie#14]
0.4 in F-Droid declines to work.

**Comment by martykan** [comment]
Try searching for the city again.

**Comment by ildar** [comment]
Ahh!
that was the misbehaving network, so the app couldn't fetch info.
Hence the error message is user-unfriendly.

**Comment by martykan** [comment]
Yeah, I will add more descriptive error messages

**Comment by martykan** [comment]
Done. Now it should display only if there really is a JSON error.
