### ISSUE TITLE
Clarification request: Odd variable values in Graph Activity

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#142]
Are these values the correct way around?
The numbers at [GraphActivity.java#L40](https://github.com/martykan/forecastie/blob/master/app/src/main/java/cz/martykan/forecastie/activities/GraphActivity.java#L40), 41, 43, 44, 46 and 47 look wrong.

E.g.:
    float minTemp = 100000;
    float maxTemp = 0;

Should that be
float minTemp = 0;
float maxTemp = 10000;
?

**Comment by martykan** [comment]
We are trying to find numbers smaller than the previous number for minTemp, and numbers that are higher for maxTemp.
