### ISSUE TITLE
Cannot Change Background Refresh Interval to 12h or 24h

### ISSUE THREAD

**Issue by TediouslyBored** [martykan/forecastie#148]
App Version: 1.2 and 1.1
App Store: F-Droid and Google Play Store
Android Version: 4.4.2

Attempting to change the background refresh interval to either 12h or 24h results in the app closing with "Unfortunately, Forecastie has stopped."

**Comment by artem-p** [comment]
There is an array refreshIntervals in arrays.xml. It doesn't have 2 and 6 hours items.

**Comment by robinpaulson** [comment]
Fixed with #149 
Closing.
