### ISSUE TITLE
Feature request: Temperature as constant notification option

### ISSUE THREAD

**Issue by tsimonq2** [martykan/forecastie#153]
I'm coming from WeatherBug, and I'm used to always having the temperature and my location in my notifications menu so I can quickly check it when the screen is locked.

It would be nice to at the very minimum have this as an option.

I'm running Android 6.0.

**Comment by cwmke** [comment]
I think this is the same as #19?

**Comment by robinpaulson** [comment]
@cwmke Similar to that, but slightly different.

As it stands, it is possible to add forecastie to dashclock (so long as your version of dashclock supports android 6, which some don't). That allows for the user to view weather 'at a glance', without unlocking the phone. So, closing for now. If that is not good enough, please reopen.
