### ISSUE TITLE
Feature request: Zoom buttons in maps

### ISSUE THREAD

**Issue by tsimonq2** [martykan/forecastie#154]
It would be nice to have Zoom buttons (`+` and `-`)  in the maps (Rain, for example) as it sometimes makes it easier to navigate.

**Comment by robinpaulson** [comment]
Another easy one to do with leaflet, I might take a look at this.

**Comment by robinpaulson** [comment]
Thinking more on this, as it currently is, the user requires a multi-touch screen to zoom.

**Comment by robinpaulson** [comment]
Done, this will be in v1.4
