### ISSUE TITLE
Feature Request: Ubuntu Phone App

### ISSUE THREAD

**Issue by tsimonq2** [martykan/forecastie#156]
This was recently [featured on an article by OMG! Ubuntu! ](http://www.omgubuntu.co.uk/2016/10/7-awesome-open-source-android-apps)so it would be nice if an Ubuntu Phone port could be developed.

**Comment by robinpaulson** [comment]
This is out of scope for the project. I'm sure there are other applications which do weather on Ubuntu Phone.
