### ISSUE TITLE
current location

### ISSUE THREAD

**Issue by qurat08** [martykan/forecastie#159]
hello there. Im so glad to see this app. its good and working. I live in a city in another country, but when I run this app it shows weather of LONDON, I want it to show weather of my city automatically. how is this possible? any help?

**Comment by icasdri** [comment]
Once you set the city once by either searching using the "search icon" in the toolbar, or by using "Detect Location" in the menu, then that location sticks and will be used for subsequent openings of the app.

**Comment by qurat08** [comment]
Thats fine. Thankyou so much

**Comment by robinpaulson** [comment]
Question answered, closing
