### ISSUE TITLE
A Changelog would be nice :)

### ISSUE THREAD

**Issue by noisnogit** [martykan/forecastie#16]
Could you make a simple Changelog just to keep us updated about the changes from a release to another?

Thanks

**Comment by martykan** [comment]
https://github.com/martykan/forecastie/releases

**Comment by noisnogit** [comment]
Thank you :)

**Comment by dbolton** [comment]
Is it possible to link to the changelog in F-droid? (So that it shows up as one of the links in the F-droid app when you choosing to update). 

https://f-droid.org/repository/browse/?fdfilter=forecastie&fdid=cz.martykan.forecastie
