### ISSUE TITLE
Weather forecast data does not update in the background

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#162]
I have the "Background Refresh Interval" setting set to "15 mins", but it never updates until I open/foreground the app and wait a few seconds for it to download the data. This setting is important to me because I don't have a mobile/3G data plan and only periodically connect to Wifi, it would be very useful to have weather info from the last time I connected, rather than the last time I opened the app (which may have been several hours before I turned Wifi off). I wonder if the lack of a mobile/3G data connection is the problem?

**Comment by zubgjacc** [comment]
>I don't have a mobile/3G data plan and only periodically connect to Wifi

This is my use case as well.

**Comment by robinpaulson** [comment]
This appears to have been fixed at some point, maybe incidentally, maybe not. @zubgjacc Please could you check also?

**Comment by shahab-vahedi** [comment]
I suffer from the same problem in 2020.
