### ISSUE TITLE
Show UV index levels

### ISSUE THREAD

**Issue by trmendes** [martykan/forecastie#163]
It would be nice if we have the UV Index for the day and for the next few days at this apl.

**Comment by trmendes** [comment]
Any news about this feature?

**Comment by robinpaulson** [comment]
Does OWM provide UV index? Please look up and let me know.

**Comment by trmendes** [comment]
It seems like they do have it: http://owm.io/uvi

**Comment by ildar** [comment]
Yeah, but do they have it in API?

**Comment by trmendes** [comment]
If owm stands for openweathermaps it seems like they have the api and the link to the docs is: http://openweathermap.org/api/uvi .

**Comment by FridoDeluxe** [comment]
+1
Since UV index data is made avaiable via the OWM API this looks like a feasible and valuable new feature.

**Comment by robinpaulson** [comment]
Excellent, is anyone willing to implement and make a PR?

**Comment by robinpaulson** [comment]
I dug into this a bit, it appears there are eight parts to this:
1. get the data from OWM; as an example, this gets the data for my location (auckland, nz): api.openweathermap.org/v3/uvi/-36.75,174.4/2017Z.json?appid=78dfe9e10dd180fadd805075dd1a10d6
2.modify weather.java
3. modify parseresult.java to parse the result from the api call
4. modify mainactivity.java to process the values from the parser
5. modify the layout/list_row.xml (probably from L60 onwards) to display the values for the days ahead
6. modify the layout/time_widget.xml
7. modify the layout/extensive_widget
8 .modify something else in layout/ to display the "now" value

**Comment by trmendes** [comment]
:)...I hope to see this feature soon

Just let me know if you need any help with this...
cheers,
Thiago

**Comment by robinpaulson** [comment]
@trmendes 
If you're willing to fork, branch and start coding, that'd be great. I can chip in too, where I'm able.

**Comment by trmendes** [comment]
I could do that but I was checking the files and here are a few questions (Java is not my main language)

1) parseresult.java -> It's just a few lines file with one enum only. What should I edit there?
2) GenereicRequestTask.java -> seems to have to url to request the json and doInBackground is calling it. As far as my main language is not java I'm not sure what is the best approach to solve it. Shall I request the server again with a new uri? since the the link is a bit different (you have the ../uvi/...)

Again...I could work on it and it would be awesome to help but for that I will probably come up with a few questions. (IRC?)

Cheers

**Comment by robinpaulson** [comment]
Yes to making a separate call for UV data.

**Comment by robinpaulson** [comment]
I would imagine parseresult.java is OK as is, we still have the same error condition it lists (city_not_found) with uv index as with weather.

**Comment by robinpaulson** [comment]
Also, yes doinbackground calls the url, which is built by provideURL. Perhaps we need a provideUV_URL method also, called in doinbackground by a second if...then...else block, straight after calling provideURL?

**Comment by trmendes** [comment]
Thanks @robinpaulson ...I think I'm on the way here :)....just gonna study the code a bit tomorrow morning and I'll come here again :)...

**Comment by trmendes** [comment]
@robinpaulson I have the value already :D....now I have to change the layout to show it. It's working when I'm sharing the location. I'll do the code to work when you are looking for a city too :)...if I have time I'll send you a patch tomorrow!

**Comment by robinpaulson** [comment]
If you want to push to a fork in your github, it's be great to watch as you go.

**Comment by trmendes** [comment]
I'll do it tomorrow...send you a message here as soon as I'm back to the computer!

**Comment by trmendes** [comment]
Wondering if the appkey we have have access to the UVI Index api 'cause using the samples from the documentation everything works but when I change to the api using the key in the code all I get from the server is: {"msg": "Not found"}

**Comment by robinpaulson** [comment]
Hmm, can you point me to a web link for the examples you're using?

**Comment by robinpaulson** [comment]
Ah: http://openweathermap.org/api/uvi

**Comment by trmendes** [comment]
Yes!
So there they tell me to use:

http://api.openweathermap.org/data/2.5/uvi?appid={appid}&lat={lat}&lon={lon} 

and when you click in a link from their examples it will be the almost the same link chaning api for samples

http://samples.openweathermap.org/data/2.5/uvi?appid={appid}&lat={lat}&lon={lon}

---------------------- FIRST
When I use the example:

http://samples.openweathermap.org/data/2.5/uvi?lat=37.75&lon=-122.37&appid=b1b15e88fa797225412429c1c50c122a1

it returns me the UIV Json

When I change samples to api keeping the rest it returns me an JSON telling me that the key (from the example) is invalid.
---------------------- END OF FIRST

----------------------- SECOND
When I use the API from the forecastie project source it won't return me the UIV data.
------------------------

Am I using the API in a wrong way?

**Comment by robinpaulson** [comment]
Have you got your own API? Perhaps when you sign up you specify which services it works for? Or, perhaps UV i paid...

**Comment by trmendes** [comment]
Well...there is an APIKEY hardcoded in the source code, right?! Isn't that one a valid one?

**Comment by robinpaulson** [comment]
> Well...there is an APIKEY hardcoded in the source code, right?! Isn't that one a valid one?

yes, but valid for which data?

i think there are tiers of data at owm. perhaps some free, some not.

**Comment by trmendes** [comment]
I was checking the prices and for the free one it should include the uvi api, no charges. Just wondering if you have to sign to to use this uvi api.

Still...gonna check it better...

**Comment by robinpaulson** [comment]
Try this api.openweathermap.org/v3/uvi/-36.75,174.4/2017Z.json?appid=78dfe9e10dd180fadd805075dd1a10d6 that's the apikey hardcoded in the app. It appears to work for me

**Comment by trmendes** [comment]
@robinpaulson with this link you sent me I've got "message | "not found"" :(

**Comment by trmendes** [comment]
@robinpaulson I'm back! Sorry for the late reply. The last few days I was busy and didn't have much time to work at this feature. I'll probably have this time tomorrow or even late today :)....I'll, now, fork your project and push the work I did at that first day we were talking to each other so you can take a look and we both can finish this so we can have this feature for everyone :). My plans are now to create an apikey for myself and check the configurations I can do there. I still can't use the app appkey to get the right json. The link you sent me, last time I checked, returned me the same msg_error as I was getting before.

**Comment by trmendes** [comment]
If you wanna have a look this is the link: https://github.com/trmendes/forecastie/tree/feature/224

Feel free to analyze it and tell me what do you think and help me if you have the time. Like I said before, I'll work on it again late today or tomorrow!!

**Comment by trmendes** [comment]
@robinpaulson Could you clone and help me to check it? It's working now buuuut for a few cities the result is 0.0. Not sure what it means (looking for an answer here). Also, you need to refresh the screen to have the value. Gonna fix it soon :)

**Comment by trmendes** [comment]
@robinpaulson Fixed :)...it's now working! There is also an API to show you the polution in each city :D :D :D....shall we do it?

Please, check the brach, help me to test it and if you think it is ok I will submit a patch.

Cheers,
Thiago

**Comment by robinpaulson** [comment]
@trmendes Excellent work! I'm busy at the moment, will get back to this shortly. I'm looking forward to seeing this in v2.0

**Comment by robinpaulson** [comment]
Two questions though:
do you have a screenshot?
and why are threre references to "Quicklyric" in the commit log? I'm not sure what that has to do with it:
e.g. https://github.com/QuickLyric/Quic224kLyric/issues/224

**Comment by robinpaulson** [comment]
I see you've also increased the build sdk from 23 to 25 (app/build.gradle). Is there any particular reason for that? I'm keen to keep it as low as possible: the app will work on more devices and be buildable using the free sdk provided by Debian (which currently on targets v23 if i understand correctly).

**Comment by robinpaulson** [comment]
Setting up a circleci account for continuous testing might be useful also. Martykan has one for forecastie:master and it's been very useful

**Comment by trmendes** [comment]
@robinpaulson About the reference to quicklyric. A mistake! I was helping them with a bug too and it seems like I've got the wrong link to write in the commit log. The reason I increased the build sdk is because I'm on very slow internet connection today and it was not possible to download the 23. I have the 25 here.
I'll send you a screenshot tomorrow. Is that ok? Right now I don't have my phone here.

**Comment by robinpaulson** [comment]
Great, yes tomorrow is fine, understood about sdk versions; they are absurdly huge to download. I haven't looked in any detail at the code, merely skimmed. It appears great so far though. Keep it up!

**Comment by robinpaulson** [comment]
Also: yes to pollution, but let's handle that in a different issue/pull request.

**Comment by trmendes** [comment]
Some Screenshots:

![screenshot_20170712-080357](https://user-images.githubusercontent.com/16507629/28120797-b2ef58a4-66de-11e7-8488-0700f398f5f7.png)

![screenshot_20170712-080330](https://user-images.githubusercontent.com/16507629/28120794-b2a92672-66de-11e7-9ff4-b13f69bc7aa8.png)

![screenshot_20170712-080223](https://user-images.githubusercontent.com/16507629/28120799-b306c3d6-66de-11e7-82f3-5133b728d213.png)

![screenshot_20170712-080203](https://user-images.githubusercontent.com/16507629/28120795-b2a97988-66de-11e7-8350-ea09422e2c8a.png)

**Comment by robinpaulson** [comment]
Excellent, looking good. Two questions:
1. Do you think this is ready to be released?
2. Is it your intention to also add forecasts for UV index? If so, will that be released at the same time as this code, or in a future release?

**Comment by robinpaulson** [comment]
Ah, also:
UVI is UV Index
UVI Index is redundant....

**Comment by trmendes** [comment]
Ops...my mistake...gonna fix it to UV Index :)

I have been using it for the last few days and so far no problems. Sometimes I got a message "Internet not working" but wondering if this a problem with my internet or the app (my internet is not good right now)....I could have a check on the code for that as soon as I have more time here!

I'm not sure if the UV Index would be useful for the week forcart. Wht do you think? I don't think it will be hard to implement anyway! The code you guys made is pretty good :D (thanks for that)

I tell you as soon as I do a commit fixing the text!!

Anyway...how do you do the tests here? Anyone to help?

**Comment by trmendes** [comment]
Spelling fixed :P :)....buuuut I'm getting "To many requests" from the app right now! Is that "normal"?

**Comment by robinpaulson** [comment]
"Too many requests" is common, see #182.
I think forecast for UV is useful, maybe in a later release though.
If you are concerned about testing, perhaps we do v2.0 beta? Then full release when we are confident. That will also prompt translators to help with new strings.
Martykan did most of the coding, I've been looking after the project for the last month or so.

**Comment by trmendes** [comment]
@robinpaulson sorry for the late reply...tooo busy now :(....sure...I'll have a check for the UV forecast latter!!!

I'm concerned about testing :)...better...also. The API is at beta version :P :D....

I can help you somehow with a few bugs. I'll check the open issues too!! Like I said, java is not my main language but I would love to help!!

**Comment by FridoDeluxe** [comment]
Well done, nice to see this feature working so soon! I have a few ideas concerning the UV index:

1. The UV index could be optional and the user could enable/disable it in the settings. This will help to not clutter up the user interface if the user is not interested in UV (after adding air pollution the upper part of the app will become a real long list of values). If UV index is not enabled by default it will also decrease the amounts of requests and maybe prevent the "Too many requests" error message.
2. I personally think that `Very High | 8.04` is not aesthetically perfect. I would rather user parantheses for the numerical value or even better let the user choose the format in the settings (number/word/both) like the units for temperatures.

Just a few ideas I wanted to share with you...

**Comment by robinpaulson** [comment]
@FridoDeluxe 
1. is a fine point. we will release 2.0 beta and see what the feedback is after a few days of using it. i suspect you will be proved right. as for the "too may requests" message, i think whatever we do that will plague us. we need a decent way of sorting it, regardless of uv/pollution features.
2. there is merit to this suggestion too, it would indeed be consistent for instance with the rain data. again though, we can play with it via beta releases.

**Comment by robinpaulson** [comment]
At the moment, the plan for v2.0 is the end of December. Once v1.6 is released in a few weeks, I will merge this and a few other new features (wind speed graph, pressure map, legend for maps, pollution levels) into v2.0 beta. We'll release 2.0 beta as a pre-release around September and see how it goes. Once we have fixed any bugs, I will release v2.0, which will likely be plenty before December.

**Comment by robinpaulson** [comment]
I've split this issue into two pieces. This deals with the current levels, #226 will show forecast levels

**Comment by trmendes** [comment]
Hi there. Can we start to work at this feature again? Is this app still being developed?

**Comment by aershov24** [comment]
Hey guys, just let you know there is a dedicated API for Real-time UV Index, Hourly Forecast and other Sun Safety information: www.openuv.io.

**Comment by trmendes** [comment]
@aershov24 thanks for sharing. I'm going to code this feature again soon and send a new PR.
@robinpaulson Do you still a mainteiner of this project?

**Comment by arucard21** [comment]
This seems to be included in the latest release (v1.6.2). It was merged from #282 with some earlier work discussed in #245. So this issue can be closed.
