### ISSUE TITLE
Expose hard coded values

### ISSUE THREAD

**Issue by Primokorn** [martykan/forecastie#164]
Hi,
We can't theme values that are located into layout folders.
Please exposed these [color codes](https://osine.cozycloud.cc/public/hastebin/CyyEceBf).
You could move them to values > colors.xml instead.

Thank you.

**Comment by robinpaulson** [comment]
@Primokorn Please expand what you mean by values > colors.xml

Are you prepared to write code and make a pull request?

**Comment by Primokorn** [comment]
This file: https://github.com/martykan/forecastie/blob/master/app/src/main/res/values/colors.xml

No problem for the PR.

**Comment by robinpaulson** [comment]
Unfortunately I don't have much experience with this particular item; could you briefly explain what it does? The link in your first post doesn't go anywhere. Cheers

**Comment by Primokorn** [comment]
Check the PR.
Basically I redirected @android:color/xxxxx to values/colors.xml

When I created this issue I was working on a theme through the CyanogenMod theme engine. I wanted to apply a true black background with light text.
Unfortunately all colors that are located into layout folders can't be modified. This means that dark texts couldn't be inverted.

**Comment by robinpaulson** [comment]
Merged; v1.4 is due for release in a couple of weeks, it'll be in that.
