### ISSUE TITLE
leading zero missing on small temp values

### ISSUE THREAD

**Issue by zoff99** [martykan/forecastie#166]
now it displays:
```-.4°C```

it should be:
```-0.4°C```

it's the same on positive small values.

**Comment by robinpaulson** [comment]
At this line:
https://github.com/martykan/forecastie/blob/master/app/src/main/java/cz/martykan/forecastie/activities/MainActivity.java#L427

I guess we need:

if temperature < 1 then
  temperature = "0" & temperature

which may need a bit of variable type wrangling, switching from float to string and maybe back to float.

**Comment by robinpaulson** [comment]
Or perhaps better we change the decimal format, so it automatically displays the "0"; there's no need to do it manually. This is probably in "UnitConvertor.java"
