### ISSUE TITLE
Dashclock space

### ISSUE THREAD

**Issue by lcavalli** [martykan/forecastie#167]
Hi,
in dashclock extension are reported temperature and weather status on the main line, and below 4 text lines with current place, wind speed, pressure and humidity. The space used is a bit too much and other daskclock extensions are not visible. I would keep only main text and current place as secondary smaller text. Wind speed, pressure and humidity are still easily accessible by clicking on the dashclock extension.

Thanks.

PS: Very nice app!

**Comment by robinpaulson** [comment]
I believe this has been fixed with #184 

Please check when the new version is released and close if you are satisfied, or add more info as necessary.

**Comment by lcavalli** [comment]
Hi,
not sure it has been fixed in #184. I think that to modify Dashclock widget it has to be modified at:
Row 121 of app/src/main/res/values/strings.xml:
https://github.com/martykan/forecastie/blob/master/app/src/main/res/values/strings.xml#L121
Row 66 of app/src/main/java/cz/martykan/forecastie/widgets/DashClockWeatherExtension.java:
https://github.com/martykan/forecastie/blob/master/app/src/main/java/cz/martykan/forecastie/widgets/DashClockWeatherExtension.java#L66

Anyhow, I will check next release.

**Comment by robinpaulson** [comment]
@lcavalli 
Did the updates released in v1.4.1 satisfy you? If not, we can investigate further.

**Comment by robinpaulson** [comment]
Dashclock is unmaintained software, removed as per #518. Closing
