### ISSUE TITLE
Bug: Wrong capitalization in Widget

### ISSUE THREAD

**Issue by FridoDeluxe** [martykan/forecastie#171]
The weather description is wrongly capitalized in the widget, while in the app the description is correct:

![forecastie-widget-bug](https://cloud.githubusercontent.com/assets/498537/21570033/97deae8e-cec2-11e6-847f-4b33852d7a72.png)

**Comment by robinpaulson** [comment]
Hmm, I wonder if this is a fault in OWM? Do they provide the text for the different weather conditions? Doing a search in the code for Forecastie, I can't find the text "klarer" or "himmel" anywhere in the app.

**Comment by robinpaulson** [comment]
https://github.com/martykan/forecastie/blob/b544a5d3bec78e354c03674f32594d671a47a4be/app/src/main/res/values/strings.xml#L90

This line says "clear" is not translatable, which leads me to believe the text comes from OWM. I may be wrong,

**Comment by FridoDeluxe** [comment]
The text comes clearly from OWM. This is a real JSON example containing the weather description from OSM:

```json
"weather": [
    {
        "id": 800,
        "main": "Clear",
        "description": "Klarer Himmel",
        "icon": "01d"
    }
]
```

I assume there are two different ways how this string is formatted in the Forecastie app and in its widget, otherwise I can't explain why it's displayed different.

**Comment by FridoDeluxe** [comment]
I guess I found the cause: https://github.com/martykan/forecastie/blob/75b797e4d6446bd548d70d4d0d60d8ab2fffb36c/app/src/main/java/cz/martykan/forecastie/widgets/AbstractWidgetProvider.java#L116. The `toLowerCase()` at the end is unnecessary and is causing the wrong capitalization in the widget. The code for the main activity seems not to use this kind of string handling, hence it's correct inside the app itself.

**Comment by robinpaulson** [comment]
@FridoDeluxe 
Could you make a pull request, the change seems fairly straightforward and uncontroversial?

**Comment by FridoDeluxe** [comment]
Unfortunately it's currently impossible for me to help with coding (mostly lack of time to set everything up). But if nobody else fixes this capitalization bug I will provide a PR later this year. Is @martykan not active anymore?

**Comment by robinpaulson** [comment]
@FridoDeluxe 
Martykan has other priorities at the moment, I am lending a hand in the meantime. If you're busy too, I will prepare a PR shortly.

**Comment by robinpaulson** [comment]
ok, done. that should show up in v1.4, due in a couple of weeks (although i may bump earlier if there are enough other fixes)
