### ISSUE TITLE
redundant usage of permission READ_CONTACTS

### ISSUE THREAD

**Issue by denis-bogdanas** [martykan/forecastie#175]
Hello, I'm Denis Bogdanas, a research assistant at Oregon Stat University.
I'm working on a tool that automatically introduces runtime permission checks and requests for Android 6 apps. As part of this study I analyzed this app, looking for how permissions are referred in the code. 

There are 2 places in the code that call
`
ActivityCompat.shouldShowRequestPermissionRationale(this, Manifest.permission.READ_CONTACTS)`

This call will always return false, because permission READ_CONTACTS is never requested. Although this is not a bug, it probably complicates code understanding. would you be interested to fix this issue?

best regards,
Denis

**Comment by martykan** [comment]
Oh, thanks. READ_CONTACTS was never supposed to be there, it's fixed now.
