### ISSUE TITLE
Temperature (and other unit changes) do not automatically refresh

### ISSUE THREAD

**Issue by icasdri** [martykan/forecastie#176]
After changing temperature (and other units) from Settings, upon leaving, the UI does not immediately reflect the changes, requiring a manual refresh.

Steps to reproduce:
1. Refresh Forecastie and observe currently used temperature unit (say `Fahrenheit`)
2. Open Settings
3. Change temperature unit (say to `Celsius`)
4. Exit Settings (by e.g. pressing back button)
5. Observe that old temperature unit (`Fahrenheit` in this example) is still being used

Expected behavior: New temperature unit (`Celsius` in this example) is reflected upon leaving Settings

**Comment by robinpaulson** [comment]
I would guess the conversion is only done once the data is downloaded from OWM.

**Comment by robinpaulson** [comment]
I found last night that if I go offline, kill the app and restart it, the correct units are displayed.

**Comment by robinpaulson** [comment]
Which means we need to trigger the redisplay of the units when ever the user changes one of the preferred units. That said, this is low priority, most users set units and never change them.

**Comment by arucard21** [comment]
This seems to be fixed in the latest release (v1.6.2, but probably already fixed earlier than that). So this issue can be closed.

**Comment by martykan** [comment]
Great
