### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by sim6** [martykan/forecastie#178]
Firstly, thanks for your work.

What about release a new version?

**Comment by robinpaulson** [comment]
Yes, that would be good. There are a few minor changes not in new binary releases.

**Comment by robinpaulson** [comment]
done, with #187. Could you close?

**Comment by robinpaulson** [comment]
I tagged a new release, v1.3. It is available now as source and will be in fdroid within a day.

**Comment by sim6** [comment]
Thanks

**Comment by robinpaulson** [comment]
For the future release schedule, check out the milestones page:
https://github.com/martykan/forecastie/milestones

**Comment by robinpaulson** [comment]
I bumped v1.4 forward by a couple of weeks; there were build errors in v1.3 fixed after the release, and it was too much work to backport the fixes to v1.3.
