### ISSUE TITLE
Temperature as integer does not affect all temps

### ISSUE THREAD

**Issue by jabranham** [martykan/forecastie#181]
Thanks for the great app. Related to #98. 

The "show temperature as integer" setting does not seem to affect the forecasted temperatures (e.g. those below the today/tomorrow/later buttons).

**Comment by artem-p** [comment]
For me, it works as expected.

**Comment by robinpaulson** [comment]
As far as I can tell, it also isn't reflected in the graphs, they only appear to show integer temperatures.

**Comment by robinpaulson** [comment]
I can't reproduce the bug @jabranham reports either. I fixed the part I added, in #200 
closing for now, please reopen if you still get the bug
