### ISSUE TITLE
Incorrect Location Detected

### ISSUE THREAD

**Issue by Trainguyrom** [martykan/forecastie#183]
Greetings!

I'm a bit annoyed that when it attempted to detect my location, upon seeing "Verona" (I'm on the edge of Madison WI right next to Verona, and I believe my IP address says Verona) it shows the weather for what appears to be Verona New York.

I'm not familiar with the OpenWeatherMap API, but it seems reasonable to ask someone in the US (probably useful for other large countries like Russia, China, Canada, etc.) whether state/province is correct, or at least show the state/province abreviation in the location name (Verona, WI-US would work, for example)

I also attempted turning on "High Accuracy" location instead of "Battery Saving" and the issue persisted.

I'm running version 1.2 (F-Droid) on my Nexus 5X running the latest build of LineageOS

(I managed to get the correct location by searching "Madison Wisconsin" but its still an annoying issue)

Edit: Also worth noting, I have Privacy Guard enabled in LineageOS and it shows GPS used once, fine location used 37 times and coarse location never used, so I retract my statement about the methodology.

**Comment by robinpaulson** [comment]
This appears to be an issue with OWM rather than Forecastie. That said, it's still a bug which should be fixed here if we can.

What happens when you search "verona wisconsin"?

Have you dug into the OWM API? Perhaps there are clues there for selecting locations in a better way?

My second response is to say wait until there are other data providers, as detailed in #126. That is a ways off though, unless you are willing to do some coding?

**Comment by robinpaulson** [comment]
I did a search for "Verona Wisconsin" and it picked the correct location, the one in the midwest, not NY.

I'm not sure what to suggest; location resolution is always tricky, and given an ambiguous input (Verona, US), I think it's reasonable that it defaults to the most populous location. That said, it probably should give a range of matching options. I merely shortcircuited that by typing the state.

As for detecting location, it depends on the method OWM uses. Your first paragraph is slightly ambiguous, could you clarify? What do you mean by "upon seeing "Verona""?

**Comment by robinpaulson** [comment]
I did a search for "Verona Wisconsin" and it picked the correct location, the one in the midwest, not NY.

I'm not sure what to suggest; location resolution is always tricky, and given an ambiguous input (Verona, US), I think it's reasonable that it defaults to the most populous location. That said, it probably should give a range of matching options. I merely shortcircuited that by typing the state.

As for detecting location, it depends on the method OWM uses. Your first paragraph is slightly ambiguous, could you clarify? What do you mean by "upon seeing "Verona""?

**Comment by bolbishvili** [comment]
I am in Williamson County, Illinois. Forecastie shows my location as "Williamson County, US" and gives me weather information for Williamson County, Texas.  

If I search for location "Marion, IL" then it gives me correct weather information (displaying it as "Marion, US")

**Comment by robinpaulson** [comment]
This should be fixed with the PR in #315.  I will be releasing it soon, please check back in 10 days or so.

**Comment by Lee-Carre** [comment]
For context, I recently learned (via a mail exchange with staff) that OWM uses [GeoNames](//www.geonames.org/) ([map](//www.geonames.org/v3/)) for locations.

So, it would seem sensible to first ensure that the desired cities are correct & unambiguous in the GeoNames data.
