### ISSUE TITLE
Add transparency to background widget

### ISSUE THREAD

**Issue by daycode** [martykan/forecastie#186]
Allow user to select the transparency of backgound color of the widget

**Comment by robinpaulson** [comment]
#164 helps with this

**Comment by justadroid** [comment]
Hi,
will it work if we just add this line to "extensive_widget.xml"
and to "time_widget.xml":

android:background="@android:color/transparent"

how can this be done? I tried substituting the original xlm files with the modified ones but even in root and read/write access allowed the files cannot be placed in the directory. Is this possible in any other way? Can the developer simply add this line and update the app, if this is all it takes for it to work?

**Comment by robinpaulson** [comment]
@justadroid 
Possibly, that looks about right. I'm not sure which widget we should modify, I can look into it shortly.

I don't know if it's possible to merely add the file to the appropriate directory, is that somewhere in /data?

Yes, the developer can add that line and update the app. I'm not the developer but I am looking after the project for the time being, martykan is a bit busy at the moment.

There are plans to allow the widgets to be themed separately to the app itself, those plans are detailed in #133 . This is related to that, and I guess should be a component part of it.

**Comment by ildar** [comment]
The original issue was about transparency of some level, not 100%
transparent. Though for me 100% transparent is better then 0% transparent.

**Comment by justadroid** [comment]
@robinpaulson great, yes its in data/app/forecastie directory/res/xml

there is also /xml-v17

I am wondering if we are speaking of reverse engineering here?

@ildar agreed. also, if i understand correctly for the degree of transparency it has to be something on the color , for example from FF to 00 

`<color name="transparent_red">#99FF0000</color>`

I found this info here:
[https://stackoverflow.com/questions/6562962/transparent-widget-background#6563101](url)

**Comment by robinpaulson** [comment]
@justadroid 
If the code for a number is 6 digits, then the digits represent rgb (two digits for each colour)
If the code is 8 digits, then the first 6 are as above and the final two are for alpha, or transparency
https://en.wikipedia.org/wiki/RGBA_color_space

**Comment by robinpaulson** [comment]
I don't know what /xml-v17 is, that doesn't exist in the code. It is maybe generated by Android/Forecastie at run time?

**Comment by robinpaulson** [comment]
I'm going to close this issue and add a relevant note to #133 so it includes the points raised here.
