### ISSUE TITLE
Provide weather notifications in status bar

### ISSUE THREAD

**Issue by cwmke** [martykan/forecastie#19]
A notification would be very useful.  Something similar to [Weather Notification](https://bitbucket.org/gelin/weather-notification) would be great in terms of appearance and functionality.  I particularily like the mini-forcast in the drawer.  Thanks for any consideration.

![screenshot_20160109-144556](https://cloud.githubusercontent.com/assets/1923967/12218901/5fe84360-b6f3-11e5-8edf-a4c5c3bf7e38.png)

![screenshot_20160109-144604](https://cloud.githubusercontent.com/assets/1923967/12218909/a35b2752-b6f3-11e5-921f-4b6cb6c9f116.png)

**Comment by RwyAPx7XFnS8J7rCdVaY** [comment]
+1 I was going to suggest this too. I have a cellphone that doesn't support DashClock and a notification would be a nice alternative

**Comment by robinpaulson** [comment]
This looks like an interesting idea, but the obvious question springs to mind: why not use "Weather Notification"? It's in g play and fdroid, I have it installed now alongside forecastie and it works very well. It even does a lock screen widget.

**Comment by cwmke** [comment]
That's a good point but one thing I do pretty frequently is check the detailed weather in the notification drawer and then tap it if I want to see maps or more information. If it was built into Forcastie, this would open the app for me to do so. 

In addition, having both installed duplicates location and weather requests.

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by robinpaulson** [comment]
OK to both points. Are you willing to contribute code? Otherwise, this may be a ways off

**Comment by cwmke** [comment]
No time or ability I'm afraid. Whenever/if you decide to add it is great to me. Thanks!

**Comment by yone0527** [comment]
is their any chance to have forecastie a notification?

**Comment by robinpaulson** [comment]
@yone0527 absolutely, but only when someone does the coding. Are you willing to?

**Comment by yone0527** [comment]
nope, im just waiting to the app to have a notification features.

**Comment by avuton** [comment]
> This looks like an interesting idea, but the obvious question springs to mind: why not use "Weather Notification"?

I've used weather notification for a long time, but it stopped working (some API bitrot it appears) on Jun 22nd. I've scoured F-Droid for a replacement, but none of them appear to support notifications.

**Comment by fAntel** [comment]
I'd like to implement this feature. I suppose there will be some pitfalls because I have only implemented notifications for min sdk version 21 but I hope I'll send PR in week or two.

**Comment by fAntel** [comment]
I haven't disappeared, I just was busy more than I thought I would. Work in progress. I've almost done with notification and it left to add settings for notification and check how it works on different versions of Android.

**Comment by 07416** [comment]
related  #481

Is this issue about any status bar icons (e.g. temperature, the current weather condition)?

**Comment by fAntel** [comment]
Yes, current weather in status bar will be implemented in this issue.

**Comment by 07416** [comment]
> Yes, current weather in status bar will be implemented in this issue.

That isn't clear to me (unless `37` in the screenshots is the current temperature); voted up the issue in any case.

**Comment by robinpaulson** [comment]
> I've used weather notification for a long time, but it stopped working (some API bitrot it appears) on Jun 22nd. I've scoured 
> F-Droid for a replacement, but none of them appear to support notifications.

@avuton 
I wonder if it's something as trivial as their API key has expired? i don't recall forecastie making any API-relevant upgrades in the last 4 years since I've been involved.

**Comment by avuton** [comment]
@robinpaulson They released a fixed version, which was very nice, considering that it seemed like the project was abandoned.

**Comment by fAntel** [comment]
I am so sorry about doing it so long but today I've finally sent PR with implementation of notification. I'm going to improve it (add one more view with weather forecast as on screenshot in the first post and temperature in the status bar as was requested in #481) but I need some time.

**Comment by robinpaulson** [comment]
@fAntel No need to apologise, we all have outside lives.

@cwmke There will be a new release out in a few days with the requested notifications. Closing for now, please reopen if it is not suitable.

**Comment by robinpaulson** [comment]
@fAntel I got the newest release today, with the notification. I'm very pleased with it, it's simple, clear and works well. Excellent!

**Comment by robinpaulson** [comment]
I'm not sure we need the addition of the "temperature in the status bar", that appears to be implemented already, with the "Default Androind widget"

**Comment by robinpaulson** [comment]
@07416
If you use the "Default Android widget", it provides the temperature in the status bar. I.e., the thing you wanted is now implemented.
