### ISSUE TITLE
Forecastie in Dashclock: Settings do not open

### ISSUE THREAD

**Issue by davidhedlund** [martykan/forecastie#190]
Nothing at all happens when I open Dashclock, and then click on **Settings** for Forecastie. This should at least open Forecastie.

**Comment by robinpaulson** [comment]
In all the other dashclock widgets which I have, there are settings to adjust. In the case of Forecastie, there aren't any settings for the widget. That said, the "Settings" menu item should do something, but I'm not sure opening Forecastie is the right thing.

**Comment by robinpaulson** [comment]
Perhaps it should open the settings for Forecastie?

**Comment by davidhedlund** [comment]
@robinpaulson Yes.

**Comment by robinpaulson** [comment]
@davidhedlund Are you interested in coding this?

**Comment by robinpaulson** [comment]
I guess we use the same logic as we do for the home screen widget - clicking calls the Settings Activity.

**Comment by davidhedlund** [comment]
@robinpaulson No.

**Comment by robinpaulson** [comment]
It appears #240 fixes this

**Comment by davidhedlund** [comment]
@robinpaulson Thanks.

**Comment by SpiritCroc** [comment]
@robinpaulson it fixes click action on the widget on homescreen, but it doesn't add a settings action
