### ISSUE TITLE
Widget - Forecast for the next few days

### ISSUE THREAD

**Issue by jobbb** [martykan/forecastie#198]
Hi, a widget for the forecast for the next days would be great.
For example:

![example](https://user-images.githubusercontent.com/23344828/26975172-3502af7a-4d0e-11e7-9653-f890c87661b5.JPG)

**Comment by robinpaulson** [comment]
Would you say issue #34 covers what you're after? If so, I'll mark this as a duplicate and close it. If not, please expand.

**Comment by jobbb** [comment]
Please close it, best regards.

Am 2017-06-09 12:31, schrieb robinpaulson:

**Comment by robinpaulson** [comment]
Great, cheers.
