### ISSUE TITLE
Add link to "API Key" signup page in settings

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#201]
Add a link in the settings dialogue, taking users to the page on the OWM website where they can sign up for their own API Key.

Fixes part of #182

**Comment by realmain** [comment]
If we are able to solve #182 with a unrestricted API Key, this would no longer be needed.

**Comment by robinpaulson** [comment]
True, but some users may wish to use their own key anyway.

**Comment by robinpaulson** [comment]
I'm going to close this as it has attracted little attention since we got an upgraded API key. Maybe we revisit in the future. The option to use an alternate API still exists and is relatively trivial.
