### ISSUE TITLE
Replace webview object in "About" dialogue with text object and clickable text link

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#203]
Before fixing #202 we should perhaps first replace the "webview" object with a simple clickable text field. Webview isn't necessary for a few hyperlinks.

Textview looks like it will be suitable:
https://stackoverflow.com/questions/2734270/how-do-i-make-links-in-a-textview-clickable#2746708

**Comment by splitowo** [comment]
Hi there,
I have removed the WebView and put the text directly as a dialog message. The string is relocated to strings.xml.

https://github.com/splitowo/forecastie/commit/ea81b878f288c5da12e9270b31d731aa60d1403b

I couldn't reproduce #202, the links always opened in the browser for me, but if there is no longer WebView, this should be resolved, I suppose.

Below is the comparison after(London) and before(Melbourne) the change. The layout stays pretty much the same, the hyperlinks are clickable.
![screenshot_20180308-231249](https://user-images.githubusercontent.com/10416515/37181573-d500093c-232d-11e8-894f-06c9a26cfe97.png)
![screenshot_20180308-231307](https://user-images.githubusercontent.com/10416515/37181574-d5251cf4-232d-11e8-8e10-9b529f21158f.png)

Let me know if that change is ok to pull

**Comment by robinpaulson** [comment]
Fixed with #320
