### ISSUE TITLE
Upgrade to newer (faster) version of Leaflet

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#205]
Only if it is faster and/or fixes security bugs.

Newer versions appears to have a different API.

**Comment by igor-cali** [comment]
At first glance, using leaflet.css and leaflet.js out of v1.5.1 does not bring difference nor defects on the weather map.

**Comment by robinpaulson** [comment]
Great, could you prepare a pull request?

**Comment by robinpaulson** [comment]
If you are checking out leaflet, would you mind casting your eye over #155 to see if you can figure out how to add a scale to the maps?

**Comment by igor-cali** [comment]
I did already, but could find the way so far. I need to investigate deeper in the OWM API. Cannot commit right now for a short term feedback, due to time limitations.

**Comment by robinpaulson** [comment]
That's fine, I understand, this is a fairly involved bit of coding and in a completely different language.

**Comment by robinpaulson** [comment]
I'll upgrade leaflet now, we can address the rest later, in the other issue.
