### ISSUE TITLE
Unit is incorrect on install

### ISSUE THREAD

**Issue by gappleto97** [martykan/forecastie#213]
Just grabbed the F-Droid version, and by default it showed Kelvin, but labelled it as Celsius.

**Comment by ramack** [comment]
isn't this a duplicate of #206 ?

**Comment by gappleto97** [comment]
Appears to be. I guess I should file an issue in FastHub for the search function now. I keep forgetting it's broken.

**Comment by robinpaulson** [comment]
Yep, it is a duplicate. Please search before posting.
