### ISSUE TITLE
Settings -> Temperature units: Celsius (broken)

### ISSUE THREAD

**Issue by davidhedlund** [martykan/forecastie#215]
A few days ago I got 285C in temperature, the next day Forecastie was updated but the problem persisted. This is both on the widget and on the app window.

I had set Settings -> Temperature units Celsius: Celcius when this happened. When I went to Settings -> Temperature units Celsius now when this bug occurred it was not set to "Celcius" or anything else, when I selected "Celcius" the temperature went back to normal for a short while (perhaps a minute). Now its showing 285C again.

**Comment by robinpaulson** [comment]
This is a duplicate, please search before posting

**Comment by davidhedlund** [comment]
@robinpaulson Please post the duplication link here then.

**Comment by robinpaulson** [comment]
#206

**Comment by davidhedlund** [comment]
@robinpaulson Thank you. The temperature is certainly set contrary to what the dup bug says.
