### ISSUE TITLE
Option to make widget transparent

### ISSUE THREAD

**Issue by nachoparker** [martykan/forecastie#217]
It would be great if the widget could be transparent.

As I have it now it is blue without the option to change it. I am guessing most users will not be using a blue theme/background. ;)

Great job otherwise!

Thanks

**Comment by robinpaulson** [comment]
Hi yeah, this is a dupe of #133

Please read existing issues before posting. Closing

**Comment by nachoparker** [comment]
sorry, I did skim through all the issues, but didn't see it!

thanks again for the project
