### ISSUE TITLE
Show current pollution levels

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#218]
Apparently it is available at owm

**Comment by FridoDeluxe** [comment]
Just to add a bit more information, the following air pollution data is available at OpenWeatherMap currently.

- Carbon Monoxide (CO): https://openweathermap.org/api/pollution/co
- Ozone (O₃): https://openweathermap.org/api/pollution/o3
- Nitrogen Dioxide (NO₂): https://openweathermap.org/api/pollution/no2
- Sulfur Dioxide (SO₂): https://openweathermap.org/api/pollution/so2

It's currently beta and the documentation seems to be still work-in-progress.

**Comment by robinpaulson** [comment]
Similar to #163, I'm splitting this into two issue. One for current levels, one for forecast. #227 is for the forecast levels.

**Comment by robinpaulson** [comment]
Thanks for the info on the types of pollution forecast available. Given there are four sets of info, I'm not sure where we would put those on the screen. Here's some ideas.

1. Add one line, below the UV info, in the "Current" part of the UI and in the forecast:
Pollution Levels: CO: 93ppb (Low); O3: 111DU (Normal); SO2: 4ppb (High); NO2: 8ppq (Very high)
Perhaps we add info to the Help/FAQ document suggested in #353 so users know what ppb, ppq and DU mean.

2. We completely reorganise the UI, so there is a "now" page with the info explained fully, each pollution item on its own line. Then for the forecast data, we use the shorthand version as in option 1.

3. I don't know. Help needed.

**Comment by FridoDeluxe** [comment]
1. Everything in one line probably won't fit. Concerning the units it's okay for me if they are abbreviated (as it's done for all other units on the "Current" part). Is there a scale to translate the pollution values to "Low", "Normal", "High"? An additional FAQ would be helpful indeed.
2. I like the Main Activity with current data and integrated forecast and like to keep that.
3. My proposal: Only show the main values by default, and add a settings option to show more or other values. Maybe some users are interested in pollution values but not in sunset times. Who wants to see all possible values for the "Current" weather has to live with the fact that this needs more screen estate. Of course then it should also be configurable which values are shown in the forecast.

**Comment by robinpaulson** [comment]
>     1. Everything in one line probably won't fit. Concerning the units it's okay for me if they are 
> abbreviated (as it's done for all other units on the "Current" part).

true

> Is there a scale to translate the pollution values to "Low", "Normal", "High"? An additional FAQ 
> would be helpful indeed.

I'm sure we could find a useful scale somewhere on the web. i'll see what i can turn up

>     2. I like the Main Activity with current data and integrated forecast and like to keep that.

Yeah, I'm not keen on changing that.

>     3. My proposal: Only show the main values by default, and add a settings option to show more 
> or other values. Maybe some users are interested in pollution values but not in sunset times.

Yes, sounds good. We add options in the settings to individually turn on and off all information

> Who wants to see all possible values for the "Current" weather has to live with the fact that this 
> needs more screen estate.

good point.

> Of course then it should also be configurable which values are shown  in the forecast.

**Comment by robinpaulson** [comment]
I'm going to close this, as it's been superseded by #397. This comment will ensure the two issues are linked, meaning we keep the discussion and other information referenced.
