### ISSUE TITLE
Add completed Danish translation from Transifex

### ISSUE THREAD

**Issue by twikedk** [martykan/forecastie#220]
I finished this some 4 months ago but it still haven't entered the project. Do I need to do something to make this happen? (Pull request)

**Comment by robinpaulson** [comment]
Oh, OK. As far as I can see there aren't any PRs we haven't actioned. Did you do the translation on transifex or github?

**Comment by robinpaulson** [comment]
It'd be great to get this in Forecastie of course, from what I see there isn't currently a Danish translation.

**Comment by robinpaulson** [comment]
OK, I found it on transifex. I'll see what I can do to get it in Forecastie.

**Comment by robinpaulson** [comment]
I added a branch and PR for the Danish translation. Assuming all goes well with the integration checks, this will be released as part of v1.6, in about 6 weeks.

Cheers for prompting about this.
