### ISSUE TITLE
Too Many Requests Try again

### ISSUE THREAD

**Issue by ajzx43** [martykan/forecastie#236]
Hello, 
this "Forcastie" app is great in look but while i am trying to run this code i am getting "Too Many Requests Try again error" how can i solve this please help me.
thank you

**Comment by theonetoday** [comment]
Im also having this problem. I had fixed it by enabling some access setting, but I had to reflash my ROM and I can't remember what setting it was.

**Comment by robinpaulson** [comment]
#182
