### ISSUE TITLE
Samsung A5 (2017) - SM-A250F Too Many Requests

### ISSUE THREAD

**Issue by sinqbad** [martykan/forecastie#238]
Installed from google play and fdroid and it's not working. On the bottom it says "Too Many Requests. Please Try Again". I can't set it as a widget and all the forecast data is at 0. 
![screenshot_20170808-194249](https://user-images.githubusercontent.com/16450345/29066200-d6bcb864-7c71-11e7-9af5-6de3a76ca758.png)

**Comment by robinpaulson** [comment]
If you scroll slightly down the "Issues" list, to #182, this has been reported already. Closing
