### ISSUE TITLE
Too much requests, please try again.

### ISSUE THREAD

**Issue by stemy2** [martykan/forecastie#239]
Hello,

I can't obtain any weather info from the app, just an error message when i try to update: Too much requests, please try again.

**Comment by Lemmiwinks** [comment]
Having the same problem!

**Comment by robinpaulson** [comment]
#182 #236 #238

Closing

**Comment by stemy2** [comment]
Why did you closed the subject without any explanation ? Will it be an upgrade or you will do nothing ?

**Comment by ildar** [comment]
He gave enough references to understand:
1. The issue is known.
2. The issue is discussed elsewhere.
3. This issue has no useful information that's unavailable in other issues.

Also my 5 cents: please look around in other issues before opening another.
