### ISSUE TITLE
Forecastie uses huge amounts of battery

### ISSUE THREAD

**Issue by abendebury** [martykan/forecastie#244]
Even when not opening it, on my moto X forecastie has used 39% of my battery in just a few hours, using more than my screen.

**Comment by realmain** [comment]
Strange. I haven't come across that issue before. Try turning off the background refresh in the settings.

**Comment by robinpaulson** [comment]
Where did you install it from? There are a number of rip-offs which include ads and who knows what else.

**Comment by abendebury** [comment]
Installed from google play. Will try turning off background refresh and will see if that helps.

**Comment by realmain** [comment]
Forecastie has been outdated for a year on Google Play. Try downloading from F-Droid (recommended) or Github.

**Comment by robinpaulson** [comment]
I've been using forecastie for nearly two years, never had battery issues. I'm slightly doubtful it's due to the older version on gp.
"Outdated" is not a code word for "bad"

**Comment by robinpaulson** [comment]
This is hard to diagnose without reports from more users and/or logcat output with some error messages. I'll leave it open for now, but it's unlikely to go anywhere without that.

**Comment by robinpaulson** [comment]
I'm going to close this, it's been over a year now without any further, more detailed feedback. If more info is forthcoming, I will of course reopen.
