### ISSUE TITLE
Run some AsyncTasks in real multi threads?

### ISSUE THREAD

**Issue by frankFic** [martykan/forecastie#246]
Hi,

Background tasks scheduled by AsyncTask.execute() will be run on the same background thread after Honeycomb, API 11. ([see the doc](https://developer.android.com/reference/android/os/AsyncTask.html#execute(Params...))). I found that in [AlarmReceiver](https://github.com/martykan/forecastie/blob/d2cc2eb351f58498e8fdb0c5cf955fcdc2239f34/app/src/main/java/cz/martykan/forecastie/AlarmReceiver.java#L62) method getWeather (also GetLocationAndWeatherTask#onPostExecute, GetCityNameTask#onPostExecute) two tasks are executed to get weather and get long term weather. What about using executeOnExecutor to run the tasks in real multi threads to speed up?
Another similar case I found is in MainActivity to preloadWeather.

I don't know whether you've noticed this, but hope it can help. :)

**Comment by robinpaulson** [comment]
Interesting suggestion. My first response is to wonder whether the difference in time would provide any meaningful benefit. That said, it feels like a more elegant way of handling the requests for data.

I doubt I would get round to it, do you think this is something you'd have the time and skill to do? If so, it'd also certainly be included.

**Comment by frankFic** [comment]
Sure, I will try to submit a pull request later.

**Comment by robinpaulson** [comment]
Marvelous! I'll take a look at the code, i might have to ask someone else to review too. Then we can merge it.
