### ISSUE TITLE
v1.6 ETA

### ISSUE THREAD

**Issue by realmain** [martykan/forecastie#248]
Do we have an ETA on v1.6?

It'd be nice to get a version with the new default API key out :)

Would make it more usable for casual users who do not know how to check GitHub issues for the API Key info.

**Comment by robinpaulson** [comment]
The short answer is that I've been slack on fixing the bugs in the v1.6 milestone.

The longer answer is if I move some unfixed bugs to v1.7 and v2.0 and some fixed bugs to v1.6, it's probably worth a release in the next week or so. I'll aim for Friday next (3rd November).

**Comment by realmain** [comment]
Are we still looking to release v1.6 today and push some other unfixed bugs to v1.7?

**Comment by Nutomic** [comment]
Is this app still being developed? There are lots of open PRs, and no new commits in the last 5 months.

@robinpaulson @martykan

**Comment by robinpaulson** [comment]
@realmain 
I don't know what "looking to" means.

@Nutomic 
Yes, of course it's still being developed. 5 months is not a long time. It's just a weather app.
