### ISSUE TITLE
Other icons for DashClock extension

### ISSUE THREAD

**Issue by ghost** [martykan/forecastie#25]

**Comment by martykan** [comment]
Dashclock's icon implementation is pretty bad. The current icon set is packaged as a font, so it's better compressed and more easy to use, so it's not possible to use it with Dashclock. But I'll add in Climacons too, at least for Dashclock.

**Comment by robinpaulson** [comment]
Climacons look like a good set of icons, presumably you refer to these:
https://github.com/AdamWhitcroft/climacons/archive/master.zip
Unfortunately, this in the licence is problematic: "Do not redistribute". F-droid will never include it also it's flat-out ambiguous so we should probably not use it.

**Comment by ildar** [comment]
+1 for avoiding climacons. I'd suggest contacting a free artists and ask
him. My 1st candidate would be https://gitlab.com/xphnx/

**Comment by robinpaulson** [comment]
There must be some already with a decent licence, surely?

I opened an issue on the climacons repo, their licence is contradictory and almost impossible to implement! If they refuse, next step is to cast around and see what already exists.

**Comment by robinpaulson** [comment]
This just occurred to me:
> The current icon set is packaged as a font, so it's better compressed and more easy to use

We cannot use the weather icons directly, but I'm sure it can be easily converted into a series of png/svg files and then used as icons?

From here, it appears there are indeed svg files of the font images. I'll see what I can do.

**Comment by robinpaulson** [comment]
Climacons, now with an improved and unambiguous licence:
https://github.com/mcyrulik/climacons

**Comment by robinpaulson** [comment]
Hmm, actually they're animated, I'm not sure we want that yet.

**Comment by ildar** [comment]
Any chance to have icons pluggable?

**Comment by robinpaulson** [comment]
> Any chance to have icons pluggable?

What does pluggable mean?

**Comment by ildar** [comment]
Like icon themes in launchers.

**Comment by robinpaulson** [comment]
Dashclock is unmaintained software, removed as per #518. Closing
