### ISSUE TITLE
Transparent widget

### ISSUE THREAD

**Issue by azlux** [martykan/forecastie#254]
Hi.
I love this app so I have a suggestion. 
Can you make the widget background transparent ?
On opaque color can be a little bit aggressive.

Thank for your work !
Az

**Comment by ildar** [comment]
We all love this app. But there's noone to work on it.
https://github.com/martykan/forecastie/issues/186

**Comment by azlux** [comment]
Ho sorry, I didn't see that issue. I only search on open issues.
