### ISSUE TITLE
Forecastie Abandoned?

### ISSUE THREAD

**Issue by realmain** [martykan/forecastie#255]
It doesn't seem like Forecastie has been updated in a long time. Either someone needs to be allowed to take over the project or someone might have to fork it.

It's saddening because this is the BEST weather app in my opinion :/

**Comment by robinpaulson** [comment]
A long time? Remind me when the last release was. And stop exaggerating.

**Comment by realmain** [comment]
The last release was v1.5, released on 7 July 2017. Last commit on GitHub was 14 July 2017.

I am just saying, if there is someone who can be added to be able to help provide the edits and approve pull requests (not me), it'll be faster development, since it's obvious that you are busy with your personal life too.

#248 you said that you'll aim for a 3 Nov release. And @Nutomic asked if the app is still being developed but there was no answer. 

Many people I found gave up on using Forecastie due to them not knowing about the API key stuff, I had to tell them each how to do it on Reddit among other places. Pushing the next build out with the fix from #182 would greatly help. That was from 10 Oct. Now... because of how inactive that key was due to people not using it, I don't even know of OpenStreetMap has disable my lift off of the key or not. Because they said that they were going to monitor the application usage via API key provided.

**Comment by martykan** [comment]
@dimqua Honestly it is kind of abandoned. I plan to do a big revamp with v2, but I haven't got around to it yet, I'm really busy with work and don't have much free time for opensource
