### ISSUE TITLE
Location is shown in English instead of locale name

### ISSUE THREAD

**Issue by igor-cali** [martykan/forecastie#262]
My device is set in Italian language.
In the widget location is shown in English ('Turin, IT'). It should be shown in the correct locale ('Torino, IT' as per the location in my example).

Thanks!

**Comment by martykan** [comment]
Unfortunately OpenWeatherMap only provides city names in English. So this is not possible at the moment

**Comment by igor-cali** [comment]
Thank you @martykan ,
this sounds strange, since looking to the website the city name is in the original Italian name ([city link](https://www.openweathermap.org/city/3165524)).
Thanks for your further clarifications.
Regards,
igor

**Comment by robinpaulson** [comment]
Hmm, interesting. Would you be prepared to look through the API docs and see how to ask for a city name in the selected locale? @igor-cali

**Comment by robinpaulson** [comment]
Perhaps this is fixed by using nominatim for reverse-geococing as in #266

**Comment by igor-cali** [comment]
I would like to take a look, even if I'm not familiar with the app code.
Where in the code the city name is collected?

**Comment by robinpaulson** [comment]
Hmm, I had a look, I'm not sure what to suggest.

**Comment by igor-cali** [comment]
With latest update (v1.10.3), the app started to display the location name in the locale language ("Torino", in my specific case).

**Comment by robinpaulson** [comment]
I'm not sure what you mean by "the app started to display the location name". Did it only partly display it?

**Comment by igor-cali** [comment]
@robinpaulson Previously, it showed it in English, as per this original bug report.

**Comment by robinpaulson** [comment]
OK, I was a bit unclear, I accept. It is the word "starting" I don't understand, that is the app started showing the name, but didn't finish showing it, i.e. only showed part of it.

**Comment by robinpaulson** [comment]
I wonder if you mean "With latest update (v1.10.3), the app now displays the location name in the locale language ("Torino", in my specific case)." ?

**Comment by igor-cali** [comment]
I just mean that last app update seems to work.

**Comment by igor-cali** [comment]
@robinpaulson The name in current locale is displayed when the widget is manually updated.
With the setting "Update location in background" on, the name in English is shown as soon as the location is updated automatically.
I will open a new issue.

**Comment by Lee-Carre** [comment]
For context, I recently learned (via a mail exchange with staff) that OWM uses [GeoNames](//www.geonames.org/) ([map](//www.geonames.org/v3/)) for locations.

So, it would seem sensible to first ensure that the desired cities have localised names in the GeoNames data.
