### ISSUE TITLE
Data disappears after rotation

### ISSUE THREAD

**Issue by SergeySharipov** [martykan/forecastie#268]
Weather data of main screen disappears after rotation.
If you have internet connection, you can refresh them. 
If you have't internet connection, you can't refresh. And also you can't view cached weather data.

**Comment by robinpaulson** [comment]
This feels similar to a couple of other bugs, such as one concerning the data requiring an update after changing the units.

**Comment by robinpaulson** [comment]
Well, it's working OK for me at the moment. Could you check on your device? Perhaps it was fixed without anyone realising it, there have been some big changes recently.

**Comment by robinpaulson** [comment]
Closing for now, please comment if it's still broken for you, I will reopen.
