### ISSUE TITLE
System date formats

### ISSUE THREAD

**Issue by Allen-B1** [martykan/forecastie#272]
Android provides [`DateFormat.getDateInstance()`](https://developer.android.com/reference/java/text/DateFormat.html#getDateInstance(int))

**Comment by robinpaulson** [comment]
Yep, worthwhile. Code and a pull request is the best way to get it done quickly, this is likely low priority.

**Comment by robinpaulson** [comment]
I'm going to mark this as a duplicate and close it; it's linked to another issue with more information/posts, so what you've posted won't get lost. Cheers for the info.
