### ISSUE TITLE
WebView disappear after device rotation

### ISSUE THREAD

**Issue by calbee633810** [martykan/forecastie#274]
Click About in the menu, wait until the WebView shows. Then rotating screen makes the WebView disappear. It may not be a bug but the app can be more professional and user experience can be increased if WebView can persist after device rotation.

![screen shot 2018-04-12 at 7 30 32 pm](https://user-images.githubusercontent.com/38213896/38674725-04a3a0fc-3e88-11e8-9986-50c05decdb2c.png)
Screenshot before rotation

![screen shot 2018-04-12 at 7 30 43 pm](https://user-images.githubusercontent.com/38213896/38674757-195dda26-3e88-11e8-86ab-bf540d29124f.png)
Screenshot after rotation

**Comment by robinpaulson** [comment]
This should be fixed by changing the webview to a text box, as suggested in #203

**Comment by robinpaulson** [comment]
Closing for now, I will reopen if fixing #203 does not also fix this.
