### ISSUE TITLE
Weather map location lost after device rotation

### ISSUE THREAD

**Issue by calbee633810** [martykan/forecastie#275]
Open weather map, scroll the map to another location, say US. Then rotate screen, the location return back to the very beginning location when open map. Location should persist after rotation.

![screen shot 2018-04-12 at 7 39 44 pm](https://user-images.githubusercontent.com/38213896/38675125-52b497b4-3e89-11e8-96b1-8862a07e4af2.png)
Screenshot before rotation

![screen shot 2018-04-12 at 7 40 04 pm](https://user-images.githubusercontent.com/38213896/38675147-5e69da92-3e89-11e8-964f-e8e9fca178b1.png)
Screenshot after rotation

**Comment by robinpaulson** [comment]
Is the bug fixed with the latest release, 1.6.4?

**Comment by savked** [comment]
Seems to be working properly now.

**Comment by robinpaulson** [comment]
@calbee633810 How about for you, is it working OK now?

**Comment by robinpaulson** [comment]
Hmm, it's not working for me either. It resets to the location I set for my device, rather than the place I was viewing.

**Comment by andrewmattie** [comment]
Currently testing a fix for this bug. PR should be up shortly.

**Comment by robinpaulson** [comment]
@andrewmattie Excellent, looking forward to that.

**Comment by FridoDeluxe** [comment]
Unfortunately part of the code of this PR was deleted by 34ff6a74a767f20071ee88e5803c0df0554f6fcb. Saving and restoring the map position is a useful feature, we should restore it.

**Comment by robinpaulson** [comment]
> Saving and restoring the map position is a useful feature, we should restore it.

absolutely
