### ISSUE TITLE
intercept OWM URLs

### ISSUE THREAD

**Issue by ildar** [martykan/forecastie#276]
As Forecastie shows the same weather info that's on OWM site I think it's worth adding intent for URLs like https://openweathermap.org/?q=Almaty%2C+KZ to show the into in the app.
Thanks!

**Comment by robinpaulson** [comment]
Could you expand please? Do you mean so the links can be shared via intent to another app, e.g. browser/email?

**Comment by robinpaulson** [comment]
This has been open over a year now; I'm not entirely sure what it's asking for so I'm going to close it. Please add more information if you wish, I will reopen.

**Comment by ildar** [comment]
The initial request was purely for the Lawnchair v1: it shows the weather
and if user taps it, Lawnchair pops the OWM URL.
I'm no longer interested, thanks a lot.
