### ISSUE TITLE
Don't open layout activity_scrolling and setting_toolbar

### ISSUE THREAD

**Issue by raj8980** [martykan/forecastie#277]
I use your project same as but not open a layout . It show the blank white page .
my dependencies is :
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.google.android.apps.dashclock:dashclock-api:+'
    compile 'com.roughike:bottom-bar:1.4.0.1'
    compile 'com.diogobernardino:williamchart:2.2'
}

using this it not open the layout file please tell me actually which gradle for open this 2 layout file.

**Comment by raj8980** [comment]
![prob1](https://user-images.githubusercontent.com/38714169/39397399-3b12d824-4b1c-11e8-90d7-29c4008000c4.PNG)
![prob2](https://user-images.githubusercontent.com/38714169/39397409-7163fc8c-4b1c-11e8-9af5-b02e77ba6578.PNG)

**Comment by robinpaulson** [comment]
Hi, @raj8980 I'm going to close this as it's been nearly a year and it's not strictly related to Forecastie. Hope you get the problem sorted.
