### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by mic-may** [martykan/forecastie#281]
Greetings, I love your project and I am willing to write a FAQ page on it, kindly let me know if I should go on with it or not.
Thanks.

**Comment by robinpaulson** [comment]
Or simply put the text somewhere we can view it (your website, blog,a pastebin, a comment here, etc.), then I will copy and paste it into the repository.

**Comment by robinpaulson** [comment]
If this goes well, it might be worth adding a clickable link in the app which links to the file. Either in the "About" dialogue, or in the main menu.

**Comment by robinpaulson** [comment]
@mic-may  did you get anywhere with this?

**Comment by robinpaulson** [comment]
Closing, it's been over two years.
