### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by teneresa** [martykan/forecastie#284]
Dear Sir/Madam, 
hi, my name is Valeria. I'm a graphic designer and I'd like to collaborate on your open source project and to propose free icon/logo design. If it's something you're interested in, please, let me know!

Best,
Valeria

**Comment by robinpaulson** [comment]
Thanks for the offer, do you have anything particular you'd like to suggest, or are you merely asking speculatively?

**Comment by ArchangeGabriel** [comment]
I bet it was just another utopian.io thing, or a graphics-school project.

However the current icon could be made [adaptative](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) without much effort I guess.

**Comment by robinpaulson** [comment]
@ArchangeGabriel Maybe, maybe not. It's hard to tell without more info. I'll leave it open until May (one year), then close if no response.

**Comment by robinpaulson** [comment]
I'd like to hear more about the adaptive design, would you be willing to do that?

**Comment by robinpaulson** [comment]
Well, it appears someone has done part of this already and made a pull request with the necessary code: #317 . I'll keep this open for now though, in case she answers about a new icon.

**Comment by robinpaulson** [comment]
I had a look at the work done by @teneresa , I'm pretty impressed by it. There were some nice, simple but evocative icon designs she did for other projects. I'd be interested to see what she comes up with. Whether we want another icon design is another matter.

**Comment by robinpaulson** [comment]
OK, closing since no response from @teneresa in over a year. I will reopen if there is any further response.
