### ISSUE TITLE
Wrong country for Aachen

### ISSUE THREAD

**Issue by KonstiPation** [martykan/forecastie#288]
On Android, with Forecastie version 1.6.1 installed from fDroid, when selecting Aachen as the location the country displayed is Belgium.

**Comment by hockdudu** [comment]
I would say that's because the data from OpenWeatherMap also states that Aachen is on Belgium ([example](https://openweathermap.org/find?q=aachen)). You can input "Aachen, DE" on the search field and the correct name should appear.

**Comment by robinpaulson** [comment]
I think this is outside what we can achieve here, as hockdud says, this is an issue for OWM. Closing

**Comment by Lee-Carre** [comment]
I recently learned (via a mail exchange with staff) that OWM uses [GeoNames](//www.geonames.org/) ([map](//www.geonames.org/v3/)) for locations.

So, it would be sensible to first ensure that the desired cities are correctly placed in the GeoNames data.
