### ISSUE TITLE
[suggestions] More units and localization

### ISSUE THREAD

**Issue by vmbspqmb** [martykan/forecastie#3]
Great start, the offline functionality is most useful! Here are some humble suggestions after using your app.

Wind: Kilometers per hour (kph), Miles per hour (mph)
Pressure: in Hg, mm Hg

Month first date format (12/30/2015)

Show day of the week 

Show moon instead of sun for nighttime forecasts

**Comment by martykan** [comment]
I'm working on it, it will come in v0.4 soon.

**Comment by Teyro** [comment]
Great News ;) I will add german translation if needed ;) Are there any plans for a widget?

**Comment by martykan** [comment]
I haven't thought about a widget yet, but it's a good idea.

**Comment by Teyro** [comment]
Just think about that ;) Because your app is the first real foss app what uses free services and is free... so i would help whereever i can ;) Is there a Language text file with Strings for translation?

**Comment by martykan** [comment]
I already have a German translation in v0.3, but it's not on F-Droid yet. You can get the apk from [here](https://github.com/martykan/forecastie/releases/download/v0.3/Forecastie-0.3.apk) (you might need to uninstall the app, then install the apk).

**Comment by martykan** [comment]
Finished, now just wait for v0.4 :smiley:
