### ISSUE TITLE
Quick access to graphs

### ISSUE THREAD

**Issue by MisterY** [martykan/forecastie#300]
Tapping on the way weather icon could lead to the charts screen.

Even better, there would be a combined chart somewhere on the main screen as a card.

**Comment by robinpaulson** [comment]
The first option should be relatively easy, only a line or two of code. The second would require some reworking of the existing code. Do you have the time, skills and inclination to contribute code, at least for the first part?

**Comment by robinpaulson** [comment]
For the second part, let's first get all the graphs on one set of axes (#297). Once that's working nicely, then we will do it.

**Comment by robinpaulson** [comment]
Marvellous, the new version will be out in a few days
