### ISSUE TITLE
Windchill factor

### ISSUE THREAD

**Issue by DocSniper** [martykan/forecastie#301]
Windchill factor would be nice 😃

**Comment by robinpaulson** [comment]
Perhaps we have it as an option, if the user selects it, we put the windchill temperature in brackets after the non-windchill value? Or maybe there is a convention for displaying this information. Are yu prepared to look up the info, or even submit code and a pull request? I will certainly include if you can get it working. This has some very useful information, including formulae!

[https://en.wikipedia.org/wiki/Windchill](url)

**Comment by robinpaulson** [comment]
Marking as a dupe, even though this was opened first. The other issue takes a higher level approach (accounting for humidity and wind). #321
