### ISSUE TITLE
Add note about other developers

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#302]
Forecastie has a very long tail of contributors, lots have submitted pull requests and taken part in discussions on the issues page. We should acknowledge this in the "About" dialogue. I have added text which states the app was developed by martykan "and others", perhaps we should list the most prolific of those and/or provide a link to the "contributors" list on github. Suggestions and code edits to do this are welcome.

**Comment by savked** [comment]
Perhaps redirect to link: https://github.com/martykan/forecastie/graphs/contributors when clicked on others?

Would that be enough, or would you like to add in app list of people?

**Comment by robinpaulson** [comment]
Yes, that's one option. The other is to list the top n developers in the about box of the app. I'm not sure where to put the cut off (top 5, top 10, top 20?), so maybe in the meantime we do as you suggest and possibly come back to it later.

**Comment by robinpaulson** [comment]
Also, I don't want to privilege coders arbitrarily, there are plenty of people who have also submitted useful bug requests, made suggestions on the issues page, looked up API documentation and so on. Perhaps two links, one to the "contributors" page, one to the "issues" page?

**Comment by robinpaulson** [comment]
At the moment, we have this as the text in the "About" dialogue:
A lightweight, opensource weather app.
Developed by Tomas Martykan and others.
Data provided by OpenWeatherMap, under the Creative Commons license
Icons are Weather Icons, by Lukas Bischoff and Erik Flowers, under the SIL OFL 1.1licence.

Suggestions for how to simply expand/modify this to include the above requirements.

**Comment by robinpaulson** [comment]
Suggested replacement line:

Initially developed by Tomas Martykan, with code contributions <link to contributions page>, ideas, research and discussion <link to issues page> from many others.

**Comment by FridoDeluxe** [comment]
The suggested replacement line is a good idea, also the general idea to include all contributions besides coding.

Additionally I'd propose to split the about text into two or more translation strings. If the version number is separated and marked as not translatable, it can be changed for every release. While the rest of the about text needs to be translated only once and probably changes very seldom (currently it's missing in all other languages).

**Comment by robinpaulson** [comment]
@FridoDeluxe Your second paragraph raises a good point, I hadn't considered that. Are you interested in doing it? Perhaps we do that first, then make the other changes once that's ready.

**Comment by FridoDeluxe** [comment]
Assuming that this issue also is about the `About` text in general: I think it would be helpful to include a link directly to the Issues page at GitHub. This would provide an easy indication where to file bugs or propose ideas.

**Comment by robinpaulson** [comment]
Yes, I agree.

**Comment by igor-cali** [comment]
The commit above can be cherry-picker if acknwoledged.

**Comment by robinpaulson** [comment]
I think you are perhaps better with git than I am; could you make a PR? Cheers.

**Comment by robinpaulson** [comment]
I think I figured it out, after a few errors....
