### ISSUE TITLE
Graph screen lost a *lot* of contrast on dark themes

### ISSUE THREAD

**Issue by gappleto97** [martykan/forecastie#303]
When you go there, there is very little contrast between the background, the graph background, and the labels. If would be good if the graphs could have more contrast, since that would make it much easier to read.

**Comment by robinpaulson** [comment]
Yes, this is correct, I noticed it too. Would you be willing to use an html colour-picker (the colours are defined using this method) to select an appropriate colour scheme, then report the codes here? Or make a pull request? Any decent image editor (GIMP, etc.) should have one included. Or use one of dozens on the web, e.g.:
https://www.w3schools.com/colors/colors_picker.asp
https://www.htmlcolor-picker.com/

**Comment by robinpaulson** [comment]
Cheers, @andrewmattie, new release in a few days
