### ISSUE TITLE
Wrong link to the translator mailing list

### ISSUE THREAD

**Issue by adriaaah** [martykan/forecastie#305]
The link stated in the `README.md` (line 27) in regards to the translator mailing list redirects to https://us14.list-manage.com/subscribe?u=3c81998f247e20acb6af26673, which actually does not exist (it returns a 404).

**Comment by FridoDeluxe** [comment]
If nobody is able to restore the link to the mailing list it's probably better to remove this link from `README.md` at all. Also this mailing list makes little sense as long as Forecastie's Transifex account is not fully operational  (#357).

**Comment by robinpaulson** [comment]
Closing, I will remove the relevant line from the readme.
