### ISSUE TITLE
Inches for snow

### ISSUE THREAD

**Issue by dbolton** [martykan/forecastie#32]
The app shows "Snow (1.6 mm)". I wish it would show "Snow (0.1 in)" [inches] 

I see options to change every unit (temperature, barometer, wind speed), except the unit for the amount of snow. 

(By the way, I love the app!)

**Comment by martykan** [comment]
Sure. Maybe still use milimeters for values under 0.1 inches (2.5 mm)

**Comment by RwyAPx7XFnS8J7rCdVaY** [comment]
An option on settings would be a better solution because not everybody use/understand inches (me for example) :-)

**Comment by martykan** [comment]
I meant if you have inches selected in settings, it would still use milimeters for small values anyway.

**Comment by dbolton** [comment]
I would be more inclined to stay with inches and just say "less than 0.1 inches" or "< 0.1 in".

**Comment by vmazoyer** [comment]
What about rain?
If the user selects inches for snow, it is not coherent to keep mm for rain.
On the other hand, 2.5 mm of rain is already "moderate", so by indicating "< 0.1 in" we lose a lot of resolution.
Another option would be to offer two digits for inches: 0.01 inches.

I have a preference for the last option: use the same unit for rain and snow & use a precision of two digits for inches.
What is your opinion?

**Comment by martykan** [comment]
Done.
