### ISSUE TITLE
manual input for location

### ISSUE THREAD

**Issue by trailsandskies** [martykan/forecastie#322]
For those who might want to check weather at a different place from where they are.

**Comment by robinpaulson** [comment]
I'm not sure how to interpret this; it sounds like two separate but related suggestions.

Firstly, could you expand upon "manual input" (it's already possible to manually enter a location, GPS is not required). Or do you mean something different?

By "check weather at a different place", would this be covered by #76 (Support multiple locations)?

**Comment by trailsandskies** [comment]
Thanks for responding! Ugh, no I missed that the search hourglass icon was for inputting a location, only looked in the vertical dots menu, assuming I'd be entering it in settings. I wouldn't normally miss something like that, or post a bug, I remember people talking about getting old when I was younger, holy crap is it scary.

**Comment by robinpaulson** [comment]
We all do it sometimes I guess, not a problem. Shall I close?
