### ISSUE TITLE
It's not detecting location

### ISSUE THREAD

**Issue by princev558** [martykan/forecastie#323]
Detect Location is not working

**Comment by robinpaulson** [comment]
Perhaps a *tiny* bit more detail?

**Comment by zeugmatis** [comment]
Looks like this might be a dupe of #325.

**Comment by robinpaulson** [comment]
@zeugmatis Possibly, or it could be an error elsewhere in the location stack; poor GPS reception, microG bug (it is very crashy on my device), etc.

**Comment by robinpaulson** [comment]
I'm going to assume this is indeed a dupe and close, please add more comments if required
