### ISSUE TITLE
location keeps defaulting to London

### ISSUE THREAD

**Issue by erdius** [martykan/forecastie#325]
I have location enabled and it will correctly find me and list weather for my area but after a period of time the widget and app will default back to showing London temperature

**Comment by alanruttenberg** [comment]
Not quite the same issue - I search to set a location. After a while the widget forgets and shows the default london. Running the app restores the widget location. However, on reboot location is forgotten.
I'm running with location services off.

**Comment by prog-amateur** [comment]
Hello, I have the same bug as erdius. So I have removed the widget but I would be happy to use it again.

**Comment by mkulesh** [comment]
The same bug on Android 9

**Comment by m0nsieurPsych0** [comment]
I have the same problem lineage OS 16, quite annoying.

**Comment by benji1000** [comment]
I have the same problem. This bug appeared after I switched to version 1.10.2 from F-Droid. Before that, I was using version 1.6.2 from Google Play, and didn't have this issue.

**Comment by robinpaulson** [comment]
I wonder then if the bug was introduced with version 1.9 or 1.10, both of which were released just before @erdius opened this issue. Perhaps it's related to the excellent work @andrewmattie did in PR #315 ?

**Comment by strixaluco** [comment]
I think the bug was introduced with version 1.9, as I'm having similar issue, but location keeps defaulting to Jaipur, which was my location back at the time of 1.9 release.

**Comment by robinpaulson** [comment]
@strixaluco That is an interesting point. I am currently away from my usual location and have a new place set in Forecastie; every so often it switches back to my home town.

**Comment by strixaluco** [comment]
Yes, and if I haven't gone for travel, I wouldn't even noticed this bug. It seems your experience with defaulting location falls within the same logic as well, so that's might be it.

**Comment by zeugmatis** [comment]
I am affected by this bug too - keeps defaulting back to London, GB and I am halfway around the world from there.  Manually doing "Detect Location" works great, and all is wonderful again... until it updates and resets back to London, GB.

**Comment by steamp0rt** [comment]
Same problem w/ LineageOS 16 + microG. It properly detects location, but forgets and defaults to London.

**Comment by Mati20187** [comment]
Same problem here on LineageOS 15.1

**Comment by trymeouteh** [comment]
I think the cause of it is this...

When I first installed the app but didn't have my phone location tracker on, every X minutes when it refreshes it will set the city to london. But ever since I had my phone location tracker on and the app refeshed after X minutes it no longer gets the weather in london.

**Comment by robinpaulson** [comment]
Check the new release, in the f-droid repo in a couple of days.

**Comment by benji1000** [comment]
@robinpaulson  Thank you, it's working great!

**Comment by zeugmatis** [comment]
Confirmed, working great now - thanks a ton!  :-D
