### ISSUE TITLE
Compact view

### ISSUE THREAD

**Issue by dbolton** [martykan/forecastie#33]
This is a feature request for a compact view so that you can see a full day (or more) at a time on the screen. 

If this is not the direction you want to take the app, feel free to close.

**Comment by martykan** [comment]
I like it, I'll work on it.

**Comment by felix-schiller** [comment]
As an Idea for a more compact view: The OpenWeatherMap Homepage has a diagram for the next 24 Hours. Line for temperatures, bars for precipitation and a small Icon for the condition at the bottom. Something like this would be great for a quick, compact overview.

**Comment by zoff99** [comment]
mockup:
red line high temp of the day
blue line low temp of the day

![fff_2](https://cloud.githubusercontent.com/assets/6833516/17852439/b0b01f9a-6867-11e6-8677-463be557ae1e.png)

**Comment by robinpaulson** [comment]
This is similar to some of the widget proposals, such as #198

**Comment by robinpaulson** [comment]
I'm going to close this, as I think it will be covered by a combination of #249 and #397 . Please comment here if you disagree.
