### ISSUE TITLE
Google Play Store Version outdated

### ISSUE THREAD

**Issue by bjo81** [martykan/forecastie#332]
Google Play Store version is still at 1.6.2.

**Comment by robinpaulson** [comment]
I don't have access to update the app on Google Play, also Google are utterly evil and doing anything to promote or assist them is completely wrong. I do push updates to f-droid, new versions appear there within a day or so; also the maintainers of that repo don't track, market or enclose like Google do.

**Comment by benji1000** [comment]
I agree that Google has some evil practices. However, by not putting your app on Google Play, where most users download their apps, you're not hurting Google... at all, you're kind of hurting your app and the regular Android users. Most of them will download the app, see that its obsolete, uninstall it and move on to another shitty weather app with a lot of ads and user tracking. Also, you deprive yourself of a lot of feedback that could be useful for improving your app. I believe the app should be published on F-Droid for geeky users, and also on Google Play for regular users. But that's your choice, I guess.

> I don't have access to update the app on Google Play

What do you mean? Did Google remove your access, does it belong to another user... ?

**Comment by robinpaulson** [comment]
> What do you mean? Did Google remove your access, does it belong to another user... ?

I'm not the original maintainer and I didn't put it on Google Play.

**Comment by martykan** [comment]
Sorry for the delay, I just uploaded the new APK.
