### ISSUE TITLE
Different version numbering scheme

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#333]
Up until now, I've vaguely tried to follow a semantic versioning (see https://semver.org/ for more on this numbering scheme) for releases. I'm not sure this is meaningful any longer, given that:
1. Only the latest version is supported
2. Ideas about an API are largely irrelevant when the software is only accessed by humans
3. We make lots of small, incremental changes on a fairly rapid release schedule.
4. Any forward planning is largely meaningless, the various contributors generally work on whatever appeals to them at any particular time, with no particular ideas about an overarching development plan (I don't mean to suggest that is bad, it is entirely valid and acceptable).

My proposal is we change numbering scheme, perhaps to one of the following:
A. A simple, integer-based numbering scheme (version 1, version 2, version 3, etc.).
B. A date-based version number (20190308 would be today's release, for example)
C. A more readable date-based version number, such as "March 2019", "October 2020". F-droid has logic which can easily deal with this type of versioning.
D. Something else

Suggestions please.

**Comment by Currrupted** [comment]
For me personally, I would choose either _Option C_ or something else.

The issue I see with Option C is that it seems like a numbering solely based on months would mean that new versions could only be released on a fixed time schedule, in contrast to the current system which to me appears rather independent from any specific periods of time.

**Comment by robinpaulson** [comment]
I prefer C, the others are a little obscure, as you rightly point out. If I did change the system, I'd probably limit releases to once per month at a maximum, which I don't think would be bad at all. Thinking more, it would resemble the numbering scheme used by Ubuntu.

**Comment by Currrupted** [comment]
> I agree with what you say about C and B; it is a little obscure/incomprehensible. If I did change the system, I'd probably limit releases to once per month at a maximum, which I don't think would be bad at all. Thinking more, it would resemble the numbering scheme used by Ubuntu.

That is a valid point, indeed. It would also make the progress of the application more intuitive and steady.

**Comment by FridoDeluxe** [comment]
At most one release per month whenever there are enough changes is a reasonable idea. So a month-based scheme like _Option C_ is also my preference out of the discussed options. But I would name the releases really Ubuntu-like with numbers, year first and month second to keep the ordering across years. Like this:
- 19.09 (September 2019)
- 19.10 (October 2019)
- 19.10.1 (Unplanned but necessary immediate bugfix release in October 2019)
- 20.01 (January 2020)

**Comment by robinpaulson** [comment]
@FridoDeluxe Cheers, good modification on option C. The numbering scheme used by Ubuntu has been adopted by a few other groups as well, their names escape me for the moment.

**Comment by robinpaulson** [comment]
@igor-cali You've been particularly active lately; do you have any suggestions here? Cheers

**Comment by robinpaulson** [comment]
Of course, we should also be wary of "version number inflation". This month's projected release with the "new" schema (19.11) sounds so much more advanced than 1.10.9 (which I made last night). Oddly, and of absolutely zero relevance, they are almost anagrams of each other.

**Comment by FridoDeluxe** [comment]
_Option C_ used by Ubuntu relies on their well-known half-year release schedule, so going from `20.04` to `20.10` means exactly one release. But with Forecastie's unsteady pace the progress from `20.04` to `20.10` is unknown: Are there several releases in between or were the developers just lazy for half a year? Maybe some consistently increasing version numbering scheme has advantages compared to _Option C_. Semantic versioning could be adjusted like that:
- increase major only for really big changes like a rewrite of the app or a new UI
- increase minor for every release that contains something new (even if it's just a translation)
- (use and increase patch only for pure bugfix releases, or don't use the third number at all)

Examples:
- 1.10
- (1.10.1)
- 1.11
- 2.0

Just an idea for a simplified version numbering scheme.

**Comment by igor-cali** [comment]
I would not go with option C either, since it fits with strict release cycle model.
I would suggest to use last proposal by @FridoDeluxe `MAJOR.MINOR[.PATCH]`.

**Comment by robinpaulson** [comment]
OK, in retrospect I probably treated too many releases as "patch" when they should have been "minor". I'll recalibrate my thinking according to your suggestions and continue with (a loose version of) semver . Cheers for the help.

**Comment by robinpaulson** [comment]
I have decided to release no more than one minor version per month, only patches will be released in the interim. This will partly reduce the somewhat frantic chaos of the release pattern at the moment.
