### ISSUE TITLE
UnitConvertor.java - move string values to strings.xml

### ISSUE THREAD

**Issue by igor-cali** [martykan/forecastie#337]
The functions `convertUvIndexToRiskLevel` and `getBeaufortName` return hard-coded strings, which result in untranslated text in the final app.

They should be moved to the resource strings, so they can be translated.

**Comment by robinpaulson** [comment]
Yep, I agree.

**Comment by robinpaulson** [comment]
I'll have a go at this, it shouldn't be too difficult.

**Comment by Linkid** [comment]
Hi. Are you still on it ?

**Comment by robinpaulson** [comment]
I've been slack is the answer, I may have over-committed myself. If you'd like to try, go for it.

**Comment by FridoDeluxe** [comment]
#360

**Comment by robinpaulson** [comment]
Thanks @FridoDeluxe
