### ISSUE TITLE
Location is shown in English instead of locale name from location update in background

### ISSUE THREAD

**Issue by igor-cali** [martykan/forecastie#338]
My device is set in Italian language.
In the widget location is shown in English ('Turin, IT'). It should be shown in the correct locale ('Torino, IT' as per the location in my example).

The name in current locale is correctly displayed when the widget is manually updated --> (`Torino, IT` as per the location in my example).
With the setting "Update location in background" on, the name in English is shown as soon as the location is updated automatically --> `Turin, IT`.

Thanks!

**Comment by igor-cali** [comment]
See previous issue [#262](https://github.com/martykan/forecastie/issues/262), now partially fixed.

**Comment by robinpaulson** [comment]
@igor-cali Is this still broken, if so in what way, given it is partly fixed?

**Comment by igor-cali** [comment]
Not experiencing this anymore; I will close theissue.
