### ISSUE TITLE
Date text overlaps with weather icon in widget 5x1

### ISSUE THREAD

**Issue by igor-cali** [martykan/forecastie#346]
I have custom date format set (`EEEE dd/MM/yyyy - HH:mm`), so I can see the full day name in the widget.

When the resulting string is long enough, the text collides with the centered weather icon (see image).
![IMG_20190424_093750](https://user-images.githubusercontent.com/12466054/56641578-f50d3100-6675-11e9-9acc-737f361a1fa7.jpg)

Is it possible to adapt the icon position to move a bit to the right when this happens?

Thanks!

**Comment by robinpaulson** [comment]
Hmm, an edge case but a bug nonetheless. Do you think you'd be able to code this yourself?

**Comment by igor-cali** [comment]
@robinpaulson I can try when I find some time.

**Comment by igor-cali** [comment]
I could not move the icon with precision, when needed. This is because of the limitation given by the `RemoteViews` class.
So I added a workaround in the widget provider when the date string is long enough.

See [PR 347](https://github.com/martykan/forecastie/pull/347).
