### ISSUE TITLE
Widget clock lags behind system time until application is opened

### ISSUE THREAD

**Issue by digital-mystik** [martykan/forecastie#348]
It seems that the widget clock is not synced with the system clock until the application is opened and refreshed.

**Comment by robinpaulson** [comment]
This works fine on my install, the time is always in sync, I wonder if anyone else has this bug?

Ah, do you mean the time of "last update", rather than the system time? Which widget are you using?

**Comment by digital-mystik** [comment]
> This works fine on my install, the time is always in sync, I wonder if anyone else has this bug?
> 
> Ah, do you mean the time of "last update", rather than the system time? Which widget are you using?

I am using the 4 x 1 widget. Not sure if it is only happening for me but I just noticed it the other day. I cropped out the location but the time is not synced until I open the application and then it starts falling out again after a brief moment.

![img_eggsif_1816279197550367820](https://user-images.githubusercontent.com/32280207/56858757-559ab780-696f-11e9-8538-d5fe51c75224.jpg)

**Comment by robinpaulson** [comment]
Hmm, more reports form other users needed I think.

**Comment by robinpaulson** [comment]
A question: is a clock on the widget necessary? Given that most of us have a clock in the top bar anyway, it may be redundant, particularly as you are easily able to compare the two....

Perhaps a better remedy would be to remvoe it altogether, freeing up space for weather-related information; Forecastie is a weather app, not a time app, after all.

**Comment by robinpaulson** [comment]
I think the same applies for the date as well, it adds nothing to the widget and takes up space.

Unless someone can come up with a good reason why we should keep it?

**Comment by robinpaulson** [comment]
@digital-mystik We've made many updates over the last year, including to the widgets; I wonder if this has been fixed anyone realising. Could you let us know the situation?

**Comment by digital-mystik** [comment]
@robinpaulson sorry for not checking sooner but it appears to work now. Thanks

**Comment by robinpaulson** [comment]
@digital-mystik That's great, no problem at all! I'm glad it's fixed.
