### ISSUE TITLE
Change icons for light rain and for app

### ISSUE THREAD

**Issue by myself12345** [martykan/forecastie#352]
[enhancement]
- The picture used for 'light rain' should be different from moderate/heavy rain. 
- The app icon could be better (it's ugly. your app deserves a better icon :-) )
thank you

**Comment by robinpaulson** [comment]
1. yes, i agree. i believe the icons are from an existing font set; adding to it it not trivial. neither is it a gigantic task though.
2. <shrug>, sure. it's simple, low priority i guess.

if you want to fix either, go for it.

**Comment by robinpaulson** [comment]
The source of the icons is here:
https://erikflowers.github.io/weather-icons/

**Comment by robinpaulson** [comment]
If you want to suggest a particular weather condition should use a different icon to what it currently does, go for it. Or make a pull request if you're confident with coding.

**Comment by FridoDeluxe** [comment]
Concerning the first enhancement suggestion with more suitable weather icons:
On https://erikflowers.github.io/weather-icons/api-list.html is even a list which icon belongs to which weather condition code from OWM. Implementing this list should not be that hard, I could try do do that. Or does anybody wants to stay with as few icons as possible for simplicity?

**Comment by FridoDeluxe** [comment]
I did prepare pull request #359 to provide a suitable icon for every weather condition code from OWM. There is a fallback icon for every main weather condition in case I missed a condition code  or there are undocumented ones. The string value names of the icons are now named like the classes from http://weathericons.io/.

**Comment by robinpaulson** [comment]
We'll see how it goes and close if the next release works OK. I'll put it out later today

**Comment by robinpaulson** [comment]
Looking good @FridoDeluxe , thanks for the great work. Closing
