### ISSUE TITLE
Add "Show both Celsius and Fahrenheit" option

### ISSUE THREAD

**Issue by Batcastle** [martykan/forecastie#354]
Is it possible to add an option in the temperature settings to show both Fahrenheit and Celsius scales? For instance, side by side with one in parentheses.

This would be great for those who are trying to become more accustomed to the Celsius (or Fahrenheit) scale. As long as they are labeled, to make it clear which is which.

**Comment by robinpaulson** [comment]
It is possible, yes, but I'm loathe to add more things which clutter the scree more. We are already on track to add pollution and a couple of other pieces of data, so I'd need a very convincing argument for this, which feels niche to say the least. I'm tempted to suggest carrying a piece of card with a conversion table on it, until you learn both scales. Or a pdf on the phone, if hard copy is too old school.
