### ISSUE TITLE
Enhancement idea: Support for specifc weather stations

### ISSUE THREAD

**Issue by zell-mbc** [martykan/forecastie#356]
I started to look into a little project to build my own Arduino based weather station so I get current data from my backyard instead of someone else's data. 
Long story short, how about an enhancement which allows someone to put in his own station as a data source? Supplementing the data which is loaded from OWM?
The flow of data I have in mind would be: local weather station -> Open Weather Map -> Forecastie

A local station may do temperature but not wind which means the data displayed in Forecastie could be a mix of the two data sources, all data points retrieved from the local station could be marked with e.g. a little house icon to reflect the data source.

The logic I have in mind would go something like below:
If station OWM key exists and local station data is current (station may be offline)
	request data from this specific station from OWM
Else 
	request data for my configured location location from OWM

Spinning this further, for temperature I would expect to see a difference between local station and OWM. One could hence calculate the offset and apply this as well to the temperature forecast coming from OWM?

Aside from the code changes this would also require a settings screen where one can enter his own OWM account and station key for the GET /measurements request documented here: https://openweathermap.org/stations.

Thanks

**Comment by robinpaulson** [comment]
I'm not entirely sure I understand, but I think you're asking for Forecastie to display data in realtime from weather stations which measure rainfall, wind speed, etc. While this is a worthwhile idea in general, it's a bit off from the intention of Forecastie, which is to display the forecasted weather, i.e. what will happen in the future. Let me know if I've misunderstood, closing for now.

**Comment by zell-mbc** [comment]
You got me right, my idea was to populate the blue (actual data) section on top of the screen (which I thought are ~current values rather than forecasted), with my own data instead of data pulled in from OWM.
