### ISSUE TITLE
Status of translations : imports from Transifex

### ISSUE THREAD

**Issue by Linkid** [martykan/forecastie#357]
Hi!

I'm using this app for a long time now, and I'm very happy to see updates.
However, I think translations are not up to date. Are we still using Transifex ? Because I didn't see any imports from it since a long time (for example, some strings.xml has not been updated for 3 years :/).

So, I think it could be great to clarify the way people can contribute in translations and when strings are updated ;).

Thanks.

**Comment by robinpaulson** [comment]
Personally, I don't have access to the transifex account and don't know how to use it. @martykan has typically handled that, although he may be busy at present. There is always the possibility of handling translation using github, so if there's something in particular you'd like to see, let us know here. We can even copy and paste from transifex if necessary. There have been some recent minor updates and additions to forecastie which are not reflected in non-English, we should fix that.

**Comment by FridoDeluxe** [comment]
Hopefully there will be a way to use Transifex again. In my opinion it's a low-threshold way to enable translation contributions, especially from non-coders.

Currently the `strings.xml` files are somehow structured (entries grouped and separated by empty lines). Does anybody know if this structure is kept by Transifex? The Translation Editor in Android Studio seems to ignore any structure in the files and just appends new entries. But the structure (ideally the same in every language) is helpful if you work with the xml files directly ...

**Comment by robinpaulson** [comment]
I'm going to remove the reference to transifex. I'm sure it's useful, but without proper access it is misleading. If @martykan resurrects it in the future, that is great, otherwise from now on we will handle translations within Github.
