### ISSUE TITLE
"Detect Location" failed to execute

### ISSUE THREAD

**Issue by sjl872964789** [martykan/forecastie#358]
What steps will reproduce the problem?

1. Install forecastie and open app
2. Click on three points in the upper right corner
3. Click the "Detect Location"

What is the expected output? What do you see instead?

The app should remind the user that there is no location permission, but nothing happened. Users don't know why it didn't successfully complete the function. After I tried it myself, I found out that the problem was caused by the lack of permission.

Latest from F-DROID, 1.10.4, EMUI 9.1.1, HUAWEI nova 5 pro

Recorded video see attachment

[SVID_20190813_161801_1.zip](https://github.com/martykan/forecastie/files/3500071/SVID_20190813_161801_1.zip)

**Comment by robinpaulson** [comment]
OK, well spotted. Cheers for the bug report.

**Comment by robinpaulson** [comment]
I accepted the PR from @minibugdev and made a new release today, check in a few days for the new version, it should have fixed the big. Please reopen if it isn't fixed
