### ISSUE TITLE
Forced to use "-" in custom date format

### ISSUE THREAD

**Issue by badener95** [martykan/forecastie#361]
At the moment you are forced to use a "-" in custom date format to seperate the date and the time. Otherwise the one widget that displays the date won't work and the app will crash as well once the widget is added to the launcher. The problematic line is this one:
https://github.com/martykan/forecastie/blob/8dd4fe03c55a93e243f9fde57604b65168be5839/app/src/main/java/cz/martykan/forecastie/widgets/TimeWidgetProvider.java#L59
Note that the two other widgets work fine (because they don't show the date) and also the app itself works fine without a "-" in the custom date format, as long as you don't add the mentioned widget to the launcher.

**Comment by robinpaulson** [comment]
Yes, this is a known issue, we identified it in #287. If you are interested in coding a fix, I'll gladly accept it.

**Comment by robinpaulson** [comment]
Also #219

**Comment by robinpaulson** [comment]
#272

**Comment by badener95** [comment]
Oh sorry about that duplicate then. It seems easy enough to fix, so I'll try my luck.

**Comment by badener95** [comment]
Fixed either way
