### ISSUE TITLE
Missing icon in widget

### ISSUE THREAD

**Issue by igor-cali** [martykan/forecastie#366]
Versions 1.0.5 and 1.0.6
Italian translation active.
A text is shown in place of the weather icon (see 
![screenshot](https://user-images.githubusercontent.com/12466054/66667623-bbe07180-ec53-11e9-8c0b-2752a867de4a.jpg).

'fl' text is shown for the 'few clouds'.

**Comment by robinpaulson** [comment]
Cheers @igor-cali Could you let me know which weather that is? Cloudy, light rain, snow, etc.

**Comment by robinpaulson** [comment]
Oh, sorry, I see it

**Comment by igor-cali** [comment]
Ciao,As I reported, the English is something like 'few clouds'. I need to cross-check from translations. Maybe the original English string is something like 'partially cloudy'.Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [martykan/forecastie] Missing icon in widget (#366)Da: robinpaulson A: martykan/forecastie CC: Igor ,Mention Cheers @igor-cali Could you let me know which weather that is? Cloudy, light rain, snow, etc.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/martykan/forecastie/issues/366?email_source=notifications\u0026email_token=AC7DPBRKSOAMRLA5DGJBYG3QOGMYPA5CNFSM4I733WLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBB3MHA#issuecomment-541308444",
"url": "https://github.com/martykan/forecastie/issues/366?email_source=notifications\u0026email_token=AC7DPBRKSOAMRLA5DGJBYG3QOGMYPA5CNFSM4I733WLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBB3MHA#issuecomment-541308444",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by robinpaulson** [comment]
Interesting, it works fine when the language is set to English.

**Comment by igor-cali** [comment]
Please be aware this was not systematic. I assume it is related to a specific icon. Yesterday I upgraded to 1.0.6. I will monitor if this happens again in next days (it didn't happen so far).Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [martykan/forecastie] Missing icon in widget (#366)Da: robinpaulson A: martykan/forecastie CC: Igor ,Mention Interesting, it works fine when the language is set to English.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/martykan/forecastie/issues/366?email_source=notifications\u0026email_token=AC7DPBVYOBAYRH64UMWAMRDQOGWDTA5CNFSM4I733WLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBB45FI#issuecomment-541314709",
"url": "https://github.com/martykan/forecastie/issues/366?email_source=notifications\u0026email_token=AC7DPBVYOBAYRH64UMWAMRDQOGWDTA5CNFSM4I733WLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBB45FI#issuecomment-541314709",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by FridoDeluxe** [comment]
With #359 (included in release 1.0.5) I introduced more icons and restructured the respective translations. Since the weather icons are marked as not translatable under normal circumstances there should not be any difference no matter which language is set. At least in German I have not experienced this kind of problem.

The icon for "Scattered Clouds" (OWM weather condition code 802) is the unicode character `&#xf002;` which is taken from the weather.ttf font file. In a "normal" font this seems to be the ligature **fl**: https://www.fileformat.info/info/unicode/char/f002/index.htm.

I could imagine that either some obscure bug or caching interferes with the update to 1.0.5 and the changed weather icons. Or some ligatures are automatically converted in Italian Android before it's possible to find the correct character from the weather.ttf font.

@igor-cali: It would be interesting what icon you see the next time your weather is again *Poche nuvole* during daytime.

**Comment by robinpaulson** [comment]
@igor-cali Caching was my first though when I saw the bug. If it repeats, I wonder if there is a way to clear the cache without reinstalling?

**Comment by igor-cali** [comment]
@FridoDeluxe 
Today the issued reappeared, thanks to the weather.
Following your insight, I played a bit with it. Please consider I run a Honor device (EMUI 8) with a custom font/theme active (the package includes the regular [Ubuntu font](https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip), v0.83) which I baked/updated myself.

1. With custom font active, the issue can be observed:
![IMG_20191016_192401](https://user-images.githubusercontent.com/12466054/66943633-dea3c900-f04b-11e9-8af1-17e95cdb2b3e.jpg)

2. Disabling the custom font, the issue clears up after a short updated:
![IMG_20191016_192420](https://user-images.githubusercontent.com/12466054/66943691-fd09c480-f04b-11e9-8b65-d536c71a612d.jpg)

3. Restoring the custom font makes the issue to reappear.

Do you have any clue on why the glyph from the `weather.ttf` is not gathered/displayed with a custom font on the device?

I can dig it further if you need and drive me.

Thanks and regards,

igor

**Comment by FridoDeluxe** [comment]
Thanks for the investigation, this looks like a perfect representation of a bug - seemingly weird behavior in the beginning, but later a logical reason was found. Hopefully easier to fix than this mysterious caching problem we had in mind ...

Seems like the icon is not displayed properly only when theres a glyph for the respective unicode available in the Ubuntu font. If it only appears on the widget and not in the app itself, the reason must be related to the way how the weather font is set in the widget.

I haven't looked at the code yet but I'll try do so after the upcoming weekend. But feel free to fix it before :-)

**Comment by igor-cali** [comment]
@FridoDeluxe do you know what's the related SW module?

**Comment by FridoDeluxe** [comment]
@igor-cali Probably this method: https://github.com/martykan/forecastie/blob/5c146df1ea4a1b7a66a3126e4542749649d8da0b/app/src/main/java/cz/martykan/forecastie/widgets/AbstractWidgetProvider.java#L60

But at a first glance the code for the icon inside the app looks similar: https://github.com/martykan/forecastie/blob/5c146df1ea4a1b7a66a3126e4542749649d8da0b/app/src/main/java/cz/martykan/forecastie/activities/MainActivity.java#L155

I have no experiences yet with custom fonts on Android and how they intercept the display of texts.

**Comment by igor-cali** [comment]
The custom [Ubuntu font](https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip) contains a glyph for `0xF002` for the 'cloudy day'. Indeed, this glyphs is represented as a 'fl'.
The font does not contain a glyph for` 0xF086` for the 'cloudy night.
This explain why the issue is during the day only.

What it is unclear to me is why the used `TypeFace` from the `weather.ttf` font is overridden in case the phone font includes the glyphs.

**Comment by FridoDeluxe** [comment]
> What it is unclear to me is why the used TypeFace from the weather.ttf font is overridden in case the phone font includes the glyphs.

It's hard to guess when we don't know how exactly EMUI 8 intercepts/changes fonts. Perhaps we can't do anything on our side. Maybe with applicable glyphs the custom font function of EMUI 8 overrides all font code in widgets: https://uk.community.huawei.com/software-40/font-changes-overrides-app-fonts-5221.

**Comment by igor-cali** [comment]
Thanks for pointing this out. Now that I think of it, I have seen wrong glyphs in other applications in my phone set (which do not really bother me since they are secondary apps to me and also proprietary). I will patch my font to make sure Forecastie is not affected anymore and then close this issue.

Thank you very much for your interest, engagement and support!

**Comment by robinpaulson** [comment]
@igor-cali Cheers for the update, glad you're on the way to getting this fixed. I'll leave it as a bug for now, maybe it's not just your use-case? We'll see.
