### ISSUE TITLE
error parsing JSON

### ISSUE THREAD

**Issue by utraz** [martykan/forecastie#369]
When entering the village "laguepie" I get the "Error parsing JSON" message.

Other nearby villages work fine.

**Comment by robinpaulson** [comment]
I did a search on the OWM website:
https://openweathermap.org/find?q=laguepie
It returned "not found"

I assume the location is too small for OWM to have in the db, whereas others are not. That said, we should give a better error message. #316 is relevant here.

**Comment by robinpaulson** [comment]
Thanks for the issue, I'll close this and add the info to 316, which is the master for all bad error messages.
