### ISSUE TITLE
Location?

### ISSUE THREAD

**Issue by ShadyGaDa** [martykan/forecastie#370]
Can't locate or input location ???

**Comment by robinpaulson** [comment]
Could you check if any existing issues cover this bug.

If not, could you put some more detail please.

**Comment by ShadyGaDa** [comment]
It's alright, started working thanks.

**Comment by astralchan** [comment]
Not sure if related, but figured I'd try commenting in this issue as it's closest to one I have.

Location seems to be failing to fetch, Trying to enable the setting "Update location in background" results in app not responding and having to force close it.

Tapping "Detect Location" simply displays "Getting your location" seemingly indefinitely (at least for 44 minutes before I stopped it). It is stuck on the default London, GB location.

The app has location access.

Details:
    phone: samsung galaxy s10+ (SM-G975F/DS)
    OS: LineageOS 19-20220921-NIGHTLY-beyond2lte (android 12)
    app version: 3.102_fdroid (f-droid)
    complete log: [here](https://gist.github.com/astralchan/10525c045bae4856d2181ce3f29cbcc5) - generated with logcat
