### ISSUE TITLE
Consider real sunrise and sunset to determine daytime

### ISSUE THREAD

**Issue by igor-cali** [martykan/forecastie#373]
https://github.com/martykan/forecastie/blob/5b225acdfdecebdd4a581363a0efe47e29dc22bb/app/src/main/java/cz/martykan/forecastie/utils/Formatting.java#L138

Use `getSunrise()` and `getSunset()` methods from `Weather` class.

**Comment by robinpaulson** [comment]
Yes, this has bugged me for a while. I used to live at a relatively high latitude, with huge swings of daylight from summer to winter, making this approximation not great. Given we know the times already, it shouldn't be so difficult.

**Comment by robinpaulson** [comment]
Are you interested in doing this @igor-cali ?

**Comment by igor-cali** [comment]
I could try, but not immediately. In the upcoming weeks I'll be busy updating my app.

**Comment by igor-cali** [comment]
https://github.com/igor-cali/forecastie/commit/0f9e50f0776ae3f5e779f4fd795d289c8790fe70

**Comment by igor-cali** [comment]
PR proposed.

**Comment by robinpaulson** [comment]
fixed with #378
