### ISSUE TITLE
Add a Korean translation to the app

### ISSUE THREAD

**Issue by byoung-min** [martykan/forecastie#376]
I am a student who needs to submit a contribution to the Open source project GitHub at university.
I found this project and tried using the app provided. It was a great app , but I would like to contact you about adding a feature. I want to add Korean function in Android app, so that Koreans can easily recognize it. 
Would you like to translate the Android app into Korean?
I can send examples of Korean translations for words used in the app.

**Comment by robinpaulson** [comment]
That would be most excellent. Are you comfortable using git to do the submissions, or would you rather do it here and then get us to copy-and-paste?

**Comment by byoung-min** [comment]
Thank you so much :)
We have sent pictures of your example in your mail. Please check and e-mail us if you need more.

**Comment by robinpaulson** [comment]
I'm afraid I don't understand, what do you mean?

**Comment by byoung-min** [comment]
We want to add a feature to the Korean version, so we sent you some example pictures. can you add Korean language function for us?

**Comment by robinpaulson** [comment]
I understand you want to translate the app into Korean, that is great, please do so.

I'm not sure what you mean by "example pictures".

I can't add anything until you send the translations. Do you need me to show you which words to translate?

**Comment by byoung-min** [comment]
I am trying to send a picture and translation words by email. where is your e-mail address? Or can you give me a e-mail address? :)

**Comment by robinpaulson** [comment]
I'd rather you put the words here, I don't want to give out my email address.

You can type the words in the issue, or upload pictures, or open a pull request.

**Comment by byoung-min** [comment]
okay!
![changed 1](https://user-images.githubusercontent.com/55642109/67673662-f1a88880-f9bd-11e9-9178-31104c020398.png)
Seoul,KR -> 서울, 대한민국
Wind -> 풍량   pressure-> 압력  humidity -> 습기  sunrise -> 일출  sunset -> 일몰
UV -> 자외선    LAST UPDATE: 마지막 업데이트 
TODAY -> 오늘   TOMORROW -> 내일  LATER -> 이후
Clear sky-> 날씨 맑음

![changed 2](https://user-images.githubusercontent.com/55642109/67673678-fff6a480-f9bd-11e9-9905-0a49ae3431e6.png)

Search for city -> 도시 검색
Seoul -> 서울
Cancel- -> 취소   ok-> 확인

![changed 3](https://user-images.githubusercontent.com/55642109/67673708-113fb100-f9be-11e9-8042-b86c997098ff.png)

Weather map -> 기상 지도 graphs -> 그래프  Detect Location -> 위치 설정
Settings -> 설정   About -> 정보

![changed 4](https://user-images.githubusercontent.com/55642109/67673726-1e5ca000-f9be-11e9-80e5-2ab2cd426c0b.png)

Getting your location… -> 위치 수집중….      Cancel-> 취소

![changed 5](https://user-images.githubusercontent.com/55642109/67673739-287e9e80-f9be-11e9-858e-bdb5a12f8bb9.png)

Settings -> 설정     units -> 단위       Temperature units -> 온도 단위 
Show temperature only as an integer -> 온도 단위를 정수로 표현
Length units -> 길이 단위   Speed units -> 풍속 단위  pressure units -> 기압 단위  date format -> 날짜 형식   custom date format -> 날짜 형식 포맷   
 provide the custom Simpledataformat string to be used  ->simple data format 문자열을 제공하십시오.
Display -> 화면   Theme->테마   Make widget transparent  ->  위젯을 투명하게 만들기
Wind direction format:  바람 방향 형식

![Uploading changed 7.png…]()

Display decimal zeroes -> 십진수 0을 표시
Differentiate days with color  -> 날짜들을 색으로 구별
Data: 데이터
Background refresh interval -> 백그라운드 새로고침 간격
Location : 위치
Update location in background: 백그라운드에서 위치 업데이트

![changed 6](https://user-images.githubusercontent.com/55642109/67673823-5532b600-f9be-11e9-91c0-012643b4de37.png)
![changed 8](https://user-images.githubusercontent.com/55642109/67673831-5a900080-f9be-11e9-80c2-a086e77b9277.png)

Graphs -> 그래프들      Temperature -> 기온  rain-> 강수량    pressure -> 기압  wind speed -> 풍속 

![changed 9](https://user-images.githubusercontent.com/55642109/67673873-6ed3fd80-f9be-11e9-939a-aa3da6a6f11e.png)

Location Settings -> 위치 설정
Location is not enabled. Do you wish to go to the settings menu? ->
위치가 사용설정 되지 않았습니다. 설정 메뉴로 가시겠습니까?
Cancel -> 취소    settings-> 설정

**Comment by robinpaulson** [comment]
OK, thanks. This might take a while to do.

If anyone with coding experience wants to lend a hand, even one or two words, that would be great.

**Comment by byoung-min** [comment]
Thank you so much! i'll wait for good news :)

**Comment by robinpaulson** [comment]
OK, i've done all those, it was easier than i thought

**Comment by robinpaulson** [comment]
Some strings you missed, talking about ultra violet (UV) levels:
No Info
Low
Moderate
High
Very High
Extreme

**Comment by robinpaulson** [comment]
Also, talking about wind speed units:
Meters per second
Kilometers per hour
Miles per hour
Beaufort wind scale
Knots

**Comment by robinpaulson** [comment]
And, for temperature units:
Celsius
Fahrenheit
Kelvin

**Comment by robinpaulson** [comment]
Beaufort scale wind strengths (https://en.wikipedia.org/wiki/Beaufort_scale):
Calm
Light air
Light breeze
Gentle breeze
Moderate breeze
Fresh breeze
Strong breeze
High wind
Gale
Strong gale
Storm
Violent storm
Hurricane

**Comment by byoung-min** [comment]
sorry to late. if you want more information. ask me again.
No info	-> 정보가 없습니다.
Low -> 낮음
Moderate -> 보통
High -> 높음
Very high -> 매우 높음
Extreame -> 극도로 높음

meters per second  ->  초당 미터
kilometers per hour  -> 시간당 킬로미터
Miles per hour -> 시간당 마일
beaufort wind scale   ->  보 퍼트 바람 규모
knots   ->매듭


celsius -> 섭씨
fahrenheit -> 화씨
kelvin  -> 켈빈

calm -> 잔잔
Light air -> 가벼운 공기
light breeze -> 가벼운 바람
gentle breeze ->산들 바람
moderate breeze ->보통 바람
fresh breeze -> 신선한 바람
strong breeze -> 강한 바람
high wind -> 높은 바람
gale -> 강풍
strong gale -> 강한 강풍
storm->폭풍
violent storm-> 강력한 폭풍
hurricane -> 태풍

**Comment by robinpaulson** [comment]
Great, here's the next chunk, directions of the compass:
N
NNE
NE
ENE
E
ESE
SE
SSE
S
SSW
SW
WSW
W
WNW
NNW

**Comment by robinpaulson** [comment]
Error message:
Error parsing JSON
There is a problem with your internet connection
Connection not available
Specified city is not found

**Comment by robinpaulson** [comment]
Various other words:
Downloading your data
DATE FORMAT ERROR
None
API key
Custom API key for OpenWeatherMap queries

**Comment by robinpaulson** [comment]
Rain amount:
Millimetres
Inches

**Comment by robinpaulson** [comment]
Air pressure units:
hPa
kPa
mmHg
inHg

**Comment by robinpaulson** [comment]
Wind direction format:
No indication
Arrows
Abbreviations

**Comment by robinpaulson** [comment]
App theme names:
Fresh
Classic
Fresh Dark
Classic Dark
Fresh Black
Classic Black

**Comment by byoung-min** [comment]
Korea's direction consists of eight directions. So we divided in eight directions

directions of the compass:  나침반의 방향
N -> 북
NNE, NE, ENE -> 북동
E -> 동
ESE, SE, SSE -> 남동
S -> 남
SSW, SW, WSW = 남서
W = 서
WNW, NNW, NW = 북서

Error message: 	-> 오류 메세지
Error parsing JSON	->JSON 구문 분석 오류
There is a problem with your internet connection -> 인터넷 연결에 문제가 있습니다.
Connection not available ->접속불가
Specified city is not found -> 지정된 도시를 찾을 수 없습니다.


Rain amount:  -> 강수량:
Millimeters -> 밀리미터
inches -> 인치

Various other words: -> 다양한 다른 단어들:
Downloading your data -> 다운로드중
DATA FORMAT ERROR -> 데이터 형식 오류
None -> 존재하지않음
API key -> API 키
Custom API key for OpenWeatherMap queries -> 날씨지도 쿼리를 위한 사용자 API 키


Air pressure unit: 기압 단위
hpa -> 헥토파스칼
kpa -> 킬로파스칼
mmHg -> 수은주 밀리미터
inHg -> 수은주 인치

wind direction format: 바람 방향 형식
no indication -> 표시 없음
Arrows -> 화살표
abbreviations -> 축약표시

App theme names -> 앱 테마
Fresh -> 밝은
classic -> 클래식한
Fresh dark -> 밝은 어두운
classic dark -> 클래식하게 어두운
Fresh black -> 밝은 검정
Claccis balck -> 클래식한 검정

**Comment by robinpaulson** [comment]
> Korea's direction consists of eight directions. So we divided in eight directions

OK, we'll have to think about that a bit, that affects the code as well as the translation.

**Comment by robinpaulson** [comment]
Given that
N -> 북
and E -> 동

what does it mean if we write
북동북
?

Would most Korean speakers understand that?

**Comment by robinpaulson** [comment]
The last word I can find, other than the compass directions:
Refresh

**Comment by byoung-min** [comment]
if you think about bit, it is okay to write in 북북동
NNE -> 북북동
ENE ->동북동
ESE ->동남동
SSE ->남남동
SSW ->남남서
WSW ->서남서
WNW ->서북서
NNW ->북북서
 
Can you tell me where the refresh word is used? I need to know the context to be able to translate it correctly.

**Comment by robinpaulson** [comment]
Refresh the weather data

Thanks for the compass directions.

I will make a new release tomorrow, then we can see how the new translation looks.

**Comment by byoung-min** [comment]
Refresh the weather data -> 날씨 정보 새로고침
Refresh-> 새로고침

thanks very much :) , i'm really looking forward tomorrow.

**Comment by robinpaulson** [comment]
Hey, thanks to you, I'm really pleased we can offer another language for the app.

It will take a couple of days after that for the update to land on your phone. I'll estimate Saturday, maybe Sunday.

**Comment by robinpaulson** [comment]
I missed a phrase, which refers to too many people trying to download the data at once:
Too many requests. Please try again.

**Comment by byoung-min** [comment]
Too may requests. Please try again -> 요청이 너무 많습니다. 다시 시도하십시오.
is it right?

**Comment by robinpaulson** [comment]
Looks good. I'll release an update in a few days, we have likely missed a few translations. I'll add this in when I do that.

**Comment by robinpaulson** [comment]
Some more I missed, one of them is fairly long and complicated:

UV Index
Wind Speed
Loading

A lightweight, Free Software weather app, released under the GPL3 licence.\n\nDeveloped by <a href='mailto:t.martykan@gmail.com'>Tomas Martykan</a> and others\n\nCode is available at <a href='https://github.com/martykan/forecastie'>Forecastie</a>\n\nData provided by <a href='https://openweathermap.org/'>OpenWeatherMap</a>, under the <a href='http://creativecommons.org/licenses/by-sa/2.0/'>Creative Commons license</a>\n\nIcons are <a href='https://erikflowers.github.io/weather-icons/'>Weather Icons</a>, by <a href='http://www.twitter.com/artill'>Lukas Bischoff</a> and <a href='http://www.twitter.com/Erik_UX'>Erik Flowers</a>, under the <a href='http://scripts.sil.org/OFL'>SIL OFL 1.1</a> licence.

**Comment by byoung-min** [comment]
Thank you for your hard work and meticulousness.

UV index -> 자외선 지수
Wind speed -> 풍속
Loading -> 로딩

A lightweight, Free Software weather app, released under the GPL3 licence.Developed by Tomas Martykan and othersCode is available at ForecastieData provided by OpenWeatherMap, under the Creative Commons licenseIcons are Weather Icons, by Lukas Bischoff and Erik Flowers, under the SIL OFL 1.1 licence.  
->
GPL3 라이센스에 따라 출시 된 간단한 자유 소프트웨어 날씨 앱입니다.
Thomas martykan 등이 개발한 코드는 OpenWeatherMap에서 제공하는 Forecastie 데이터에서 사용가능합니다. 아이콘은 SIL OFL 1.1 라이센스에 따라 Lukas Bischoff 및 Erik Flowers의 날씨 아이콘들입니다.

**Comment by robinpaulson** [comment]
The long piece of test could be difficult, in the code it contains a lot of hyperlinks, I would like to keep those working as they currently do. It might take a few goes to get it right. I'll post something shortly.

**Comment by robinpaulson** [comment]
The best way might be to get you to translate the source code. Do you understand HTML?

If so, could you take a look at this line (number 184):
https://github.com/martykan/forecastie/blob/449da9b6168765a8a37aa8acb5f71bcaef3f3208/app/src/main/res/values/strings.xml#L184
and translate the text? It's really important you translate the information without altering the code.

Does that make sense?

**Comment by robinpaulson** [comment]
Actually, hold that for a moment, it may not be necessary. This is quite difficult, I'm trying to think through the best way to do it.

**Comment by robinpaulson** [comment]
OK, let's try this, broken into smaller parts:
A lightweight, Free Software weather app, released under the GPL3 licence.

Developed by Tomas Martykan and others.

Code is available at Forecastie.

Data provided by OpenWeatherMap, under the Creative Commons CC-BY-SA license.

Icons are Weather Icons, by Lukas Bischoff and Erik Flowers, under the SIL OFL 1.1 licence.

**Comment by robinpaulson** [comment]
I asked again, because I erroneously posted it as one long piece, in the app it is broken up into several pieces. I'm not sure where those breaks should be.

**Comment by byoung-min** [comment]
A lightweight, Free Software weather app, released under the GPL3 licence.
-> GPL3 라이센스에 따라 출시 된 간단한 자유 소프트웨어 날씨 앱입니다.
Developed by Tomas Martykan and others.
->Tomas Martykan 등 다른인원들로부터 개발되었습니다.
Code is available at Forecastie.
->코드는 Forecastie에서 이용가능합니다.
Data provided by OpenWeatherMap, under the Creative Commons CC-BY-SA license.
->Creative Commons CC-BY-SA 라이센스에 따라 OpenWeatherMap에서 제공한 데이터입니다.
Icons are Weather Icons, by Lukas Bischoff and Erik Flowers, under the SIL OFL 1.1 licence.
->아이콘은 SIL OFL 1.1 라이센스에 따라 Lukas Bischoff 및 Erik Flowers의 날씨 아이콘입니다.

**Comment by robinpaulson** [comment]
Excellent!

**Comment by robinpaulson** [comment]
OK, that's done. There will be a new release in a day or two, then another in 7-10 days when we've figured out all the bugs.

**Comment by byoung-min** [comment]
We're doing school assignments and doing something different than the professor wants. We should have submitted this translation contribution as "Pull requests" rather than "issue". Can you merge if we upload the contents of this "issue" to "pull requests"? Or can you tell me how to solve this. plz

**Comment by robinpaulson** [comment]
Ah, sorry to hear that. I've already merged all the suggestions you made. We have almost certainly missed some though, perhaps we do those the correct way?

**Comment by byoung-min** [comment]
Do you mean that we may have missed something of our translations? 
if then Does that mean we can MERGE?

**Comment by robinpaulson** [comment]
I'm not sure, we'll find out next week, when you try the new release. If there are things missing, then you can open a pull request with the missing translated strings.

**Comment by byoung-min** [comment]
okay. I'll wait until next week. thank you

**Comment by robinpaulson** [comment]
OK, the new release is out now, on F-droid.

**Comment by byoung-min** [comment]
Thank you. Has confirmed. We'll find the error later in pull requests.

**Comment by robinpaulson** [comment]
@igor-cali found the first mistake, in the formatting of the translation file. It will be corrected once #378 is ready to be accepted.

**Comment by byoung-min** [comment]
it is okay to modify @igor-cali 's revision.
we will requests another error in "Pull requests" maybe tomorrow.

**Comment by robinpaulson** [comment]
We've accepted the corrections made by igor-cali, do you think you'll have anything soon?

**Comment by Ryeoly** [comment]
I am a member of the same team as byoung-min who raised the issue for translate.ko.
I posted a pull request for additional translations. Please confirm. We will also be fixing any awkward translations as soon as possible.

**Comment by robinpaulson** [comment]
@Ryeoly @byoung-min Could you review my comments on the recent PR (#379) made by @Ryeoly ? I am going to make a new release and would like to include your changes if possible.

**Comment by robinpaulson** [comment]
I'm going to close this, as the initial issue has been solved. Any additional updates can be addressed via new issues and pull requests.
