### ISSUE TITLE
Forecastie Widget Disappears On A Reboot!

### ISSUE THREAD

**Issue by 0pLuS0** [martykan/forecastie#380]
Hello!

I'm running a OnePlus5T running LineageOS microG version - lineage-16.0-20191029 which you can find/see here at their URL;

https://download.lineage.microg.org/dumpling/

I have the latest Forecastie 1.10.8.

I'm also using the latest PIE firmware from OnePlus 9.0.9, and the problem started to happen after updating to this version.

I placed the Widget and made it transparent on the Home screen, and if I reboot my phone, the widget disappears.

I've never had this problem till now, it seems like the latest Android updates might have caused this?

Hmm

I've attached a logcat after I rebooted the phone, when the widget disappeared, so I hope it shows the problem and you can fix this.

[logcat.txt](https://github.com/martykan/forecastie/files/3833055/logcat.txt)

THANKS

```P.S. After making this Issue Report, I noticed that now Forecastie is placed on a second Home screen always to the right after I've rebooted the phone, so then I scroll my Home screen to the right, I see Forecastie and I drag it back to the left, but this has not always happened with the latest LineageOS microG version. I'm using the version before the latest, and with the latest version of LineageOS microG, Forecastie was gone when I rebooted.```

**Comment by robinpaulson** [comment]
I had a look through the logcat, it contained one benign reference to forecastie. At first glance, this looks entirely like a problem with the OS.

When you upgraded Android, did you wipe the phone and reinstall forecastie, or keep the previous installation (I don't even know if that's possible to be honest).

**Comment by robinpaulson** [comment]
Have you had problems with other software? Have you asked on the LineageOS forum? That might provide some more useful info.

**Comment by 0pLuS0** [comment]
I wanted to report this, in case the latest Android PIE firmware could be the issue and that forecastie needed an update to better support it, is why I made this report.

All I can say is before the latest PIE firmware update I didn't have this problem...

**Comment by robinpaulson** [comment]
@0pLuS0 We've made a few improvements to the widgets over the last few months. I wonder if we have inadvertently fixed the problem you were having?

**Comment by 0pLuS0** [comment]
I don't see it now, so either you fixed it, or a new ROM update did...

Either way, all good now.

THANKS

**Comment by robinpaulson** [comment]
Excellent, closing.
