### ISSUE TITLE
Add code style guidelines to Contribution.md

### ISSUE THREAD

**Issue by FridoDeluxe** [martykan/forecastie#381]
Code style was a topic briefly touched in #378. This is a proposal how to include something about code style guidelines into the `CONTRIBUTING.md` file. I did not include concrete examples (about naming, brace style, ...) because this is quite cumbersome and probably deters potential contributors. Hopefully the general idea of consistent and self-explanatory code and the two links are sufficient.

> **Contributions**
> 
> We welcome any and all contributions to Forecastie. Please add suggestions, bugs or requests for new features to the [Issues](https://github.com/martykan/forecastie/issues) page. The [Issues](https://github.com/martykan/forecastie/issues) page is also the best place to ask questions about the code, the structure of the software, release schedule, etc.
> 
> **Pull requests**
> 
> We also accept pull requests; anything you submit will be reviewed and discussed, and merged if appropriate. Please take the time to read relevant [Issues](https://github.com/martykan/forecastie/issues), or open one yourself on the topic.
> 
> **Code guidelines**
> 
> Although we will discuss every pull request, we'd like you to prepare your contribution as good as possible. Keep your code easy to understand and maintainable as well as consistent with the existing code. Add helpful comments or JavaDoc when necessary.
> 
> We don't have an official code style but you can find reasonable guidelines in the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) and the [Android Contributors Code Style](https://source.android.com/setup/contribute/code-style).

If this text is okay for you I can prepare a PR.

In case Transifex is reactivated I'll add a paragraph especially for translations.

**Comment by robinpaulson** [comment]
That is excellent @FridoDeluxe , really clear, straightforward and welcoming. One small change, more grammatical than substance: could you replace "good" with "well" ? It doesn't quite read smoothly at the moment. If you do that and make a PR, I'll accept it.

**Comment by FridoDeluxe** [comment]
Thanks for correcting my imperfect English. See #382.

**Comment by robinpaulson** [comment]
Excellent, done.
