### ISSUE TITLE
Continuous Integration builds

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#403]
Yesterday I set up CI (Continuous Integration) builds for Forecastie. These will allow anyone looking at the repo to see whether the latest master branch of the app is building correctly.

Bad news: it isn't.

I already fixed one bug in the Swedish translation, leaving this:
https://github.com/martykan/forecastie/runs/325268528#step:4:131

See here for more info. on CI:
https://en.wikipedia.org/wiki/Continuous_Integration

**Comment by robinpaulson** [comment]
To be clear: we already have CI builds using circleci, this is a second service, built into github.

**Comment by FridoDeluxe** [comment]
The failing CI build should be fixed by #410, as you can see in https://github.com/FridoDeluxe/forecastie/runs/336361141.

**Comment by robinpaulson** [comment]
Excellent, cheers
