### ISSUE TITLE
upgrade bundled jquery files

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#406]
It is almost certainly faster than the version we currently use, but is the API the same?

**Comment by robinpaulson** [comment]
The API may be different enough to cause problems, the jquery site offers info on upgrading:
https://jquery.com/upgrade-guide/3.0/
https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

**Comment by FridoDeluxe** [comment]
Hmm, where is jQuery actually used? The library is linked in `map.html` but there is no JavaScript code using jQuery. I just removed the jQuery reference and the maps still work - looks to me as we could remove jQuery completely without problems?

**Comment by robinpaulson** [comment]
Well, that's interesting. I don't know much about jquery at all, I assumed it was used in the map for the slider.... but of course there isn't a slider. Maybe we should have one for zooming in, etc. Anywho, I'll close for now and delete jquery and references.
