### ISSUE TITLE
Tidy/possibly remove some themes

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#408]
There are currently 6 themes; do we need them all?

As pointed out by @FridoDeluxe in #331 , this number of themes makes a certain amount of sense.

If we do keep all 6, we maybe need to tidy how the code for them is distributed through the repository, for neatness and readability.

**Comment by igor-cali** [comment]
In the commit above I changed the parent theme for `Black` variants. New parent is the respective `Dark` theme.
In fact, the theme pairs share all of the color values except `colorBackGround` and `colorTintedBackground`.
I also removed unused colors.

@robinpaulson If this is fine for you, I can remove the commented lines and raise a PR.

**Comment by robinpaulson** [comment]
@igor-cali I'm not 100% sure here, from what I gather the first part of this simplifies the code for defining the styles, correct?

As for the second part, that sounds positive, but I can't see which colours have been removed.

Regardless, yes please propose a PR.

**Comment by igor-cali** [comment]
`Black` themes are now derivations/children of `Dark` themes, instead of being siblings.
The colours commented out in `colours.xml` are being removed.

**Comment by robinpaulson** [comment]
Cheers, understood now. Closing.
