### ISSUE TITLE
Support weather description in Latvian and consolidate OWM language support

### ISSUE THREAD

**Issue by FridoDeluxe** [martykan/forecastie#424]
OWM uses language codes to support the weather descriptions in different languages. Sometimes these codes differ from Android's system language code (currently Czech and Korean are converted by Forecastie). But it also applies to Latvian which is not yet corrected by Forecastie (Android: `lv` vs. OWM: `la`).

Talking about language codes for OWM: Converting the languages is implemented in two places (`GenericRequestTask`, `AlarmReceiver`), it should be consolidated into one implementation to simplify future adjustments.

**Comment by FridoDeluxe** [comment]
For documentation purposes and to provide information for the translations (#364):

Language | Android / ISO 639-1 ([source](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)) | OWM lang value ([source](https://openweathermap.org/current#multi))
-- | -- | --
Arikaans | af | af
Arabic | ar | ar
Azerbaijani | az | az
Basque | eu | eu
Belarussian* | be |  
Bulgarian | bg | bg
Catalan | ca | ca
Chinese Simplified | zh_CN | zh, zh_cn
Chinese Traditional | zh_TW | zh_tw
Croatian | hr | hr
Czech | _cs_ | _cz_
Danish | da | da
Dutch | nl | nl
German | de | de
Greek | el | el
English | en | en
Farsi/Persian | fa | fa
Finnish | fi | fi
French | fr | fr
Galician | gl | gl
Hebrew | he | he
Hindi | hi | hi
Hungarian | hu | hu
Indonesian | id | id
Italian | it | it
Japanese | ja | ja
Korean | _ko_ | _kr_
Latvian | _lv_ | _la_
Lithuanian | lt | lt
Macedonian | mk | mk
Nepali* | ne |  
Norwegian | no | no
Polish | pl | pl
Portuguese | pt | pt
Portuguese | pt_BR | pt_br
Romanian | ro | ro
Russian | ru | ru
Swedish | sv | se, sv
Slovak | sk | sk
Slovenian | sl | sl
Serbian | sr | sr
Spanish | es | sp, es
Thai | th | th
Turkish | tr | tr
Ukrainian | uk | ua, uk
Vietnamese | vi | vi
Zulu | zu | zu

*Belarussian and Nepali translations are available in Forecastie, but these languages are not supported by OWM. On the other hand OWM supports many languages that have no Forecastie translation.

Actually OWM supports more langauge codes than noted in their documentation (for example `sv` for Swedish). OWM is case-insensitive regarding the language code.

**Comment by robinpaulson** [comment]
Wow, this is a big help, it ties into the questions I asked in #364 . I will dig deeper later this week, see what we can do.
