### ISSUE TITLE
GraphActivity crashing

### ISSUE THREAD

**Issue by Nemo-512** [martykan/forecastie#429]
Here is adb logcat output
> 01-21 14:42:24.388 E AndroidRuntime: FATAL EXCEPTION: main
> 01-21 14:42:24.388 E AndroidRuntime: Process: cz.martykan.forecastie, PID: 16845
> 01-21 14:42:24.388 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.martykan.forecastie/cz.martykan.forecastie.activities.GraphActivity}: java.lang.IllegalArgumentException: Number of rows/columns can't be lesser than 1.
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:193)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6718)
> 01-21 14:42:24.388 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
> 01-21 14:42:24.388 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 01-21 14:42:24.388 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 01-21 14:42:24.388 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Number of rows/columns can't be lesser than 1.
> 01-21 14:42:24.388 E AndroidRuntime:    at com.db.chart.view.ChartView.setGrid(ChartView.java:1423)
> 01-21 14:42:24.388 E AndroidRuntime:    at cz.martykan.forecastie.activities.GraphActivity.humidityGraph(GraphActivity.java:314)
> 01-21 14:42:24.388 E AndroidRuntime:    at cz.martykan.forecastie.activities.GraphActivity.onCreate(GraphActivity.java:107)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:7144)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:7135)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
> 01-21 14:42:24.388 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
> 01-21 14:42:24.388 E AndroidRuntime:    ... 11 more

**Comment by robinpaulson** [comment]
Which version are you using?

**Comment by FridoDeluxe** [comment]
Thanks for the bug report. This line is a good hint:

> java.lang.IllegalArgumentException: Number of rows/columns can't be lesser than 1.

Indeed the GraphActivity crashes for some special edge cases where the Y-axis range and grid lines couldn't be calculated correctly (e.g., exactly the same temperature or pressure for five days). It should be fixed now with PR #430.

Maybe the Y-axis and not the precipitation value was also the reason for the problem in #422 ...
