### ISSUE TITLE
Please add MET.no Yr weather data too

### ISSUE THREAD

**Issue by pinportal** [martykan/forecastie#432]
MET.no Yr is a Free API from Norwegian Meteorological Institute.
It is completely free and in many countries your data is much more reliable than OpenWeatherMap
I am not suggesting replacing one with the other. I am suggesting adding it as a second option.

https://www.met.no/en/free-meteorological-data

**Comment by robinpaulson** [comment]
Hi, yes we have had requests before for other data sources. It would require a big effort of work though, so who knows when it may happen. Implementing #428 will certainly help, but that will take time itself. Unless you are prepared to assist with code?

**Comment by robinpaulson** [comment]
Closing as it's a duplicate of #126
