### ISSUE TITLE
Show numerical Beaufort scale in app

### ISSUE THREAD

**Issue by sotpapathe** [martykan/forecastie#439]
When using the Beaufort scale it is shown as text in the main app (e.g. Strong breeze) and as a number in the widget (e.g. 6 bft). It would be useful if we could show the number in the main app as well as it's more intuitive than the corresponding English names for many people.

This could be implemented as an extra speed unit so there would be two for the Beaufort scale, one numerical and one textual. Another alternative would be to always show the numerical value along with the text.

**Comment by robinpaulson** [comment]
I completely agree with all of this, good suggestion. I think the best method is to have the two pieces of information alongside each other.

**Comment by robinpaulson** [comment]
I've made a quick change which should cover this. I'll close this for now, let me know if it's not suitable. The next release will be within a few days.
