### ISSUE TITLE
Problem with the Forecastie Classic 4x2 widget

### ISSUE THREAD

**Issue by akym-tsubby** [martykan/forecastie#440]
There've been some bugs pertaining to the classic widget as of 1.13.2:

- the widget doesn't respect the Theme colour and constantly stays blue regards of whatever theme selected

- whenever Date Format is set to custom, the widget merely displays as a coloured rectangle with no information whatsoever

![Screenshot_20200212-170858_Lawnchair](https://user-images.githubusercontent.com/51875072/74321836-ee46da80-4dbd-11ea-8564-3756fc1dbd9d.jpg)

**Comment by robinpaulson** [comment]
Good to hear about the first bug, that's not been reported before. As for the second, that sounds closely related to a couple of other recent problems: #437 #426

**Comment by igor-cali** [comment]
Reworked for first issue.

**Comment by robinpaulson** [comment]
A new release will hit the archives in a few days, including igor's fix.

**Comment by skyerjoe** [comment]
Same here but the tablet was shutdown ungracefully then the blue bar appears.

**Comment by robinpaulson** [comment]
@skyerjoe That's no good, it's working on mine. Could you try selecting a different theme to your preferred, then reselecting your preference?

If that doesn't work, could you uninstall, then reinstall? I'm not sure what you mean by "Reinstall doesn't work"

**Comment by skyerjoe** [comment]
@robinpaulson 
An double install and Uninstall with reboot had helped
Thnx for guidance

**Comment by skyerjoe** [comment]
Update after an update from my device the issue occurs again

**Comment by robinpaulson** [comment]
H folks, are you still getting problems with this, or have recent updates fixed it? @akym-tsubby @skyerjoe

**Comment by skyerjoe** [comment]
@robinpaulson 
 I'm not getting updates for my tablet so often so I have to wait and see if it's still an issue.

Best regards

**Comment by skyerjoe** [comment]
Update:
One some restarts the problem is solved,  the next one can be that  it causes the issue newly. 
so 
I'm not sure where the error lies. 
May it's an problem from Android 8

Best regards

**Comment by robinpaulson** [comment]
@skyerjoe Which version of Forecastie are you using now?

**Comment by skyerjoe** [comment]
@robinpaulson 
1.17

Update: after an os Upgrade the Widget doesnt appears so May its solved but i have to verify thus with the next one 

Best regards

**Comment by igor-cali** [comment]
> @robinpaulson
> 1.17
> 
> Update: after an os Upgrade the Widget hasnt appear anymore so May its solved but i have to verify thus with the next one
> 
> Best regards

@skyerjoe what device and OS you are experiencing this, now?

**Comment by skyerjoe** [comment]
Mediapad t5 with Android 8
And
Xiaomi mi9t pro with  MIUI 12.03 based on Android 10 QKQ 1.190825.002

**Comment by skyerjoe** [comment]
Update:

After some updates,  I realized that the problem still exist but there is an workaround.
Just reboot one more after update and the blue background is gone. 

So I think it can be closed 

Best regards

**Comment by robinpaulson** [comment]
OK, thanks for the info skyerjoe, I'll close. If it happens again, please leave a note or create a new issue and we'll revisit.
