### ISSUE TITLE
Push Catalan translation

### ISSUE THREAD

**Issue by adriaaah** [martykan/forecastie#442]
Hello,
I'd like to request to push the Catalan translation because it's completed since some months: https://www.transifex.com/forecastie/forecastie/language/ca/
Since there is no coordinator, in case it's a requirement I'd step into.

**Comment by robinpaulson** [comment]
Ah, thanks for pointing that out. I'm the coordinator for Forecastie, Tomas is taking a break in the meantime. I had lost track of the translations page, a few of us talked about this in #364 but we didn't make any concrete decisions about what to do. I have two questions:
1. the link you posted appears to be dead, could you check it?
2. how do we get info from transifex to github?
Cheers

**Comment by adriaaah** [comment]
Hello @robinpaulson ,
thanks for replying.

Regarding the first question, I think you're right as this link only works as long as you're logged in Transifex.
Regarding the 2nd question, I saw you already pushed it to #364 , therefore thank you! I have no idea how to do it because never did that before, but it seems you managed to find it out.

Since it seems several translations are managed on #364, I think we can close this one.

Once again, thank you so much.

**Comment by robinpaulson** [comment]
I'd like to keep #364 open for now, there are some bigger issues which need fixing. I'm glad you're happy with the state of the Catalan translation.

**Comment by robinpaulson** [comment]
Do we need to keep this issue open? I see you closed and then reopened it.

**Comment by adriaaah** [comment]
Hello,
I closed it by accident and edited my previous comment accordingly, sorry for the confusion.
However, feel free to close it. I'm find to follow #364

**Comment by robinpaulson** [comment]
That's fine, no biggie

**Comment by robinpaulson** [comment]
Thinking further ahead, @adriaaah are you able/would you be willing to coordinate the updating of translation, as you suggest in your first comment? I don't know anything about Transifex, but it appears at a glance to be a decent option.

**Comment by adriaaah** [comment]
Hello,
I have no experience and can't promise to do it in a timely manner but I can give it a try, yes.
I don't know anything about Transifex either, but (and it it is an assumption) the options I linked in https://github.com/martykan/forecastie/issues/442#issuecomment-599692688  require admin rights that if no one else has, we're doomed.
If that was the case, we may start over on f.e. https://hosted.weblate.org
