### ISSUE TITLE
Selected tab has the wrong color in the map view

### ISSUE THREAD

**Issue by sotpapathe** [martykan/forecastie#453]
Although commit 34ff6a74a767f20071ee88e5803c0df0554f6fcb fixed the issues with the map (thanks @igor-cali !), a small regression was introduced. The icon of the selected tab now has the same color as the background. At first I though it was missing completely but by tapping the already selected tab a highlight appears and the blue icon is momentarily visible. I guess it's as simple as changing
```
android:background="@color/colorPrimary"
```
in `app/src/main/res/layout/activity_map.xml`, but I'm not that familiar with Java and Android development.

![forecastie_map_rain](https://user-images.githubusercontent.com/16228680/78073194-165bbe80-73a9-11ea-99c1-cbea71cb5144.png)

**Comment by igor-cali** [comment]
Can you confirm the Fresh theme is active?
It looks OK, for instance, with Classic Black on my device.

**Comment by sotpapathe** [comment]
- In Fresh, Fresh Black and Fresh Dark the selected tab is the same color as the background.
- In Classic the selected tab has a shade of gray the provides quite low contrast with the background.
- In Classic Black and Classic Dark the icon is visible with better contrast than Classic.

**Comment by sotpapathe** [comment]
The tab bar in the map view is always the same shade of blue, no matter the theme. It looks like this shade of blue is also the primary color for the Fresh themes. What if the tab background was always the primary color of the theme and the focused/not focused tabs the bright/dim white color of the theme? There would be no contrast issues this way.

**Comment by robinpaulson** [comment]
@sotpapathe That sounds good, are you willing to code it up?

**Comment by sotpapathe** [comment]
I am willing but not capable yet :smile: . I might look into Android development during the weekend but no promises yet.

**Comment by robinpaulson** [comment]
Great, I might take a look at it then, I'm guessing it's a simple theme change as you pointed out.

**Comment by igor-cali** [comment]
Fixed with Fresh colors. Selected theme colors does not still work.
