### ISSUE TITLE
Add temporary hint to "Graphs" button

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#456]
How many of you are aware that tapping on the weather icon on the "main" screen will show the graphs? Maybe most, but not all who come here and certainly not all users with it installed. I think it would be helpful to display a hint there, only until the first time it's used, so a new user is aware it exists. After they use it once, it disappears and is not shown again.

"Tap for Graphs"

**Comment by lmaths** [comment]
Hi, can I work on it?

**Comment by robinpaulson** [comment]
We've added the feature, but it's not working correctly; it doesn't disappear after the first use, only after the app is restarted.

**Comment by lmaths** [comment]
@robinpaulson The first run is the time that the application remains open, It is necessary that the activity is finished or restarted for this.

**Comment by lmaths** [comment]
The solution, I will change the logic for when the user clicks the button, it means that he has already seen the message

**Comment by lmaths** [comment]
What do you think?
As long as the user does not press the graphics button, we display the message, after he clicks the message disappears

**Comment by TheOtherDoctor** [comment]
As a (possibly simpler?) alternative, maybe consider having the user close (via some "(x)" icon) the message explicitly? Just an idea...
I would have put this away as old-fashioned, until I found this very nice in FairEmail [https://github.com/M66B/FairEmail](url), which brings quite a number of function suggestions to the user's focus this way. It is then up to the user to decide for each to remove or have it stay for some time - which I like when for some action I anticipate I might forget it again... ;-)
(Unfortunately, the design of the hints is not covered in any of the screenshots on the github page.)

In general (maybe yet overdone as long as there is only one such hint) it also might be good to have a reset item in the config to reactivate any such info boxes, acting like "mark as unread" - unless there is a built-in doc which mentions this anyway. ;-)

**Comment by robinpaulson** [comment]
> As a (possibly simpler?) alternative, maybe consider having the user close (via some "(x)" icon) the message explicitly? Just an idea...
> I would have put this away as old-fashioned, until I found this very nice in FairEmail [https://github.com/M66B/FairEmail](url), which brings quite a number of function suggestions to the user's focus this way. It is then up to the user to decide for each to remove or have it stay for some time - which I like when for some action I anticipate I might forget it again... ;-)
> (Unfortunately, the design of the hints is not covered in any of the screenshots on the github page.)
> 
> In general (maybe yet overdone as long as there is only one such hint) it also might be good to have a reset item in the config to reactivate any such info boxes, acting like "mark as unread" - unless there is a built-in doc which mentions this anyway. ;-)

they sound like good ideas, but i'm not willing to add the complexity to do this, it is a minor function after all.

**Comment by robinpaulson** [comment]
@lmaths 

Have you been able to look further into this?

**Comment by lmaths** [comment]
Hi @robinpaulson i'm back, sorry, i had some problems, i will provide this

**Comment by robinpaulson** [comment]
I'm going to close this, I don't think there's any major issue in a user seeing it multiple times. It disappearing when the app is restarted is fine.
