### ISSUE TITLE
Trailing space when searching by zip code causes 'error parsing JSON.' message

### ISSUE THREAD

**Issue by capslockpirate** [martykan/forecastie#464]
When searching for a location by a numerical value (like a zip code), trailing spaces are not removed which causes an error when fetching locations.

### Steps to reproduce:

1. Open forecastie
2. Tap search
3. Type in any zip code and add any amount of trailing space after the zip code
4. Tap OK
5. Observe the error message at the bottom of the screen.
6. Repeat the process without any trailing space and observe how the zip code does return correct results.

### Why this is an issue

Normally this wouldn't be a problem, why would a user add an extra space after their zip code?
A lot of mobile keyboards add a space after inserting an auto-completed string. Most likely users of forecastie are entering a zip code that they have typed in before and may be in their keyboards autocomplete. 

I'm happy to put in a PR, I'm not the most familiar with java, but I think the change would be the addition of a `.trim()` [on this line](https://github.com/martykan/forecastie/blob/cce5f8e03438f440c83462e97e33d3c513d10c4c/app/src/main/java/cz/martykan/forecastie/activities/MainActivity.java#L309)

**Comment by robinpaulson** [comment]
Good analysis and reasoning, this is entirely correct. Your suggestion sounds right, if you're comfortable putting in the PR, give it a go. I'm very pleased Forecastie has a "long tail" of developers and would like to continue that.

**Comment by robinpaulson** [comment]
Another problem which would likely be solved by using an OWM library instead of building our own interface. The UNIX philosophy is great. #428

**Comment by robinpaulson** [comment]
As an aside, the error message Forecastie provides is totally crap, I'll add this to the list which need fixing. #316

**Comment by capslockpirate** [comment]
Glad I could help!  I'm trying to get a dev environment set up right now, never done android stuff before. 
 I'm used to webapps, so it may take a little bit for me to get all set up. I couldn't find a how to develop readme file, is there some documentation I can follow to test my change?

**Comment by robinpaulson** [comment]
We don't have much in the way of docs, have you had a look in the "contributing.md" file, that's about it? Google's android dev resources are pretty good, maybe start there. https://developer.android.com

**Comment by lmaths** [comment]
Hi, i send a pull request to fix this bug.
