### ISSUE TITLE
Installation and configuration

### ISSUE THREAD

**Issue by ahxanhaxhmi** [martykan/forecastie#471]
Hello Sir i am newbie in this field can yu please tell me how to run this app on android studio ?
I will be very gratefull to you if yu tell th process how to run this on android studio i want to learn from it.

**Comment by robinpaulson** [comment]
Hi, I'm not sure how to respond to this. I'm not a fan of Android Studio (more Google proprietary nonsense), so don't use it.

Although you're welcome to ask questions here, this is a bit off-topic for Forecastie. I think you might be better off trying a generic Android programming guide, starting with a simple example project - Forecastie may be a little bit complicated to start off with. I'm sure there are many around on the web that are more suitable than this. I'll leave the issue open for now, but will likely close it later if it doesn't shift to on-topic.

**Comment by robinpaulson** [comment]
Also, you don't need to call me sir. ;-)

**Comment by fAntel** [comment]
Hi, @robinpaulson. Could you please suggest alternatives for Android Studio or what are you using for Android development?

**Comment by JigarSable** [comment]
> Hi, @robinpaulson. Could you please suggest alternatives for Android Studio or what are you using for Android development?

IntelliJ IDEA is the alternative for Android Studio, but for the better performances you should use Android Studio.

**Comment by JigarSable** [comment]
First of all you download it or clone and then simply import the complete project on Android Studio.

**Comment by robinpaulson** [comment]
I'm going to close this for now, I'm not sure there's much we can help with here. You can still comment though.
