### ISSUE TITLE
Feature Request: Language selection

### ISSUE THREAD

**Issue by primarto** [martykan/forecastie#475]
It would be nice to add in the settings that you can manually select the desired language, so that the language of the whole system does not have to be changed.

**Comment by robinpaulson** [comment]
We discussed this previously in #134. Is there anything there that helps? Could you describe your use case a little please, that will help to provide the best answer? Thanks

**Comment by robinpaulson** [comment]
I'm going to close this, please post more info if you would like to resurrect the discussion.
