### ISSUE TITLE
Time can get frozen/stuck on widget

### ISSUE THREAD

**Issue by Porkepix** [martykan/forecastie#482]
See the joined screenshot, time was frozen/stuck at a much older time than current one (visible in the top bar).

Screenshot is issued from a Pixel3a running Android 10.
![Screenshot_20200604-113651](https://user-images.githubusercontent.com/709500/83742540-cffd3700-a659-11ea-8e7a-1fabd908db17.png)

**Comment by robinpaulson** [comment]
Yeah there's a couple of issues already which discuss this.

**Comment by robinpaulson** [comment]
Which version of forecastie are you using?

**Comment by Porkepix** [comment]
Latest, 1.15.
