### ISSUE TITLE
UV Index sometimes shows incorrect values

### ISSUE THREAD

**Issue by weattyarbiter** [martykan/forecastie#488]
As in title UV Index value is changing to improper value on refresh.
e.g UV Index is Low during Night/Evening; the app will show this correctly until refreshing. 

Refreshing the app manually by pulling down causes the value to change from Low to Extreme. In some cases this event does not require manual refreshing to occur; following the example above, the correct UV Index Value of Low will show for a brief second or two before updating to the incorrect value of Extreme.

App Version: 1.15.1

**Comment by robinpaulson** [comment]
Yeah, I've seen this too, it's been there for a while.

**Comment by robinpaulson** [comment]
according to @reg4xp

>  When ever i refresh manually it sets UV index to very high

This matches my experience too

**Comment by robinpaulson** [comment]
I've added code which shows the numerical value of the UV index. I think this is useful, plus it might help debug this issue. Now I need to figure out how to round the figure, a UV index of "6.92" is a little bit over-precise.

**Comment by robinpaulson** [comment]
There are odd things happening to the UV index reporting, I wonder if the service is broken. When I request this (at 10pm):

https://api.openweathermap.org/data/2.5/uvi?lat=-36.8&lon=174.5&appid=3e29e62e2ddf6dd3d2ebd28aed069215

I get this:
{"lat":-36.8,"lon":174.5,"date_iso":"2020-10-11T12:00:00Z","date":1602417600,"value":6.68}

The UV level is 6.68 (it's very dark here)
The UNIX time is listed as 1602417600

Problem is, when I run this on the command-line:
date +%s

I get:
1602409937

as the current UNIX time.

Which is a much earlier time than the OWM UV API gives me. Earlier by around 7700 seconds, which is about 2 hours.

**Comment by robinpaulson** [comment]
Docs for the UV API:
https://openweathermap.org/api/uvi

**Comment by robinpaulson** [comment]
Ah, from:
https://openweathermap.org/api/uvi#responseformat

"Please remember that data is provided only for 12:00 p.m."

It's giving the current UV index at midday, presumably the most recent midday before the current time.

**Comment by robinpaulson** [comment]
The 2 hours is the time until midday GMT (I'm in NZ, 13 hours ahead of GMT). Sigh, the UV info is still useful, but we should indicate what exactly we are showing.

**Comment by robinpaulson** [comment]
It's midday GMT in a couple of hours, I'll see if the value changes then, and report it here.

**Comment by robinpaulson** [comment]
OK, it's after 1am NZ time, midday GMT, the UV value is still 6.68. I'll check again every hour.

**Comment by robinpaulson** [comment]
I set up a cron job to fetch the UV data at 1 minute past every hour, starting yesterday at 9pm local time (NZ). The reported value was 9.08, which stayed the same every hour until 13:01 today. Coincidentally (?), that is midday GMT.

I'll do the same experiment again for a different time zone, then compare the time at which the UV value changes.

**Comment by robinpaulson** [comment]
I set up a second cron job, this pulled data for Rio de Janeiro. Everything else was the same. The UV index stayed the same every hour, until 13:01 NZ time, which is of course midday GMT, the same as for NZ data.

So, it appears the new data value for a given location is displayed from midday GMT, wherever in the world you are getting data for.

I'm not sure how to display the data, I think we should inform users of the software what the number means, otherwise it's not terribly helpful.

Suggestions, anyone?

**Comment by robinpaulson** [comment]
I ran the test for another day, at Rio de J again. Same result, a change of value at midday GMT.

**Comment by robinpaulson** [comment]
It appears OWM are deprecating the current UVI forecast, see #581.

Given that is the case, this bug becomes redundant, as the One Call API which replaces it will not have the limitations detailed above. Closing.
