### ISSUE TITLE
Error Detect Location

### ISSUE THREAD

**Issue by IronetIvan** [martykan/forecastie#489]
When you click on the detect location menu, this is not the correct location so I think it should be caused in the _"Localize"_ method.

`private String localize(SharedPreferences sp, String preferenceKey, String defaultValueKey) {
        return localize(sp, this, preferenceKey, defaultValueKey);
    }

    public static String localize(SharedPreferences sp, Context context, String preferenceKey, String defaultValueKey) {
        String preferenceValue = sp.getString(preferenceKey, defaultValueKey);
        String result = preferenceValue;
        if ("speedUnit".equals(preferenceKey)) {
            if (speedUnits.containsKey(preferenceValue)) {
                result = context.getString(speedUnits.get(preferenceValue));
            }
        } else if ("pressureUnit".equals(preferenceKey)) {
            if (pressUnits.containsKey(preferenceValue)) {
                result = context.getString(pressUnits.get(preferenceValue));
            }
        }
        return result;
    }`

**Comment by fAntel** [comment]
Do you mean determined location is wrong or it is displayed in wrong language/locale? Because _localize_ is short for _localization_, i.e. translation from one language to another and in this case translation from default language to selected in smartphone settings.
If determined location is wrong, have you grant location permission to the app and does it still have this permission?

**Comment by robinpaulson** [comment]
> When you click on the detect location menu, this is not the correct location so I think it should be caused in the "Localize" method.

I'm not sure what this means, could you expand please?

as fantel asks, is Forecastie returning the wrong location for you?

**Comment by IronetIvan** [comment]
In no way does it show me my current location, so by default it shows me an incorrect.

**Comment by robinpaulson** [comment]
@IronetIvan 

as fantel asks:

> have you grant location permission to the app and does it still have this permission?
