### ISSUE TITLE
Dependency on Google Play Services for Location

### ISSUE THREAD

**Issue by icasdri** [martykan/forecastie#49]
A dependency on the proprietary Google Play Services seems to have been introduced by 32ef7458 in #40 for resolving coarse location. I wonder if it is possible to resolve location without these services, as introducing such a dependency has a couple important consequences, especially considering Forecastie is aiming to be a FOSS app:

1. Users of fully-free (or otherwise Google-free) roms would be unable to use our app.
2. We might get kicked from F-Droid (or F-Droid would have to maintain a separate branch with the proprietary services stripped out).

We may also look into configurable solutions, such as a setting to configure location provider, or as a stop-gap, a setting that guards against importing or creating the proprietary `GoogleAPIClient` (using dynamic import measures or otherwise). If desirable, I will spend some time looking into this.

**Comment by martykan** [comment]
I would abolish Google Play Services totally and use the native location services. I will work on it.

**Comment by martykan** [comment]
Fixed now, full freedom regained.
