### ISSUE TITLE
[Feature request] Adjustable widget transparency

### ISSUE THREAD

**Issue by huuhaa** [martykan/forecastie#490]
It would be nice to have option to adjust transparency of the widget, maybe even select color by own choice, but atleast possibility to adjust.

**Comment by robinpaulson** [comment]
We added an option to change the transparency of the widget, aside from it already being available as a solid colour determined by the theme. I'm reluctant to add more code for this, it doesn't feel substantial enough. Closing for now, I'm willing to hear more arguments though - do post them here if there's anything else you want to say on the matter, the issue can always be reopened.
