### ISSUE TITLE
Please Provide Percent Chance Of Rain On Daily Forecast Summary

### ISSUE THREAD

**Issue by DecodeRecode** [martykan/forecastie#496]
Guys, I am grateful for this app, and once I switched to Calyxos ROM. I was used to having my Pixel 2XL show the current weather on my home-screen. One thing that would be nice to have is to include the chance of rain (%) in the application forecast summary tab. I went through settings and I wasn't able to see any option to activate this. I believe this is a feature that should come standard for any weather app. Well keep up the good work, and for helping us with our daily planning!

**Comment by robinpaulson** [comment]
This was requested a while back, there was a discussion about it but nobody stepped forward to do the coding. When someone does, I'll be glad to accept it. I'll close this, the previous issue is still active.
#79
