### ISSUE TITLE
Background refresh interval suggestion

### ISSUE THREAD

**Issue by mrtootoo** [martykan/forecastie#501]
An alternative option instead of a time interval is to refresh the data upon screen unlock.

**Comment by robinpaulson** [comment]
Yes, it's an interesting and meaningful suggestion, with a good logic behind it.

**Comment by fAntel** [comment]
Forecastie already do that but with 5 minute threshold. Sometimes I even have time to see forecast-is-updating dialog on app start.

**Comment by robinpaulson** [comment]
See also #530, which is similar

**Comment by robinpaulson** [comment]
I think this is close enough to 530 that we can close one as a dupe. I realise this issue was opened first, but the other has more discussion, so I will close this. The two are linked, so the discussion here will not disappear into the empty void.
