### ISSUE TITLE
Widget improvements

### ISSUE THREAD

**Issue by dasmaetthes** [martykan/forecastie#51]
Hey,
The app is very nice, yesterday I tried also the widget. For me I can use it only as 4x3 widget to see the full informations and then I have a lot of empty space inside the widget. Is it possible to improve the font size and line gap for use as 4x2 or make the text scrollable?

http://tinyurl.com/jr4wynj

Edit: replaced link

**Comment by anarcat** [comment]
@dasmaetthes that link is dead: "File not found. The specified document has not been found on the server."

**Comment by FridoDeluxe** [comment]
I can confirm the behavior descrived by @dasmaetthes, with a 4x2 widget I can see only the upper part of the air pressure line. Increasing the size to 4x3 leaves too much empty space at the bottom of the widget.
(The device is a FullHD screen with 480 dpi LCD density using the default 4x4 homescreen grid of CyanogenMod 13)

**Comment by ildar** [comment]
![screenshot_2016-07-10-11-12-16](https://cloud.githubusercontent.com/assets/517752/17469924/af5aedf0-5d59-11e6-8193-b7b8c2f1281a.png)
indeed needs laboring.

**Comment by sudogitgud** [comment]
I would like to request for the widget to have a transparent or translucent background.

**Comment by nazar-pc** [comment]
Yeah, 4x2 with transparent background and only key information (no date/time, just weather) would be perfect. Currently widgets are too big.

**Comment by subiol** [comment]
+1 to configurable translucid to transparent widget.

Also, the widget does not follow the theme, it always show in the annoying blue background.

**Comment by picklecat** [comment]
I came here today to submit a feature request for the widget to have a transparent background option. Very glad to see there were already requests for it. A code reference for how to implement the transparent/color picker background for the widget can be found at Simple Calendar: https://github.com/SimpleMobileTools/Simple-Calendar

Cheers!

**Comment by robinpaulson** [comment]
We recently added code for a 2x1 widget. This will be released in v1.5; please check at the end of July to see if this covers any of the requests listed here.

**Comment by robinpaulson** [comment]
Some overlap with #133

**Comment by robinpaulson** [comment]
v1.5 was pushed forward; it will be available in f-droid in a few days.

**Comment by arucard21** [comment]
As mentioned before, a 2x1 widget was made available a while ago. And with the latest release (v1.6.2) the widget can now be made transparent as well. This seems to cover almost everything mentioned in this issue so it can probably be closed. If any other improvements are still wanted, it would be better to create a new issue for that.
