### ISSUE TITLE
Show daily min/max temp in the app and on the widget

### ISSUE THREAD

**Issue by mario-g98** [martykan/forecastie#510]
I love Forecastie a lot!
The feature that I'm missing the most is the ability to check the minimum and maximum temperatures for the day. It would be very nice if this could  be implemented.

Here is an example how it might look like:

![Screenshot_20200901-022818_1](https://user-images.githubusercontent.com/49582442/91782233-d2414400-ebfc-11ea-8cf2-ef3944f4a33d.jpg)

**Comment by robinpaulson** [comment]
We've talked about this before:
#212 

I'll close this as it's a dupe.
