### ISSUE TITLE
UV index

### ISSUE THREAD

**Issue by reg4xp** [martykan/forecastie#513]
Os: android 10
Version:1.15.6 f-droid
When ever i refresh manually it sets UV index to very high

**Comment by robinpaulson** [comment]
This is a dupe, however you have revealed possible useful info about the manual refresh. Now you mention it, that occurs occurs on my device too.

**Comment by robinpaulson** [comment]
#488

**Comment by robinpaulson** [comment]
I've added code which shows the numerical value of the UV index. I think this is useful, plus it might help debug this issue.
