### ISSUE TITLE
Wrong Android SDK Version at CONTRIBUTING.md

### ISSUE THREAD

**Issue by fAntel** [martykan/forecastie#516]
CONTRIBUTING.md says that Forecastie minimal support Android version is 4.0.3/API 14. But 4.0.3 is API 15 and `app/build.gradle` says that `minSdkVersion 15`. First commit of `app/build.gradle` also says that Forecastie minimum Android version was 4.0.2/API 15. Is this typo in CONTRIBUTING.md?

**Comment by robinpaulson** [comment]
Yup, sounds like a typo somewhere..... I've only been on board since 2016, so I don't know tomas' original intentions. What's the most conservative, least-likely-to-break-something option here?

**Comment by robinpaulson** [comment]
Perhaps the best option is to go with what builds, not what we say in the docs, i.e. API 15/4.0.3? Then update docs to match that?

**Comment by fAntel** [comment]
@robinpaulson the least-likely-to-break-something option is fixing typo in documentation.
