### ISSUE TITLE
sunrise and sunset

### ISSUE THREAD

**Issue by lucamp** [martykan/forecastie#52]
Hi,
could you please consider to add sunrise and sunset time to the main screen?

Thanks for your app
Luca

**Comment by MarcRdC** [comment]
I agree: it would be a nice addition to the application.

**Comment by vmazoyer** [comment]
I just noticed that, when expanded to 4x3 size, the widget displays the same information as the main screen.
In my pull request #77, I added the sunrise and sunset times to the main screen only.
Should the sunrise and sunset times also be visible on the widget?

**Comment by lucamp** [comment]
My forecastie widget has only 4x1 size, installed 0.9.1 from f-droid.
Nevertheless on a 4x3 size there is more space so I am pretty sure I and someone else like it

**Comment by lucamp** [comment]
sorry, I clicked the wrong button

I have only 4x1 wigdet, got forecastie 0.9.1 from fdroid.
Nevertheless in a 4x3 size there is more space so, in my opinion, sunsrise and sunset time could fit in it

**Comment by martykan** [comment]
It should be done now.
