### ISSUE TITLE
Proper XML within translations

### ISSUE THREAD

**Issue by nevyn-hira** [martykan/forecastie#520]
When working with the translations (app/src/main/res/values*/strings.xml), I found a problem within the Korean translation:

<string name="about_developers"><a href='mailto:t.martykan@gmail.com'>Tomas Martykan</a> 등 <a href='https://github.com/martykan/forecastie/graphs/contributors'>다른 인원들&lt;/a&gt; 이 개발하였으며, <a href='https://github.com/martykan/forecastie/issues?utf8=✓;q=is%3Aissue'>많은 이들의&lt;/a&gt; 도움이 있습니다.</string>

Essentially lines like this look to the any xml parser like the "<a" is trying to embed another xml structure. Looking up the problem further, from here: https://www.w3.org/TR/xml11/#syntax , it states:

_The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings "& amp;" and "& lt;" respectively. The right angle bracket (>) may be represented using the string "& g t ;", and MUST, for compatibility, be escaped using either "& gt;" or a character reference when it appears in the string "]]>" in content, when that string is not marking the end of a CDATA section._

As for the scope of the issue currently very few translations have tackled the about section which is where all links seem to appear. As far as I can tell, the only files that would currently need changing is the English translation and the Korean one. Are there any issues with changing the < and > characters within the text data to & l t ; and & g t ; ?

In the long term I think it'd be a positive to try and stick to the XML standard as much as possible but also acknowledge that

<string name="about_developers">& lt;a href='mailto:t.martykan@gmail.com'& gt;Tomas Martykan&lt;/a& gt; 등 & lt;a href='https://github.com/martykan/forecastie/graphs/contributors'&gt;다른 인원들&lt;/a& gt; 이 개발하였으며, & lt;a href='https://github.com/martykan/forecastie/issues?utf8=✓;q=is%3Aissue'& gt;많은 이들의&lt;/a&gt; 도움이 있습니다.</string>

is slightly less readable.

**Comment by robinpaulson** [comment]
Cheers for the heads up, this was causing endless build failures (#509 has more details)
