### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by fAntel** [martykan/forecastie#524]
Forecastie still uses support library that won't be updated because one is deprecated and it's recommended to use new AndroidX and Material components libraries.

Firstly, I think it will be good to start use maintained libraries.
Secondly, I've used Robolectric versions 4.x for tests for notification and Robolectric depends on AndroidX. It worked with Gradle plugin 3.x but Gradle plugin has been updated to 4.x when Forecastie target sdk versions had been raised to Android 9 (SDK 28) and now impossible to use AndroidX only for tests.

I rather ask permission than ask someone to do it

This issue relates to #447

**Comment by robinpaulson** [comment]
> Forecastie still uses support library that won't be updated because one is deprecated and it's recommended to use new AndroidX and Material components libraries.
> 
> Firstly, I think it will be good to start use maintained libraries.

yes, i agree

> Secondly, I've used Robolectric versions 4.x for tests for notification and Robolectric depends on AndroidX. It worked with Gradle plugin 3.x but Gradle plugin has been updated to 4.x when Forecastie target sdk versions had been raised to Android 9 (SDK 28) and now impossible to use AndroidX only for tests.
> 

i'm not sure what this means: "now impossible to use AndroidX only for tests"

> I rather ask permission than ask someone to do it

permission? this sounds excellent, go for it.
