### ISSUE TITLE
Option to update the forecast when we open the app

### ISSUE THREAD

**Issue by naoliv** [martykan/forecastie#530]
A more comfortable and pleasant way I can imagine to use the app is to open it and have the weather forecast automatically updated, without having to click on the update button and without having a service running in the background to update the forecast.
Could we have an option like this, to update the weather forecast when opening the application, please?

**Comment by fAntel** [comment]
Forecastie already do that. Forecast updates by the timer (period could be configured), on the app start and when a user returns to it. There is information about when forecast was updated on the main screen.

**Comment by naoliv** [comment]
I had the impression (and maybe I got it wrong) that if I enable the timer, the app would keep updating the forecast even if I don't open it (since it says "Update location in background").

**Comment by fAntel** [comment]
If you enable the timer than app will update forecast by the timer **and** on app start.
I've check, Forecastie have 5 minute threshold for updating forecast on app start or returning to app to avoid too frequent updates. I even thought there was issue about adding setting for change this threshold but I couldn't find it.
And there is no service to update forecast in background. Forecastie use `AlarmManager` to set alarm and wake ups only to update forecast.

**Comment by robinpaulson** [comment]
I assumed "Update location in background" meant update my location, as in the city i'm in, if i move around

**Comment by fAntel** [comment]
"in background" means when app doesn't open or is no the top app.
On Android 8, if I remember it correctly, apps doesn't get location in the background at all, and on Android 9 and above there is even new permission to start foreground services because with foreground service app considered to be in foreground and it can get location.
But Forecastie doesn't have services yet (it will be when I add notification) and even then without permission Forecastie won't get location in background on modern Android.
And Forecastie even doesn't need location if user select city.

**Comment by naoliv** [comment]
> "in background" means when app doesn't open or is nt the top app.
That is what I don't want.

I want to have it automatically updated only when I open the app.
If I stay, for example, 3 days without opening, I don't want any background update.

From what I tested it now, it's updating the forecast in background even if I don't open it.

**Comment by fAntel** [comment]
@naoliv There is option "Disabled" in refreh periods in settings.

@robinpaulson Maybe it isn't obvious and should be moved to separate setting?

**Comment by robinpaulson** [comment]
> Maybe it isn't obvious and should be moved to separate setting?

or another option in the existing list:
Update weather data:
Manually
When I open/foreground the app
Every 5 mins
Every 15 mins
....

And so on

**Comment by naoliv** [comment]
> @naoliv There is option "Disabled" in refreh periods in settings.

Hummm, right.
So probably "Update location in background" should be reworded, like @robinpaulson suggested.
Otherwise it gives us the impression that it will always be updating in the background, even when we do not open the application.

**Comment by fAntel** [comment]
If we add all options in one list, a user won't be able to choose several (or one will be able to choose several time periods which is wierd).
I think it would be better to split this options: periods of updates and update on app start. And maybe add option to choose how often should forecast be update on app start (now it is 5 minutes).

**Comment by robinpaulson** [comment]
> So probably "Update location in background" should be reworded

That's not quite what I meant, but never mind, that sounds good. I'm not entirely sure now what that option does.

> If we add all options in one list, a user won't be able to choose several (or one will be able to choose several time periods which is wierd).

True. On the other hand, this is a lot of options for a relatively unimportant setting, with small differences between them. What are the (bad) consequences of doing nothing?

**Comment by fAntel** [comment]
> True. On the other hand, this is a lot of options for a relatively unimportant setting, with small differences between them. What are the (bad) consequences of doing nothing?
Yes, I agree, this is relatively unimportant. Rewording should be enough.

**Comment by robinpaulson** [comment]
#501 is very similar

**Comment by mrtootoo** [comment]
> I assumed "Update location in background" meant update my location, as in the city i'm in, if i move around

I assumed the same.  However, I need to hit detect location for location to be updated.

**Comment by mrtootoo** [comment]
> > "in background" means when app doesn't open or is nt the top app.
> 
> That is what I don't want.
> 
> I want to have it automatically updated only when I open the app.
> If I stay, for example, 3 days without opening, I don't want any background update.
> 
> From what I tested it now, it's updating the forecast in background even if I don't open it.

Agree completely.

**Comment by robinpaulson** [comment]
> Yes, I agree, this is relatively unimportant. Rewording should be enough.

Any suggestions for the text we should use?

**Comment by robinpaulson** [comment]
I think this has been fixed, as far as I'm concerned anyway, but a recent PR. See the new release in a few days.
