### ISSUE TITLE
FDroid Repository Needs To Be Updated To 1.15.8

### ISSUE THREAD

**Issue by DecodeRecode** [martykan/forecastie#531]
Good afternoon, guys. I enjoy using Forecastie a lot. I know you have limited resources but could someone in your team update the FDroid repository with the latest version of 1.15.8. I downloaded the APK from the Github release page but I guess the signature is different from what I have installed. Thank you for the phenomenal app!

**Comment by robinpaulson** [comment]
It takes a few days for them to sync the sources, it'll get there.
