### ISSUE TITLE
Some words have not been translated into pt_BR

### ISSUE THREAD

**Issue by naoliv** [martykan/forecastie#533]
It seems that Forecastie is 100% translated for `pt_BR` in transifex, but some words are still in English.
Maybe this also affects other languages?

`Clouds` in the maps:

![](https://user-images.githubusercontent.com/982338/93657610-76532980-fa0a-11ea-85be-bc00fbaa2371.png)

`UV Index: <intensity>` at the initial screen:

![](https://user-images.githubusercontent.com/982338/93657615-7c490a80-fa0a-11ea-9c32-0e30d5464dd9.png)

The about screen:

![](https://user-images.githubusercontent.com/982338/93657618-7e12ce00-fa0a-11ea-9a13-e40bb61504f8.png)

`Wind Speed` in the graphics:

![](https://user-images.githubusercontent.com/982338/93657620-80752800-fa0a-11ea-9d1f-2df780fa7916.png)

`More days` in the graphics:

![](https://user-images.githubusercontent.com/982338/93657623-81a65500-fa0a-11ea-9343-8167191f6fef.png)

`Make widget transparent` in settings:

![](https://user-images.githubusercontent.com/982338/93657625-83701880-fa0a-11ea-8877-65325cbd00d3.png)

**Comment by robinpaulson** [comment]
Transifex is well out of date and we no longer have access to the site account you have probably looked at. All the strings are translatable, but waiting for someone to do them.

**Comment by naoliv** [comment]
So the transifex part of [CONTRIBUTING.md](https://github.com/martykan/forecastie/blob/master/CONTRIBUTING.md) should be updated then?

And what do you use to update the `strings.xml` files?
I can translate the missing `pt_BR` words but [values-pt-rBR/strings.xml](https://github.com/martykan/forecastie/blob/master/app/src/main/res/values-pt-rBR/strings.xml) seems to be missing them.

**Comment by robinpaulson** [comment]
> So the Translations part of CONTRIBUTING.md should be updated then?

Yes, good point.

> And what do you use to update the strings.xml files?

personally i use a combination of git and a text editor. personally i use "kate", but any is suitable (except for Windows Notepad)

it can also be done via the website. how conversant are you with git/github?

> I can translate the missing pt_BR words but values-pt-rBR/strings.xml seems to be missing them.

there is a template in the tools/ directory which will show you the order they should be in.

**Comment by robinpaulson** [comment]
I'm going to close this, as it's a known problem, which we are gradually fixing.

If you are not comfortable learning how to prepare a pull release, would you be OK with posting the missing strings here, then I will transcribe them by hand into the codebase?

**Comment by naoliv** [comment]
I am fine with pull requests :-)
As soon as I finish the translations I will create a PR.
