### ISSUE TITLE
Broken escaping in About

### ISSUE THREAD

**Issue by naoliv** [martykan/forecastie#534]
(Sorry to be a little annoying lately :-))
It seems that some of the escaping work between version `1.15.7` and  `1.15.8` broke the `About` page:

![](https://user-images.githubusercontent.com/982338/93664551-34e06f80-fa46-11ea-8fc4-9b45f803028f.png)

**Comment by robinpaulson** [comment]
Erk! Cheers

**Comment by robinpaulson** [comment]
Also: you're not annoying. Reporting bugs, making suggestions. etc. is good, it means the community is healthy.

**Comment by robinpaulson** [comment]
OK, I think I've solved that. There will be another new release, v1.16, out in a few days. It will also include a slew of other fixes and improvements, including migration to androidx and sdk29.
