### ISSUE TITLE
Selected theme is not obeyed in "Weather Maps" screen

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#538]
I have "Classic Dark" theme selected, but the menu bar to the maps screen is bright blue, which is more in keeping with one of the "Fresh" themes.

**Comment by robinpaulson** [comment]
I wonder if there was a change as a result of the upgrade to SDK29/AndroidX?

**Comment by robinpaulson** [comment]
On this line:
https://github.com/martykan/forecastie/blob/master/app/src/main/res/layout/activity_map.xml#L20

"background" is set to "colorPrimary", which is a static hex value of #2196F3, rather than a variable to match the theme. I'm not sure how to set a colour to a variable though. Unless it should be "?attr/colorPrimary" as in activity_main.xml ? I'll give it a go....

**Comment by fAntel** [comment]
@robinpaulson reliable way to set color is programmatically, i.e. in the code. "?attr" works fine on Android 6 and above but it could be parsed wrong on Android 5 and below. [`ContextCompat`](https://developer.android.com/reference/androidx/core/content/ContextCompat) could be used to parse drawables or color states with "?attr" if needed.

**Comment by robinpaulson** [comment]
should we be removing all instances of ?attr then, there are more than what i saw in activity_graph.xml?

**Comment by fAntel** [comment]
Hm. Maybe I'm wrong and as just a color it works fine. I'll look at code and check themes later. I've created a bunch of emulators with different Android versions when started to code for Forecastie :)

**Comment by robinpaulson** [comment]
I've modified it as I originally suggested, it builds OK. I'll take a look at some docs later, see what best practice is.

**Comment by robinpaulson** [comment]
I tried forecastie on older phones (Android 5 and 6), it appeared to work OK, apart from the weather icon being too wide for the screen.

**Comment by fAntel** [comment]
I've checked Graph activity for Android 4.0.3 (SDK 15) and it looks well. I guess the problem with `?attr` occurs only for drawables and color state lists.

**Comment by robinpaulson** [comment]
@fAntel Good to hear. From now on I'll be frequently testing Forecastie on my older phones, it'd be great if you were able to do so occasionally as well, on your v4.0.3 device.
