### ISSUE TITLE
Make icons for graphs, settings, detect location

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#539]
We should allow all icons to show on the  top bar, rather than solely in the menu, this will be useful on wider screens. To do this, we require icons. Maybe we can find some which are CC?

**Comment by FridoDeluxe** [comment]
Google's Material icons are available under Apache license 2.0: https://material.io/resources/icons/.

**Comment by robinpaulson** [comment]
OK, added with the latest commit. We'll see what everyone thinks, they may not fit with the existing icons. Maybe we should update the whole lot to be Material compliant......
