### ISSUE TITLE
Remove or use redundant "app/src/test/" directory

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#541]
In the file tree, there is a folder named "test" (under app/src/), which contains unused files. I presume they are an artefact of the default project from Android Studio or similar. I propose we delete them, or alternatively expand them to include unit tests

**Comment by fAntel** [comment]
I agree that generated by Android Studio default unit test is redundant and should be removed. But I use this pass to write some unit tests for notification and I'm going to add more test in the future to less worry during refactoring.

**Comment by robinpaulson** [comment]
Excellent, I'm glad to hear that. I have little experience with unit tests, I'm intrigued to see what you will come up with.

**Comment by robinpaulson** [comment]
@fAntel One of the unit tests you added is causing the build to fail, as far as i can tell, anyway. https://github.com/martykan/forecastie/runs/1547544582?check_suite_focus=true#step:4:744

"cz.martykan.forecastie.notifications.repository.WeatherRepositoryTests > observeWeatherEmitsNewValuesWhenTheyAreUpdatedInSharedPreference FAILED
    java.lang.AssertionError at WeatherRepositoryTests.java:123"

would you be able to take a look?

cheers

**Comment by fAntel** [comment]
@robinpaulson yes, of course, I'll look at it today.

**Comment by fAntel** [comment]
@robinpaulson I've sent PR with fix for this test. It was a bad decision to use `Thread.sleep` to wait until background thread has ended its job.

**Comment by robinpaulson** [comment]
thanks very much, the last build worked fine.

**Comment by robinpaulson** [comment]
Hi again fantel, I'm getting a similar error again on build:
https://github.com/martykan/forecastie/runs/2480274063?check_suite_focus=true#step:4:725

cz.martykan.forecastie.notifications.repository.WeatherRepositoryTests > observeWeatherEmitsNewValuesWhenTheyAreUpdatedInSharedPreference FAILED

It'd be great if you could check it out. Cheers

**Comment by robinpaulson** [comment]
How odd, all we did was add a .gif, that caused the failure.
