### ISSUE TITLE
API

### ISSUE THREAD

**Issue by admin196** [martykan/forecastie#544]
Hi
Do you using free API of open weather of open weather map??

**Comment by robinpaulson** [comment]
Yes

**Comment by admin196** [comment]
By using this API, can we get 10day forecast?

**Comment by robinpaulson** [comment]
Possibly, but I'm not convinced it would be reliable.

**Comment by robinpaulson** [comment]
Take a look at openweathermap.org/api for details of what the api is capable of

**Comment by admin196** [comment]
Where can I give my own API in codes?

**Comment by robinpaulson** [comment]
> Where can I give my own API in codes?

pardon?

**Comment by admin196** [comment]
Can I use the API that I have? how?

**Comment by robinpaulson** [comment]
> Can I use the API that I have? how?

I still don't understand the question. What do you mean "the API that I have"?

**Comment by fAntel** [comment]
@admin196 hi, do you mean that you have [https://openweathermap.org/price](your own OWM key) and want to use it in Forecastie?
If it is so, @FridoDeluxe [https://github.com/martykan/forecastie/issues/499#issuecomment-694508680](has told) about adding ability for user to use their own key, but it will take a lot of work.
For now you can clone Forecastie source, replace free key with yours and build app for yourself.

**Comment by robinpaulson** [comment]
#48 is relevant then

**Comment by robinpaulson** [comment]
It's possible to enter one's own API Key already, via "Settings".

**Comment by FridoDeluxe** [comment]
Forecastie utilizes the following APIs from OpenWeatherMap (all included in a free subscription):
- [current weather data](https://openweathermap.org/current)
- [5 day / 3 hour forecast](https://openweathermap.org/forecast5)
- [current UV data](https://openweathermap.org/api/uvi)

Although you can enter an API key of a paid plan, Forecastie will not be able to benefit from APIs included in a paid subscription so far.

**Comment by admin196** [comment]
Thanks

**Comment by robinpaulson** [comment]
@admin196 Does that help, is there anything else we can do to assist?

**Comment by admin196** [comment]
No thanks

**Comment by robinpaulson** [comment]
Great, I'll close this issue. Please open another if you have more questions about the app or the code.
