### ISSUE TITLE
Weather on my Ulefone Armor 3W

### ISSUE THREAD

**Issue by TruthLifestyle** [martykan/forecastie#545]
Tried downloading the Forecastie app on my phone and I got the issue shown in the screenshot. Any way I can bypass this issue? Any help is appreciated.
![Screenshot_20201005064402](https://user-images.githubusercontent.com/72259048/95087536-aa9b3b00-06d6-11eb-9c18-dfb1be6dc0ea.png)

**Comment by fAntel** [comment]
@TruthLifestyle Screenshot says that Forecastie has been updated last time 3 months ago but actually Forecastie has been update couple days ago. Try to update F-Droid repository: go to Update tab and make pull-to-refresh (swipe from top to bottom).

**Comment by TruthLifestyle** [comment]
Hey @fAntel thanks for pointing out the obvious 🤦‍♂️. lol
I updated F-Droid and the app failed to load. I than realized the phone I'm using has Android 9 (Pie). I downloaded an older version and now it's working. Yay me. A lot can be missed when a person (me) is rushing past the simple details.

**Comment by robinpaulson** [comment]
> I downloaded an older version and now it's working

Do you mean the most recent version of Forecastie is not working on your phone? Could you expand, please?

**Comment by TruthLifestyle** [comment]
I am currently using a Ulefone Armor 3W global phone. It comes with Android OS 9 and no option to update to a newer version (unless I want to Root).
I have attached a screenshot of the error msg that pops up.
Thank you
-------- Original Message --------

**Comment by TruthLifestyle** [comment]
I have a screenshot attached that shows the error message which pops up when I try to download a newer (current) version.

Thank you

-------- Original Message --------

**Comment by robinpaulson** [comment]
@TruthLifestyle I'm not sure what you're saying here. You closed the issue; is it fixed? There are no images attached, could you try again?

> no option to update to a newer version

what does this mean, a newer version of what?
