### ISSUE TITLE
Add feels like temperature

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [martykan/forecastie#553]
Is it possible to add feels like temperature? In the past i always used the weather app from 'The Weather Channel and they always displayed a feels like temp. I really like ur app but this is the only thing i miss.

![Capture](https://user-images.githubusercontent.com/73130443/97325174-9c21e880-186a-11eb-85e6-74db1b3ac84a.PNG)

**Comment by robinpaulson** [comment]
Yes, we've had a couple of requests for this previously. Closing as it's a dupe, at least one other is still active. #321

**Comment by robinpaulson** [comment]
As an aside, I like that little graphic which shows the sun position. It's simple but conveys information about sunrise/solar noon/sunset in a less abstract way than is generally used in these sort of apps.

**Comment by robinpaulson** [comment]
Also: interesting Github username, is there any significance to it?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> 
> 
> Also: interesting Github username, is there any significance to it?

Haha no there is no significance in the username. I just don't value making up usernames (expect for gaming) so i just use a random generated UUID.
