### ISSUE TITLE
Unused string resources

### ISSUE THREAD

**Issue by igor-cali** [martykan/forecastie#555]
I cannot find any usage in the code for the following strings:
- `notification_service_description`
- `channel_name`
- `settings_title_notifications`
- `settings_enable_notification_title`
- `settings_notification_type_title`
- `settings_notification_type_default`
- `settings_notification_type_simple`

Are they placeholders for something yet to come or obsolete resources?

**Comment by robinpaulson** [comment]
Apart from "channel_name", they sound like they might be related to the Notifications added by @fAntel recently. They mentioned there was more to come.

Do you know from git who added them?

**Comment by fAntel** [comment]
- `notification_service_description` used in manifest. As [documentation](https://developer.android.com/guide/topics/manifest/service-element) states it is used by Android to "A string that describes the service to users."
- `channel_name` used in `WeatherNotificationService.createNotificationChannelIfNeeded()` to specify channel description in app notification settings in Android UI on Android 8 and above.
- `settings_title_notifications`, `settings_enable_notification_title`, `settings_notification_type_title`, `settings_notification_type_default`, `settings_notification_type_simple` used for preferences in `prefs.xml`
