### ISSUE TITLE
City selection: Maps broken?

### ISSUE THREAD

**Issue by gaelanlloyd** [martykan/forecastie#560]
Not sure what is supposed to be showing in these previews, looks like they might be maps?  But they show up as blank areas on my device.  Nokia 5.3, Android 10.
![Screenshot_20201207-233258](https://user-images.githubusercontent.com/1403649/101510849-45123780-392f-11eb-84b5-0a7b722683e3.png)

**Comment by robinpaulson** [comment]
Correct, there should be a map there. Which version are you using? The most recent is delivered by fdroid

**Comment by gaelanlloyd** [comment]
1.10.2, from Google Play.  Looks like that's way out of date.  Just installed 1.17 from F-Droid and I see maps now.  Thanks!
