### ISSUE TITLE
City selection: Help differentiate cities in results list

### ISSUE THREAD

**Issue by gaelanlloyd** [martykan/forecastie#561]
When selecting a city and multiple results come back for the search, it's impossible to differentiate between cities in the list.  Maybe the broken map issue #560 would help this, but showing the state's name and ZIP code would also help.

For example, try searching "Orange".  There are two Orange Counties (CA and FL), as well as cities named Orange.

**Comment by robinpaulson** [comment]
There is a fix proposed for showing province/state info which hasn't been coded yet. I'll see if I can find it

**Comment by robinpaulson** [comment]
#420

**Comment by robinpaulson** [comment]
I'll close this too, as it's also a dupe.
