### ISSUE TITLE
Condensed data/graph view

### ISSUE THREAD

**Issue by gaelanlloyd** [martykan/forecastie#562]
I'd like a way to see important forecast information for the next few days (temperature and rain chance) with less scrolling.  A combined graph would be really helpful, here's just a quick mockup idea I threw together.  A combined chart like this would be super helpful as a desktop widget!

![forecastie](https://user-images.githubusercontent.com/1403649/101515003-bd2e2c80-3932-11eb-9f3a-5f13752132e0.png)

**Comment by robinpaulson** [comment]
Yep, this is on pur (non-existent) roadmap, it's waiting for a coder. See #249. Closing as this is a dupe.
