### ISSUE TITLE
Weather information may overwrite weather icon

### ISSUE THREAD

**Issue by TheLastProject** [martykan/forecastie#57]
Light intensity shower rain seems to be too long for my device. Motorola Moto E 2015 LTE, CyanogenMod 12.1 (Android 5.1.1), Forecastie 0.9 from F-Droid:  
![tmp_15676-screenshot_2016-02-10-18-57-38-73622860](https://cloud.githubusercontent.com/assets/1885159/12956477/8bb7515e-d028-11e5-82ea-0a7c23744dd0.png)

**Comment by martykan** [comment]
It should be fixed now.
