### ISSUE TITLE
Follow system theme

### ISSUE THREAD

**Issue by julianfairfax** [martykan/forecastie#582]
Forecastie has a light theme and a dark theme but it doesn't follow the system theme. If it would follow the system theme and change to the light theme or the dark theme automatically based on what the system theme is, it would improve the integration with the android system, and it would be a welcome change for me. Thanks for all the work you've put into this wonderful app!

**Comment by julian-fairfax** [comment]
I'm no longer using this app so you can ignore this. (I still love the app, I just found something that suits my specific needs better)

**Comment by julianfairfax** [comment]
I'm no longer using this app so you can ignore this. (I still love the app, I just don't need a weather app at this time)

**Comment by julianfairfax** [comment]
Reopening this since it would still be useful if I would use Forecastie and you seem to have showed initiative in adding it, at some point.

**Comment by julianfairfax** [comment]
Or not.

**Comment by julianfairfax** [comment]
Sorry for closing and opening this again, would you still be up for adding this functionality? Thanks for your wonderful app!

**Comment by robinpaulson** [comment]
Just leave it open. Maybe we get to it, maybe not.
