### ISSUE TITLE
Finnish translation (attached)

### ISSUE THREAD

**Issue by huuhaa** [martykan/forecastie#584]
I made new Finnish translations for the app, since there wasn't much of terms translated at the app. I don't know is there everything translated at here either. I used Swedish translation file as a base and added some lines to map part which werent there translated. I tried to quess right string for those etc. so there might be some errors, but hope this isn't complete waist in time for trying to translate app to Finnish.

I can't attach .xml file so I attach it as .txt

[strings.txt](https://github.com/martykan/forecastie/files/6353668/strings.txt)

**Comment by robinpaulson** [comment]
Excellent, I'll have a look through it tomorrow and transcribe into the appropriate location. It's good to have your contribution.

**Comment by huuhaa** [comment]
Just checking, should I translate more (or all) of those .xml which are at values folder? The time I did translation, I just looked few other translations and mostly strings were only translated. Sure by long term I probably should learn to use github properly and contribute by merging those translations...

**Comment by robinpaulson** [comment]
> should I translate more (or all) of those .xml which are at values folder?

that would be great, yes thanks

some months back i decided to break the single "strings.xml" files into manageable sections, one section to each file,

**Comment by robinpaulson** [comment]
@huuhaa Will you be splitting the file, or shall I add it to the repo, to be split later? Or do you want me to split it? Either is fine, but I'd rather ask what you want than guess.

**Comment by huuhaa** [comment]
@robinpaulson Sorry for late reply, I probably have to check I have updated email address here.. Anyway for the question. Maybe it's better you to split.  After all I don't have yet much (almost none) experience of working at github, just rescently did my first translation as merge at gitlab, got to study bit more to be sure I do it right way.. Anyway, if you do the split and I do my best to offer translation part as merge, not attached.

**Comment by robinpaulson** [comment]
That's OK, no problem. Yep, I'll look at it later and do the split

**Comment by robinpaulson** [comment]
I forgot about this ... added a moment ago.

**Comment by huuhaa** [comment]
I saw Finnish translation at app, probably at december or janyary, after that (maybe update) seems like translation isn't part of app anymore, or app doesn't recognice system languagu at phone). Sure I understand that some might want to use English, so option to choose preferred language would also be nice.
