### ISSUE TITLE
API key invalid and maybe multiple cities support?

### ISSUE THREAD

**Issue by Horuyuki** [martykan/forecastie#590]
Hello dev!

I just installed the app, copied into it an API key from openweather, yet it said it was incorrect when I tried to update my location with the key applied.

What could have gone wrong? I just created and copied pasted the key as I normally would on per say gnome.

~~Another thing is, is there a way for me to change my location without location access but rather with a manual input?~~

~~I can't seem to find a way to input that even tho it is mentioned to be possible in the play store.~~

Nevermind, I had to search it with the looking glass to find cities. 

Though I would like to know if you have enough time to add multiple city support? That would be a nice feature!

Thanks for reviewing!

**Comment by robinpaulson** [comment]
> is there a way for me to change my location without location access but rather with a manual input?

Yes, hit the magnifying glass icon at the top of the screen and type your city name

**Comment by robinpaulson** [comment]
> Though I would like to know if you have enough time to add multiple city support? That would be a nice feature!

eventually, it's in the wishlist ......

**Comment by robinpaulson** [comment]
> I just installed the app, copied into it an API key from openweather, yet it said it was incorrect when I tried to update my location 
> with the key applied.

OK, this could be fiddly. first, does it match the length of our API key, i.e. 32 characters?
3e29e62e2ddf6dd3d2ebd28aed069215

Are you sure there are no trailing spaces or carriage return/newline characters?

Is there a particular reason you use your own key, rather than that which is included?

**Comment by Horuyuki** [comment]
> Is there a particular reason you use your own key, rather than that which is included?

I thought that it is better to use my own key as that is what most other weather programs. recommended me to do. Like the gnome open weather and so such.

And plus, since you gave us the option to use out own, I thought that was the intention too., is there no need to?

**Comment by robinpaulson** [comment]
> I thought that was the intention too., is there no need to?

it will work fine with the preinstalled mass-use key, but yes we provide a means to input an individual user's API key. up to you. i was curious is all.

**Comment by Horuyuki** [comment]
Thank you! Will patiently wait for the new features!

**Comment by Horuyuki** [comment]
Thank you! Will patiently wait for the new features!
