### ISSUE TITLE
Translations needed

### ISSUE THREAD

**Issue by martykan** [martykan/forecastie#6]
We have some new strings for v0.4 and we need to translate them. These are a bit more complicated, so Google Translate won't be enough. We need them in ~~Spanish, Basque (@beriain could help), Japanese (@naofum)~~, French, Italian, Dutch, Russian. It's better to have them before release, than after release, where everything changes anyway. 

```
<string name="setting_imperialDate">Use imperial date format</string>
<string name="setting_imperialDate_description">12/31/2001 instead of 31.12.2001</string>
<string name="setting_showDay">Show day of the week</string>
<string name="setting_speedUnits">Speed units</string>
<string name="setting_tempUnits">Temperature units</string>
<string name="setting_pressureUnits">Pressure units</string>
```
I know we won't get it in all languages, but let's try to get as much as possible.

**Comment by ArchangeGabriel** [comment]
Do you still need those? If so, french ones:

```
<string name="setting_imperialDate">Utiliser le format mm/jj/aaaa pour les dates</string>
<string name="setting_imperialDate_description">12/31/2001 au lieu de 31.12.2001</string>
<string name="setting_showDay">Afficher le jour de la semaine</string>
<string name="setting_speedUnits">Unités pour la vitesse</string>
<string name="setting_tempUnits">Unité pour la température</string>
<string name="setting_pressureUnits">Unité pour la pression</string>
```

**Comment by martykan** [comment]
Yep, still need those.

**Comment by Zagur** [comment]
Hi,

I love this app! Catalan translation!

<string name="setting_imperialDate">Utilitzeu el format de data imperial</string>
<string name="setting_imperialDate_description">12/31/2001 en lloc de 31.12.2001</string>
<string name="setting_showDay">Mostra el dia de la setmana</string>
<string name="setting_speedUnits">Unitats de velocitat</string>
<string name="setting_tempUnits">Unitats de temperatura</string>
<string name="setting_pressureUnits">Unitats de pressió</string>

**Comment by fazyloff** [comment]
Hi, 
Russian traslation:

<string name="setting_imperialDate">Использовать формат даты ММ/ДД/ГГГГ</string>
<string name="setting_imperialDate_description">12/31/2001 вместо 31.12.2001</string>
<string name="setting_showDay">Отображать день недели</string>
<string name="setting_speedUnits">Единицы скорости</string>
<string name="setting_tempUnits">Единицы температуры</string>
<string name="setting_pressureUnits">Единицы давления</string>
