### ISSUE TITLE
Widget not tap-able 

### ISSUE THREAD

**Issue by dasmaetthes** [martykan/forecastie#60]
But when I tab on the widget nothing happen, nice would be when it open's the app.
Maybe it just doesn't work on my device ( Motorola Razr I x86, CM 11, Android 4.4.4)

**Comment by anarcat** [comment]
I do not think this is specific to your device, I get the same on CM 12.1 and HTC One S.

**Comment by anarcat** [comment]
@dasmaetthes why did you close this - is the issue resolved?

**Comment by martykan** [comment]
It's not resolved, I will open it again.

**Comment by dasmaetthes** [comment]
It's solved since version 1.0 for me

**Comment by martykan** [comment]
Oh, I see it's working now. I will close it then.
