### ISSUE TITLE
Some display issues on the main page

### ISSUE THREAD

**Issue by yuhuitech** [martykan/forecastie#601]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the main page, **several texts overlap together and a weather icon is blocked also**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**. And because of too many texts on this page, the bigger fonts and display settings would make those strings be displayed in a cramped way.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.17.3, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts without overlapping and the weather icon fully.

**Steps to reproduce the behavior:**

1. use the largest font and display in the display setting
2. open this app
3. this error could be seen after the resource downloading is finished

**Screenshot**

(The issues are marked in red)

<img src="https://user-images.githubusercontent.com/25502419/131473877-f8dc7d13-2781-41c1-a079-c65d5934f5be.png" alt="copy" width="250"/> <img src="https://user-images.githubusercontent.com/25502419/131473881-83e85889-26f1-4fcb-85f5-ef04284dc126.png" alt="copy" width="250"/>

**Environment**

1. Version of forecastie: 1.17.3
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by robinpaulson** [comment]
I realise we have similar issues in the widget. See #486

**Comment by robinpaulson** [comment]
I believe this is fixed with the most recent PR you made, so I'll close. Please attach more comments if you have anything more you wish to add.

**Comment by robinpaulson** [comment]
Hi @yuhuitech the 'main' page is severely broken since I merged your PR. I will revert them later today when I get home. Do submit another PR of you think you can fix the problem. See #621

**Comment by robinpaulson** [comment]
I have reverted the changes you made in #602 and released a new version. It will be in F-Droid in a few days.

**Comment by FridoDeluxe** [comment]
Maybe the "broken" FlexboxLayout can be fixed easily. For a quick solution one could alter the left LinearLayout (containing the Icon which is now mising with the UI problems) in `activity_scrolling.xml` and just change its width from `0dp` to `wrap_content`. At least this seemed to work on my device. (still this isn't tested thoroughly and I didn't analyze all the layout changes)
