### ISSUE TITLE
[Feature request] Switch to Norwegian Meteorological Service

### ISSUE THREAD

**Issue by julianfairfax** [martykan/forecastie#603]
Switching to the Norwegian Meteorological Service as a weather service would make this a fully open source app, provide weather data parity with GNOME Weather, and rely on European infrastructure. If, understandably, this isn't something you'd want to do fully, at least having it as an option would be very nice. In it's current configuration, and in the current configuration of every open source weather app, I get different data from GNOME Weather, different data from my country's official weather service, and a non-free network service, which isn't something I find useful. Thanks for your work on this wonderful app, and I hope it continues to get better!

**Comment by robinpaulson** [comment]
It's not about want or don't want, it's about development time. There is an issue here already asking for this service #126  and others. I'll close as this is a dupe.

**Comment by robinpaulson** [comment]
As an aside, I use two weather service providers too, NZ Met Service and OWM. Yep, they frequently give me different answers too, but that's a good thing. Meteorology is not as exact a science as say mechanical engineering, getting multiple answers and being prepared for all of them is not a bad thing. I live on a boat, so I guess that's more important for me, but I think the general point holds for most people.

**Comment by julianfairfax** [comment]
It's also worth mentioning I was wrong about it being a free network service. It seems no weather service is just no bank, or carrier, or ISP is, since it relies on having actual infrastructure to run, and how that is run is not shared. The data however, with both services is, which is a good thing. For now I will use my country's official weather service since only the app is additionally closed source compared to these two other services, and the data is the most accurate.
