### ISSUE TITLE
Map overlay not working

### ISSUE THREAD

**Issue by suncoastkid** [martykan/forecastie#608]
The map opens up but there is no overlay data, just the map. Android 10 installed via F-droid.

**Comment by robinpaulson** [comment]
huh, interesting, it works here ok.

does the forecast work?

**Comment by robinpaulson** [comment]
i've been meaning to look up other tile sets, to see if they are a bit more usable.

**Comment by robinpaulson** [comment]
#563

**Comment by robinpaulson** [comment]
I'll assume this is the same problem and close as a duplicate
