### ISSUE TITLE
Strengthen Korean translation.

### ISSUE THREAD

**Issue by BAESI** [martykan/forecastie#615]
Hello developer! 

I'm very sorry that I couldn't fix the previous issue. So I want to benefit this app in different ways. 
the Korean translation of this application is awkward.  Can I translate it into Korean naturally? 
I already know how to do it.

**Comment by robinpaulson** [comment]
Absolutely, any contributions are appreciated!

I'm curious, in the space of a few days, a number of Korean-based coders made suggestions, bug reports, etc. The same happened about the same time last year. I wonder if there is a link, perhaps you are at university together?

**Comment by BAESI** [comment]
Yes, they are my university team members. We are currently studying opensource and want to contribute to your source. Although we lack the ability, we will try to contribute as much as possible!

**Comment by robinpaulson** [comment]
Excellent, I'm glad you are interested in contributing. Do ask if you have any questions.

**Comment by BAESI** [comment]
complete translate!
