### ISSUE TITLE
Broken layout and expired API key

### ISSUE THREAD

**Issue by BAESI** [martykan/forecastie#618]
It seems to be broken due to recent mudge.
![image](https://user-images.githubusercontent.com/28686402/143875645-29336f06-d26c-46a6-847d-3548ccb68b1f.png)
![image](https://user-images.githubusercontent.com/28686402/143875673-a56dc929-16c7-4466-8c63-a1a9436e4dc8.png)

and invaild api key problem Do I have to get a key issued and use it?

**Comment by robinpaulson** [comment]
What is mudge?

**Comment by BAESI** [comment]
sorry merge

**Comment by robinpaulson** [comment]
Which merge?

**Comment by BAESI** [comment]
Does it come out normally if you run the application?

**Comment by robinpaulson** [comment]
> Does it come out normally if you run the application?

what do you mean? what is "it"?

**Comment by initenit** [comment]
> > Does it come out normally if you run the application?
> 
> what do you mean? what is "it"?

I think it means does it look correctly when you're running the app.

**Comment by robinpaulson** [comment]
yes, it looks fine here.

**Comment by digital-mystik** [comment]
it appears the bundled API key has expired to OP's second point

**Comment by robinpaulson** [comment]
> it appears the bundled API key has expired to OP's second point

ah .... i didn't know they expired.

**Comment by digital-mystik** [comment]
@robinpaulson not totally sure if expired, or maybe gone over the limit potentially

**Comment by RiK621** [comment]
Hi! There is the same issue too. App show me alert that the API key is invalid.
@martykan Will you update the API key?

**Comment by robinpaulson** [comment]
i recall we sorted the error messages a while back, so i'll go with "expired" sd the problem.

**Comment by initenit** [comment]
> yes, it looks fine here.

Could you tell me the device's resolution that you run on this app? My layout is still broken in 1080 x 2220, 1080 x 2340 and 1440 x 2560 after I put my API Key on this app.
![image](https://user-images.githubusercontent.com/28488250/143906046-f3ac511b-ca86-47dd-ab25-6c4c6314e28b.png)

**Comment by initenit** [comment]
> Hi! There is the same issue too. App show me alert that the API key is invalid. @martykan Will you update the API key?

Is your layout looks correctly?

**Comment by RiK621** [comment]
> layout looks correctly

Yes, it is. Layout looks correctly. But App shows me alert about the invalid API key.

**Comment by Halilb1978** [comment]
Yea, it says invalid api key

**Comment by robinpaulson** [comment]
We had a similar problem about 4 years ago, we (apparently temporarily) fixed it then, I've asked the guy who dealt with it then for more info.

**Comment by BAESI** [comment]
I solved this problem by receiving a new key from openweatherMap.

**Comment by BAESI** [comment]
@robinpaulson  Until #616 , the screen is output normally. However, after that, it will not be printed normally. Is it different depending on the situation?

**Comment by mrtootoo** [comment]
> I solved this problem by receiving a new key from openweatherMap.

I know this was closed for being a duplicate, but that post was the most concise (easy to understand), didn't interject any speculation,  and provided a temporary solution.

**Comment by MichaelR95** [comment]
It appears that the API key issue is still present.

**Comment by Halilb1978** [comment]
Still not working

**Comment by James-G-I** [comment]
I'm having the same problem when I open the Forecastie app and when I try to refresh it.

**Comment by robinpaulson** [comment]
I contacted OWM, they were slow replying. Eventually I got this:
"I couldn't find an account with this API key, this API key does not exist. Please try to use the key tied to this account."

This is for the API key embedded in the app, that we've been using for 4 years. I've written back, explaining the situation, asking if it's possible to get another key with increased requests.

I'll post more as I hear more.

**Comment by robinpaulson** [comment]
I've unlocked the discussion. No more comments saying "This bug effects me too!", they're redundant noise and irritating.

**Comment by robinpaulson** [comment]
OK, we got a new key, it's in the repo. I'll put out a new release shortly, in the meantime you're welcome to manually set the api key in the settings:
5dfc6b895bd1f7dad9595d05e09f6be4

**Comment by robinpaulson** [comment]
Huzzah, the new release built fine. It'll be in the F-Droid tubes in a few days.

Alternatively, you can download the new apk from here:
https://github.com/martykan/forecastie/suites/4579234216/artifacts/123315083

**Comment by tempaccounttoask** [comment]
Not able to install the APK.
![Screenshot_2021-12-10-01-22-17-779_com google android packageinstaller~01~01~01](https://user-images.githubusercontent.com/95173374/145501537-4a5bab37-fdc0-4d4a-8c37-3eb8ecb891fb.jpg)

**Comment by DemoniWaari** [comment]
The API key is still an issue. I tried reinstalling, hoping it would update the API key but it did not work.

**Comment by RiK621** [comment]
> Not able to install the APK. ![Screenshot_2021-12-10-01-22-17-779_com google android packageinstaller0101~01](https://user-images.githubusercontent.com/95173374/145501537-4a5bab37-fdc0-4d4a-8c37-3eb8ecb891fb.jpg)

The same issue. I can't install version 1.18.2. Installer notifies me that 'App not installed'.

**Comment by robinpaulson** [comment]
@RiK621 did you read the bit about not repeating the same statements, because it's distracting noise?

**Comment by robinpaulson** [comment]
The build posted on the github releases page was broken, wait for the F-Droid release in a couple of days
