### ISSUE TITLE
"invalid API key"

### ISSUE THREAD

**Issue by metbic** [martykan/forecastie#619]
Loading new weather data impossible since 24 hrs.
Instead tells me "invalid API key".

**Comment by metbic** [comment]
Android version is 9 (Sony) 
Forecastie version is 1.18.0

**Comment by BAESI** [comment]
There is a problem at the moment.  See #618 If you want to use it, sign up for OpenweatherMap, receive your own key, and enter it.

**Comment by robinpaulson** [comment]
really? the very next issue includes "invalid api key". closing, dupe

**Comment by mrtootoo** [comment]
> There is a problem at the moment. See #618 If you want to use it, sign up for OpenweatherMap, receive your own key, and enter it.

So I signed up for OpenweatherMap, retrieved api.  But I am not sure if I requested the correct data or am using properly as I still get invalid api.  I chose the One Call API.  Any recommendations you have are appreciated.
