### ISSUE TITLE
Feature request: indicate last update in widget

### ISSUE THREAD

**Issue by benedetto** [martykan/forecastie#62]
Since I don't have a data plan on my mobile phone it is normally not online unless I'm somewhere with WIFI access (home, work, friends). That means that I cannot tell for sure when was the last time that forecastie had the opportunity to update its weather information. If I want to go sure that it's updated, I hit the small update button (round arrow) on the widget. However, the only indication that the information has been updated is if the information shown changes, which can be hard to tell if the changes are slight ("It says 4.2 degrees now, but was it 4.3 before or did it not change at all???").

Hence it would be nice if the widget should either show a time stamp that indicates when the information has been updated the last time or at least some indicator that an update is currently performed and when it has finished – something like the update arrow rotating while the update is in progress.

**Comment by SpiritCroc** [comment]
Sorry for the multiple commits that reference this issues and I deleted later; will create a pull-request when I'm finally happy with it
