### ISSUE TITLE
Search for location results in "Invalid API Key

### ISSUE THREAD

**Issue by Jfh79** [martykan/forecastie#623]
Running on Sony  Xperia XZ 2 compact, Lineage 18.1. 

Android 11 
lineage_xz2c-userdebug 11 RQ3A.211001.001 eng.root.20211109.083801 dev-keys

**Comment by ajinzrathod** [comment]
Same here

**Comment by robinpaulson** [comment]
Yes, it uses the same API as the rest of the code.
