### ISSUE TITLE
Broken Layout with version 1.18.2

### ISSUE THREAD

**Issue by tuch96** [martykan/forecastie#628]
Today I have install the new 1.18.2 version over f-droid on my Pixel 1 and the layout does not look like the same to version 1.18.0. My screen size: 1920 × 1080.

![Screenshot_20211211-221421_Forecastie](https://user-images.githubusercontent.com/57192210/145692242-a62660ac-3df1-432f-86cc-96b9e22f79a5.png)

**Comment by robinpaulson** [comment]
Yah, I thought this might happen. It was caused by this #602 . For the short-term, best option is to use v1.18 and manually add the API Key.

**Comment by robinpaulson** [comment]
When I figure out git revert, I'll undo the offending commits and release a new version, with the new API key.

**Comment by robinpaulson** [comment]
I think I did it .... v1.19 will be out in a few days, with new API key, without changes which broke the UI.

**Comment by robinpaulson** [comment]
Locking the conversation so we don't get a flood "me too" comments like issue 618.

**Comment by robinpaulson** [comment]
Nope, that didn't fix it, 1.19 and 1.19.1 are broken too.

**Comment by robinpaulson** [comment]
@yuhuitech Your help would be appreciated here, undoing the problem your commit caused.
