### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by Billeffinggates** [martykan/forecastie#633]
Widget/app hasn't been working for a week or two. Updates are current. Running on Lineage OS.
![Screenshot_20211214-085714_Forecastie](https://user-images.githubusercontent.com/96133716/146033542-2317b48e-750f-477f-9efc-8f7de4dfa1ed.png)

**Comment by ignaqui** [comment]
As a workaround, I've created an API key on openweathermap.org, and use it with forecastie

**Comment by robinpaulson** [comment]
Guys, read the other issues before posting.
