### ISSUE TITLE
Somebody is using our API key for other projects

### ISSUE THREAD

**Issue by robinpaulson** [martykan/forecastie#634]
I don't know who it is or what the project is, but we are already over the One Call API limit for each day.

If this continues, the key will be cancelled by OWM.

I have got another, but if the same thing happens again, there's nothing else I can do, no more weather forecasts unless users sign up for their own key.

**Comment by robinpaulson** [comment]
Install v1.21 for the new key, due in a few days.

**Comment by igor-cali** [comment]
Any idea for the key not be human readable in the source code?

**Comment by robinpaulson** [comment]
@igor-cali I'm not sure how to do that. I made a mistake posting it in another issue, I shouldn't have done that.

**Comment by igor-cali** [comment]
> @igor-cali I'm not sure how to do that. I made a mistake posting it in another issue, I shouldn't have done that.

You may cancel/update that post.

**Comment by robinpaulson** [comment]
Unfortunately, I fear that won't prevent the current person who is using it.

v1.21 with the new key will be out in a few days, then I'll cancel the compromised key and hopefully all will be good.

**Comment by woheller69** [comment]
Are you sure someone else is using the key? One call API limit is 1000 calls per day. You do not need more than a handful of users to reach that limit...

**Comment by woheller69** [comment]
with one call API everyone needs his own key. That is what I did in RadarWeather.

Regarding increased limit I was already in contact with OWM and got the answer " that FOSS access does not and will not be increasing limits for One Call API." #499

**Comment by robinpaulson** [comment]
We don't use one call anywhere

**Comment by woheller69** [comment]
First sentence of this issue...
  ", but we are already over the One Call API limit for each day."

**Comment by robinpaulson** [comment]
Yep

**Comment by robinpaulson** [comment]
OK, the key has been cancelled, v1.21 is out with the new key.

**Comment by robinpaulson** [comment]
Closing, v1.21 has been out a couple of days with no obvious problems

**Comment by shortspider** [comment]
@robinpaulson when will the google play version be updated?

**Comment by robinpaulson** [comment]
Ah, Google, yes. @martykan handles that. Tomas?
