### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by cpo-ux** [martykan/forecastie#639]
Hi,

I'm running version 1.20 on Android 10 on Samsung S9. The app doesn't load weather data and it reports invalid API key in toast message.  I cleared app data and uninstalled and reinstalled and I have the same issue. It doesn't allow searching for another city.  When searching for another city it reports invalid API key. Reviews on Google Play store also report this issue.

**Comment by robinpaulson** [comment]
Upgrade to 1.21

**Comment by Lee-Carre** [comment]
@cpo-ux see #634 & #635.
