### ISSUE TITLE
NWS Severe Weather Alerts

### ISSUE THREAD

**Issue by HonestAbe7** [martykan/forecastie#640]
I would like to see this app at least show NWS weather alerts; but also give notifications as well. I use an app called Severe Weather Alerts which needs Google Play Services enabled in order to get them. This would allow me to completely ditch Google Play services. Thanks considering doing this.

**Comment by Lee-Carre** [comment]
@HonestAbe7 try [NWS Weather Alerts](http://github.com/justdave/nwsweatheralertswidget) (available via F-Droid).

**Comment by Lee-Carre** [comment]
Separately, this request seems to have all the same problems of #126.

**Comment by Lee-Carre** [comment]
@HonestAbe7 would your needs be covered by #192 ?

If not; what do NWS alerts offer which #192 wouldn't?

**Comment by HonestAbe7** [comment]
@Lee-Carre  Yes, an alert to possible rain or snow coming would be nice. Even changing seasons.

**Comment by HonestAbe7** [comment]
I have decided delete the Severe Weather Alerts app since it doesn't seem very reliable. Just want to know what could be coming, knowing that the weather can and does change.

**Comment by robinpaulson** [comment]
I'm going to close this, the essence of it is included in the existing issues #126 and, #157 and #192
