### ISSUE TITLE
API key error

### ISSUE THREAD

**Issue by paulwittle** [martykan/forecastie#641]
Hi,
Just downloaded your app and it does seem to be reporting an API error. Could see a review commenting on the error but not a bug report so I thought I'd add one. Does your key need renewing?

I did try adding my own key but same result; does it need to be more than the basic free API key?

Thanks

**Comment by robinpaulson** [comment]
I guess you're using v1.20? v1.21 is out now, with a new API key. see #635

**Comment by paulwittle** [comment]
My key worked once I confirmed my email address however there may still be an issue with the default one (if there is one) as the personal API key seems to be described as optional. 

In any case I'll close the ticket and leave it to you to look if there is an issue. Thanks
