### ISSUE TITLE
Forecastie stopped updating weather

### ISSUE THREAD

**Issue by msdosfx** [martykan/forecastie#653]
My app stopped updating the weather as of 1-22-22. Today is the 25th. The widget shows the correct time and date, but wrong temperature. Then when I open the app, it says last update 1-22-22. Under "today" it says saturday. Under the tomorrow tab it says wed. when I try to refresh it says "downloading your data" and never finishes. I tried changing my API key, but that didn't work. I am running a Pixel 4a on CalyxOS. The app has worked for me for many months, so I know it works on this OS

**Comment by robinpaulson** [comment]
Which version ate you using? Could you remove your key, falling back to the default?

**Comment by msdosfx** [comment]
I deleted the app and tried to download again to get latest version from F-droid. It failed to download so I downloaded the APK from F-droid.org . It seems in latest build you can not just enter in your location. I do not want to enable the app to track my location. I would rather just enter in my location, but it doesn't seem like this is an option. In any case it seems the weather is updating, but it doesn't have my correct location.

**Comment by msdosfx** [comment]
So, I allowed it to detect my location "just this one time" in my settings, and because I use an always on VPN it doesn't have the correct location. It would really be much simpler and less invasive if I could just enter in a zip or coordinates and use that for location. Then it would also be much simpler to check the weather at other locations that I might be visiting soon as well.

**Comment by msdosfx** [comment]
Ah, I am an idiot. You can use the search magnifying glass to enter the location.
