### ISSUE TITLE
Saved/Favorite Locations

### ISSUE THREAD

**Issue by Noctudeit** [martykan/forecastie#656]
It would be great if we could create saved/bookmarked/favorited locations so those of us who travel can keep tabs on the weather back home. Even better if we could map a separate widget to a saved location so that we could see both current location and a saved location at a glance.

Thanks for all of your work on this project!

**Comment by robinpaulson** [comment]
I think an issue for this exists already, maybe it's a component of the multiple locations issue?

**Comment by robinpaulson** [comment]
#76
