### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 0.9.1.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [martykan/forecastie#66]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 0.9.1.

**Comment by martykan** [comment]
Done. 
https://gitlab.com/fdroid/fdroiddata/merge_requests/1237

**Comment by locutis-of-borg-1999** [comment]
B-) 8-)  Cool.  

Thanks.
