### ISSUE TITLE
still invalid key 

### ISSUE THREAD

**Issue by skyerjoe** [martykan/forecastie#670]
Phone:  mi9t pro mui global 12.5.1 based on Android 11
App: forecastie 1.221

Hello

My app shows still "invalid key" if i want to weather data with pull the screen or change the Location

Best regards

**Comment by robinpaulson** [comment]
I've got 1.22.1, it's working fine. Have you set an expired API key in the settings? The default key works fine.

**Comment by Korb** [comment]
I created an API key at https://home.openweathermap.org/api_keys with a free plan, and entered the number in the corresponding field of the application settings. When I try to update the forecast, I get a message about an invalid API key. When I remove my API key from the settings, the forecast downloads fine.

Forecastie 1.22.1, Blackview BV8000 Pro (Android 7.0).

**Comment by skyerjoe** [comment]
I had an invalid key  in the settings

After an update it works now

**Comment by Korb** [comment]
> After an update it works now

> Version 1.22.1 (74) added on 2022-02-23

— is this version (latest on F-Droid) already fixed?

**Comment by skyerjoe** [comment]
no problems anymore so far, everything works fine  
and yes my app version is 1.22.1 from f-droid

best regards
