### ISSUE TITLE
Feature Request: Smaller 2x1 widget

### ISSUE THREAD

**Issue by sbruder** [martykan/forecastie#68]
Hi,
This is the best weather app for Android I found, but the widget is too big for me. I would like a 2x1 (or 4x1) widget like the weather panel in CMs cLock.
Thanks

**Comment by entodoays** [comment]
I was going to suggest this enhancement as well. A 4x1 widget with time on the left and weather on the right, possibly semi-transparent background. Tapping on the time could open clocks and tapping on the weather could open the weather app.

**Comment by Linkid** [comment]
Hi! I'm working on a smaller widget (2x1).

**Comment by robinpaulson** [comment]
Hi @Linkid how is your 2x1 widget going? If it is ready or you need assistance, let us know! Or make a PR.

**Comment by Linkid** [comment]
Sorry, I was fighting against the refresh button on the widget. I restarted from the TimeWidget and it's working now.

**Comment by robinpaulson** [comment]
Excellent, that's great news. A screenshot would be a big help.

**Comment by robinpaulson** [comment]
Merged, this will show up in v1.5 in 3 weeks
