### ISSUE TITLE
Widget has partial functionality

### ISSUE THREAD

**Issue by ACOdell** [martykan/forecastie#74]
I'm running on a Moto E (Cyanogenmod 13.0, Android 6.0.1 equivalent), and I only get the icon that shows the weather condition outside (cloudy, stormy, clear, etc.) but no other data. It's not an issue of the app getting the data, because when I open the app proper all the info is right there, I just don't know why the widget isn't 

Screenshot [here](http://imgur.com/r6M7AKT).

**Comment by anlar** [comment]
Currently it's not working as 4x1 widget. To see whole widget resize it to 4x3.

**Comment by ACOdell** [comment]
Yuuup, that works. Thanks for the help!
