### ISSUE TITLE
Detect Location does not work

### ISSUE THREAD

**Issue by DatGizmo** [martykan/forecastie#75]
Versions: 
- Android: CM 12.1-20160329-Nigtly for Xperia Z3 Compact 
- Kernel: 3.4.0
- Forcastie: 0.9.1 insalled via f-droid

I have the Privacy Guard activated.
The app doesn't ask for permission to use the Location.
Even after allow access to the location, the app doesn't apper in the lis of apps, which used the location.
Side note, instead of gapps I'm using microG apps. https://microg.org
But I think, that it is not related to microG, because to me it seems, that the app doesn't try to use the location.

**Comment by githwithit** [comment]
I have the same issue and can not use the app.

I'm on a Nexus 7 2013 running CM13 and Forcastie 1.0 from Fdroid.

I allow location and it still doesn't find me.

Could a manual location entry be allowed?

Like city/country or even GPS coordinates?

**Comment by martykan** [comment]
The app does ask for permission on marshmallow, not sure how it works with privacy guard.

@githwithit Does it actually have GPS? Manual entry is obviously allowed - it's the search function.

**Comment by DatGizmo** [comment]
Found out, that the app actually does ask for GPS permission. But only if GPS is enabled. 
If the position mode is only set to GSM position the app does not ask for the permission.

So the app only works with GPS but not with GSM positions.
Don't know if this is intended.

**Comment by mase76** [comment]
Is it a good idea always to use GPS for location? I think the system's location service is exact enough and faster.

**Comment by juanitobananas** [comment]
>The app does ask for permission on marshmallow, not sure how it works with privacy guard.

Privacy Guard won't ask for the user to grant permission until the moment where the app actually tries to determine a location. If GPS is not enabled, the app cannot try to get a location and therefore Privacy Guard doesn't ask for permission.

It also works for me on Android M :smile: 

I've taken a look at the code and I think a solution for this would be to use the LocationManager to check if the LocationProvider is enabled (`locationManager.isProviderEnabled(String provider)`) and show a dialog informing the user that s/he should change the location settings in order for forecastie to be able to determine the location. A lot of apps even have a button to go directly to the Android location settings.

This should be pretty easy to implement. @martykan: If you wish, I could gladly do it :smile:

**Comment by robinpaulson** [comment]
@juanitobananas 

> This should be pretty easy to implement. If you wish, I could gladly do it

Please do!

**Comment by juanitobananas** [comment]
@robinpaulson 

>>This should be pretty easy to implement. If you wish, I could gladly do it

>Please do!

As far as I can see, I already implemented this:
5cbddac309d30fdfd231f8ec71f00d659cb7820b

I am just not quite sure if I meant something else... I haven't taken a look at this since then 😄

**Comment by robinpaulson** [comment]
@juanitobananas 
so you did. Could you take a look and decide if this closes the bug or not?

Also, @DatGizmo Could you let us know what you think?

**Comment by juanitobananas** [comment]
> Could you take a look and decide if this closes the bug or not?

As far as I can see, this issue is already solved.

**Comment by robinpaulson** [comment]
great, closing
