### ISSUE TITLE
Feature Request: % Chance of Rain

### ISSUE THREAD

**Issue by ghost** [martykan/forecastie#79]
It would be helpful to see a % chance of rain on the forecasts. An extremely low possibility of rain on other apps/services will still just show 'rain' on Forecastie

**Comment by martykan** [comment]
Sorry, but OpenWeatherMap doesn't provide this data with their API. I will keep this issue open if they add the support.

**Comment by robinpaulson** [comment]
@ghost
Would you be willing to look through the OWM API to see if this feature is supported by them yet?

Thanks
