### ISSUE TITLE
Always current location

### ISSUE THREAD

**Issue by mase76** [martykan/forecastie#87]
Hi!
Please add an option to get the current location with every refresh. And please add more refresh rates (2 and 6 hours for example).

**Comment by Nutomic** [comment]
Agreed, current location should be the default (instead of always using London as default).

**Comment by juanitobananas** [comment]
Added option to update location automatically in c6093eccc6a0ccc9543f576c19813bc55eabc0c4
(it isn't enabled by default though)

**Comment by martykan** [comment]
@juanitobananas I think we can consider this issue resolved then.
