### ISSUE TITLE
Use integer values for temperatures

### ISSUE THREAD

**Issue by mabkenar** [martykan/forecastie#98]
I don't think people really care about sub-integer temperatures. I mean, 17°C and 17.4°C is essentially the same temperature to me. Moreover, reporting temperature of a 3 hour period with 0.1°C accuracy is not really meaningful since the temperature will surely fluctuate during this time and through the region.

Rounding all temperatures to integer values instead removes some clutter from the app, making it more useful when you want to very quickly check the weather.

At the end, this is my personal taste. Feel free to close this issue. I am already very thankful for this beautiful and useful app that you have made.

**Comment by martykan** [comment]
I added an option to the settings.

**Comment by mabkenar** [comment]
Thank you! I'll wait for F-Droid to sync the new version and I'll try it.

**Comment by artem-p** [comment]
I did not find this option in the settings.

**Comment by martykan** [comment]
Yeah, you are right. I will fix it.

Dne pá 5. 8. 2016 22:30 uživatel artem-p <notifications@github.com> napsal:

**Comment by zoff99** [comment]
hold on, please don't remove the sub-integer values

**Comment by martykan** [comment]
I just want to add an option to the settings.

Dne so 6. 8. 2016 9:50 uživatel Zoff <notifications@github.com> napsal:

**Comment by martykan** [comment]
I found the code on my old PC, I forgot to push it to origin.
So it should be done.
